### ISSUE TITLE
nbgrader does not work with SQLAlchemy 1.3

### ISSUE THREAD

**Issue by soldis** [jupyter/nbgrader#1073]
### Operating system
4.15.0-29-generic #31-Ubuntu SMP Tue Jul 17 15:39:52 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

### `nbgrader --version`
Python version 3.6.7 (default, Oct 22 2018, 11:32:17)
[GCC 8.2.0]
nbgrader version 0.5.5

### `jupyterhub --version` (if used with JupyterHub)
0.9.4

### `jupyter notebook --version` 
5.7.6

### Expected behavior
autograding, manual grading and watching submissions should work

### Actual behavior
they don't work

### Steps to reproduce the behavior

In formgrader when I go to "Manage Assignments" -> Submissions list (and in some other places in GUI - but the error is the same) I get "Loading, please wait..." and nothing happens. In log file:

Traceback (most recent call last):
      File "/usr/local/lib/python3.6/dist-packages/tornado/web.py", line 1697, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/usr/local/lib/python3.6/dist-packages/tornado/web.py", line 3174, in wrapper
        return method(self, *args, **kwargs)
      File "/usr/local/lib/python3.6/dist-packages/nbgrader/server_extensions/formgrader/base.py", line 103, in wrapper
        return f(self, *args, **kwargs)
      File "/usr/local/lib/python3.6/dist-packages/nbgrader/server_extensions/formgrader/apihandlers.py", line 146, in get
        submissions = self.api.get_submissions(assignment_id)
      File "/usr/local/lib/python3.6/dist-packages/nbgrader/apps/api.py", line 560, in get_submissions
        db_submissions = gb.submission_dicts(assignment_id)
      File "/usr/local/lib/python3.6/dist-packages/nbgrader/api.py", line 2372, in submission_dicts
        ).join(SubmittedNotebook, Notebook, Assignment, Student, Grade, GradeCell)\ 
      File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/orm/query.py", line 2235, in join
        from_joinpoint=from_joinpoint,
      File "<string>", line 2, in _join
      File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/orm/base.py", line 220, in generate
        fn(self, *args[1:], **kw)
      File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/orm/query.py", line 2414, in _join
        left, right, onclause, prop, create_aliases, outerjoin, full
      File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/orm/query.py", line 2437, in _join_left_to_right
        ) = self._join_determine_implicit_left_side(left, right, onclause)
      File "/usr/local/lib/python3.6/dist-packages/sqlalchemy/orm/query.py", line 2568, in _join_determine_implicit_left_side
        **"Can't determine which FROM clause to join "
    sqlalchemy.exc.InvalidRequestError: Can't determine which FROM clause to join from, there are multiple FROMS which can join to this entity. Try adding an explicit ON clause to help resolve the ambiguity.**

After install sqlalchemy-1.2.18 everything works fine.

**Comment by mhwasil** [comment]
I faced the same problem, installing sqlalchemy-1.2.18 solved the problem.

**Comment by jhamrick** [comment]
Thanks for reporting this!

**Comment by jhamrick** [comment]
Should be fixed by #1080

**Comment by JoostBerkhout** [comment]
I installed nbgrader this weekend (using Anaconda 3) and I faced the same problem, installing sqlalchemy-1.2.18 solved the problem also for me.
