### ISSUE TITLE
Autograde fails due to missing regex match

### ISSUE THREAD

**Issue by thiippal** [jupyter/nbgrader#1077]
### Operating system
macOS 10.12.6 (Sierra)

### `nbgrader --version`
`nbgrader version 0.5.5`

### `jupyter notebook --version` 
`5.7.4`

### Expected behavior

I have submissions from my students in separate folders in `submitted/assignment_id/student_id/exercise_1.ipynb`. The directory is under the working directory, as expected, and I can see the students and their submitted assignments in formgrader. I want to autograde the notebooks manually or from the command line using `nbgrader autograde assignment_id`.

### Actual behavior

nbgrader executes the following actions, but then raises an error. Note that I've modified the logs to mask the student identifier.

```
[AutogradeApp | INFO] Overwriting files with master versions from the source directory
[AutogradeApp | INFO] Sanitizing ./submitted/intro_to_python/STUDENT/exercise_1.ipynb
[AutogradeApp | INFO] Converting notebook ./submitted/intro_to_python/STUDENT/exercise_1.ipynb
[AutogradeApp | ERROR] Could not match './submitted/intro_to_python/STUDENT/exercise_1.ipynb' with regexp '\.\/submitted\/(?P<assignment_id>.*)\/(?P<student_id>.*)\/\/(?P<notebook_id>.*).ipynb'
[AutogradeApp | ERROR] There was an error processing assignment: ./submitted/intro_to_python/STUDENT/
[AutogradeApp | ERROR] Traceback (most recent call last):
      File "/Users/thiippal/digi/lib/python3.6/site-packages/nbgrader/converters/base.py", line 293, in convert_notebooks
        self.convert_single_notebook(notebook_filename)
      File "/Users/thiippal/digi/lib/python3.6/site-packages/nbgrader/converters/autograde.py", line 174, in convert_single_notebook
        super(Autograde, self).convert_single_notebook(notebook_filename)
      File "/Users/thiippal/digi/lib/python3.6/site-packages/nbgrader/converters/base.py", line 248, in convert_single_notebook
        resources = self.init_single_notebook_resources(notebook_filename)
      File "/Users/thiippal/digi/lib/python3.6/site-packages/nbgrader/converters/base.py", line 126, in init_single_notebook_resources
        raise NbGraderException(msg)
    nbgrader.converters.base.NbGraderException: Could not match './submitted/intro_to_python/STUDENT/exercise_1.ipynb' with regexp '\.\/submitted\/(?P<assignment_id>.*)\/(?P<student_id>.*)\/\/(?P<notebook_id>.*).ipynb'
```

My `nbgrader_config.py` has the following lines related to `notebook_id`:

`c.CourseDirectory.notebook_id = '*'`
`c.CourseDirectory.root = '.'`
`c.CourseDirectory.student_id = '*'`

The assignment ID is commented out.
`# c.CourseDirectory.assignment_id = ''`

What am I doing wrong with nbgrader configuration?

**Comment by thiippal** [comment]
Alright, I've identified my error and will document it here in case someone else is repeating my mistake.

I had modified the following line in my `nbgrader_config.py` to reflect the changes I made to the directory structure for student work:

`c.CourseDirectory.directory_structure = '{nbgrader_step}/{assignment_id}/{student_id}/'`

The error was caused by the final slash. Changing the line to the following fixed the problem:

`c.CourseDirectory.directory_structure = '{nbgrader_step}/{assignment_id}/{student_id}'`
