### ISSUE TITLE
Autograder not recognizing grade cells

### ISSUE THREAD

**Issue by michaeld32** [jupyter/nbgrader#1234]
### Operating system
Windows 10 and OSX Mojave

### `nbgrader --version` 
0.5.6

### `jupyter notebook --version`
5.7.4

### Expected behavior
Autograde assignments. Files are submitted, I can manually open them and they seem not corrupted.

### Actual behavior
Traceback error where the first graded cell is not being recognized, even though the cell shows up in the metadata. I have already tried removing the assignment and re-generating it, and them having students resubmit the assignment based on the new version of the released file to no avail.

### Steps to reproduce the behavior
Anytime I try to autograde any of the submissions for this assignment.
Here's the full traceback I get within formgrader
      [INFO] Copying C:\Users\micha\CSP Autograde\submitted\kombucha_kat\Homework 2.2\desktop.ini -> C:\Users\micha\CSP Autograde\autograded\kombucha_kat\Homework 2.2\desktop.ini
      [INFO] Creating/updating student with ID 'kombucha_kat': {}
      [INFO] Overwriting files with master versions from the source directory
      [INFO] Sanitizing C:\Users\micha\CSP Autograde\submitted\kombucha_kat\Homework 2.2\Homework 2.2.ipynb
      [INFO] Converting notebook C:\Users\micha\CSP Autograde\submitted\kombucha_kat\Homework 2.2\Homework 2.2.ipynb
      [ERROR] There was an error processing assignment: C:\Users\micha\CSP Autograde\submitted\kombucha_kat\Homework 2.2
      [ERROR] Traceback (most recent call last):
      File "C:\ProgramData\Anaconda3\lib\site-packages\nbgrader\api.py", line 1479, in find_grade_cell
        Assignment.name == assignment)\
      File "C:\ProgramData\Anaconda3\lib\site-packages\sqlalchemy\orm\query.py", line 2960, in one
        raise orm_exc.NoResultFound("No row was found for one()")
    sqlalchemy.orm.exc.NoResultFound: No row was found for one()
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "C:\ProgramData\Anaconda3\lib\site-packages\nbgrader\converters\base.py", line 293, in convert_notebooks
        self.convert_single_notebook(notebook_filename)
      File "C:\ProgramData\Anaconda3\lib\site-packages\nbgrader\converters\autograde.py", line 174, in convert_single_notebook
        super(Autograde, self).convert_single_notebook(notebook_filename)
      File "C:\ProgramData\Anaconda3\lib\site-packages\nbgrader\converters\base.py", line 249, in convert_single_notebook
        output, resources = self.exporter.from_filename(notebook_filename, resources=resources)
      File "C:\ProgramData\Anaconda3\lib\site-packages\nbconvert\exporters\exporter.py", line 179, in from_filename
        return self.from_file(f, resources=resources, **kw)
      File "C:\ProgramData\Anaconda3\lib\site-packages\nbconvert\exporters\exporter.py", line 197, in from_file
        return self.from_notebook_node(nbformat.read(file_stream, as_version=4), resources=resources, **kw)
      File "C:\ProgramData\Anaconda3\lib\site-packages\nbconvert\exporters\notebook.py", line 32, in from_notebook_node
        nb_copy, resources = super(NotebookExporter, self).from_notebook_node(nb, resources, **kw)
      File "C:\ProgramData\Anaconda3\lib\site-packages\nbconvert\exporters\exporter.py", line 139, in from_notebook_node
        nb_copy, resources = self._preprocess(nb_copy, resources)
      File "C:\ProgramData\Anaconda3\lib\site-packages\nbconvert\exporters\exporter.py", line 316, in _preprocess
        nbc, resc = preprocessor(nbc, resc)
      File "C:\ProgramData\Anaconda3\lib\site-packages\nbconvert\preprocessors\base.py", line 47, in __call__
        return self.preprocess(nb, resources)
      File "C:\ProgramData\Anaconda3\lib\site-packages\nbgrader\preprocessors\overwritecells.py", line 20, in preprocess
        nb, resources = super(OverwriteCells, self).preprocess(nb, resources)
      File "C:\ProgramData\Anaconda3\lib\site-packages\nbconvert\preprocessors\base.py", line 69, in preprocess
        nb.cells[index], resources = self.preprocess_cell(cell, resources, index)
      File "C:\ProgramData\Anaconda3\lib\site-packages\nbgrader\preprocessors\overwritecells.py", line 74, in preprocess_cell
        self.assignment_id)
      File "C:\ProgramData\Anaconda3\lib\site-packages\nbgrader\api.py", line 1482, in find_grade_cell
        raise MissingEntry("No such grade cell: {}/{}/{}".format(assignment, notebook, name))
    nbgrader.api.MissingEntry: No such grade cell: Homework 2.2/Homework 2.2/cell-fc0ad483da432d2c
    
[WARNING] Removing failed assignment: C:\Users\micha\CSP Autograde\autograded\kombucha_kat\Homework 2.2
[ERROR] There was an error processing assignment 'Homework 2.2' for student 'kombucha_kat'
[ERROR] Please see the the above traceback for details on the specific errors on the above failures.

**Comment by michaeld32** [comment]
Fixed by manually updating to 0.6.0
