### ISSUE TITLE
Error with the courses list tab in Jupyterhub

### ISSUE THREAD

**Issue by whositwhatnow** [jupyter/nbgrader#1247]
Brand new install latest versions of jupyterhub and nbgrader.
I'm working on my configurations and getting formgrader ready for testing.  When i click on the courses tab i get teh following error:

Traceback (most recent call last): File "/usr/local/lib/python3.6/site-packages/nbgrader/server_extensions/course_list/handlers.py", line 175, in get local_courses = yield self.check_for_local_formgrader(config) File "/usr/local/lib/python3.6/site-packages/tornado/gen.py", line 735, in run value = future.result() File "/usr/local/lib/python3.6/site-packages/tornado/gen.py", line 742, in run yielded = self.gen.throw(*exc_info) # type: ignore File "/usr/local/lib/python3.6/site-packages/nbgrader/server_extensions/course_list/handlers.py", line 69, in check_for_local_formgrader response = yield http_client.fetch(url, headers=header) File "/usr/local/lib/python3.6/site-packages/tornado/gen.py", line 735, in run value = future.result() File "/usr/local/lib/python3.6/site-packages/tornado/simple_httpclient.py", line 336, in run source_ip=source_ip, File "/usr/local/lib/python3.6/site-packages/tornado/tcpclient.py", line 294, in connect False, ssl_options=ssl_options, server_hostname=host File "/usr/local/lib/python3.6/site-packages/tornado/iostream.py", line 1391, in _do_ssl_handshake self.socket.do_handshake() File "/usr/local/lib/python3.6/ssl.py", line 1077, in do_handshake self._sslobj.do_handshake() File "/usr/local/lib/python3.6/ssl.py", line 689, in do_handshake self._sslobj.do_handshake() ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)

I have a valid SSL cert so i dont know what its talking about.

**Comment by whositwhatnow** [comment]
I went through my nbgrader_config.py again.  Restarted teh server isntance now I am getting the following error:

Traceback (most recent call last): File "/usr/local/lib/python3.6/site-packages/nbgrader/server_extensions/course_list/handlers.py", line 173, in get config = self.load_config() File "/usr/local/lib/python3.6/site-packages/nbgrader/server_extensions/course_list/handlers.py", line 53, in load_config full_config.merge(config) File "/usr/local/lib/python3.6/site-packages/traitlets/config/loader.py", line 185, in merge for k, v in other.items(): **AttributeError: 'tuple' object has no attribute 'items'**

**Comment by whositwhatnow** [comment]
read through #1245, made some of the changes now back to square one with the SSL error

**Comment by jhamrick** [comment]
Is this a self-signed certificate? If so it sounds like the same issues as #1220

**Comment by whositwhatnow** [comment]
No, I’m using my own cert

Email sent from my phone.
________________________________

**Comment by whositwhatnow** [comment]
I think I fixed the issue on my end.  I was only using our wildcard root cert.  I combined root intermediate into a chainand pointed it to that file error disappeared.
