### ISSUE TITLE
one student can't Autograde

### ISSUE THREAD

**Issue by xin2v** [jupyter/nbgrader#1302]
### Operating system
Ubuntu 16.04.6 LTS 64 bit 
### `nbgrader --version`
nbgrader version 0.6.1
### `jupyterhub --version` (if used with JupyterHub)
$ jupyterhub --version
0.9.6
### `jupyter notebook --version` 
$ jupyter notebook --version
6.0.0
### Expected behavior
Autograde for all students 
### Actual behavior
only one student can't Autograde, click Autograde have error as follow 

*******Log Output
[INFO] Copying /home/dku-dasc-02/Stats102/submitted/wms16/q3/jupyter.png -> /home/dku-dasc-02/Stats102/autograded/wms16/q3/jupyter.png
[INFO] Copying /home/dku-dasc-02/Stats102/submitted/wms16/q3/timestamp.txt -> /home/dku-dasc-02/Stats102/autograded/wms16/q3/timestamp.txt
[INFO] Creating/updating student with ID 'wms16': {}
[INFO] SubmittedAssignment<q3 for wms16> submitted at 2020-01-12 03:14:55.209492
[INFO] Overwriting files with master versions from the source directory
[INFO] Copying /home/dku-dasc-02/Stats102/source/./q3/jupyter.png -> /home/dku-dasc-02/Stats102/autograded/wms16/q3/jupyter.png
[WARNING] Skipping unknown notebook: /home/dku-dasc-02/Stats102/submitted/wms16/q3/WMS q3.ipynb
[ERROR] No notebooks found, did you forget to run 'nbgrader generate_assignment'?
[ERROR] There was an error processing assignment: /home/dku-dasc-02/Stats102/submitted/wms16/q3
[ERROR] Traceback (most recent call last):
      File "/home/dku-dasc-02/anaconda3/lib/python3.6/site-packages/nbgrader/converters/base.py", line 332, in convert_notebooks
        self.init_assignment(gd['assignment_id'], gd['student_id'])
      File "/home/dku-dasc-02/anaconda3/lib/python3.6/site-packages/nbgrader/converters/autograde.py", line 154, in init_assignment
        raise NbGraderException(msg)
    nbgrader.converters.base.NbGraderException: No notebooks found, did you forget to run 'nbgrader generate_assignment'?
    
[WARNING] Removing failed assignment: /home/dku-dasc-02/Stats102/autograded/wms16/q3
[ERROR] There was an error processing assignment 'q3' for student 'wms16'
[ERROR] Please see the the above traceback for details on the specific errors on the above failures.

**********Traceback

Traceback (most recent call last):
  File "/home/dku-dasc-02/anaconda3/lib/python3.6/site-packages/nbgrader/utils.py", line 514, in capture_log
    app.start()
  File "/home/dku-dasc-02/anaconda3/lib/python3.6/site-packages/nbgrader/converters/base.py", line 74, in start
    self.convert_notebooks()
  File "/home/dku-dasc-02/anaconda3/lib/python3.6/site-packages/nbgrader/converters/base.py", line 413, in convert_notebooks
    raise NbGraderException(msg)
nbgrader.converters.base.NbGraderException: Please see the the above traceback for details on the specific errors on the above failures.

**Comment by xin2v** [comment]
needs autograding
![student](https://user-images.githubusercontent.com/59700447/72220357-dbf13b00-358a-11ea-8cd4-ee09ef44f9ef.JPG)

**Comment by xin2v** [comment]
error screen capture
![student2](https://user-images.githubusercontent.com/59700447/72220448-b0228500-358b-11ea-8f06-8ce038011244.JPG)

**Comment by xin2v** [comment]
I create a new user test again , but same error 

Log Output
[INFO] Copying /home/dku-dasc-02/Stats102/submitted/wms161/q6/jupyter.png -> /home/dku-dasc-02/Stats102/autograded/wms161/q6/jupyter.png
[INFO] Copying /home/dku-dasc-02/Stats102/submitted/wms161/q6/timestamp.txt -> /home/dku-dasc-02/Stats102/autograded/wms161/q6/timestamp.txt
[INFO] Creating/updating student with ID 'wms161': {}
[INFO] SubmittedAssignment<q6 for wms161> submitted at 2020-01-15 01:32:22.195787
[INFO] Overwriting files with master versions from the source directory
[INFO] Copying /home/dku-dasc-02/Stats102/source/./q6/jupyter.png -> /home/dku-dasc-02/Stats102/autograded/wms161/q6/jupyter.png
[WARNING] Skipping unknown notebook: /home/dku-dasc-02/Stats102/submitted/wms161/q6/WMS.ipynb
[ERROR] No notebooks found, did you forget to run 'nbgrader generate_assignment'?
[ERROR] There was an error processing assignment: /home/dku-dasc-02/Stats102/submitted/wms161/q6
[ERROR] Traceback (most recent call last):
      File "/home/dku-dasc-02/anaconda3/lib/python3.6/site-packages/nbgrader/converters/base.py", line 332, in convert_notebooks
        self.init_assignment(gd['assignment_id'], gd['student_id'])
      File "/home/dku-dasc-02/anaconda3/lib/python3.6/site-packages/nbgrader/converters/autograde.py", line 154, in init_assignment
        raise NbGraderException(msg)
    nbgrader.converters.base.NbGraderException: No notebooks found, did you forget to run 'nbgrader generate_assignment'?
    
[WARNING] Removing failed assignment: /home/dku-dasc-02/Stats102/autograded/wms161/q6
[ERROR] There was an error processing assignment 'q6' for student 'wms161'
[ERROR] Please see the the above traceback for details on the specific errors on the above failures.
Traceback
Traceback (most recent call last):
  File "/home/dku-dasc-02/anaconda3/lib/python3.6/site-packages/nbgrader/utils.py", line 514, in capture_log
    app.start()
  File "/home/dku-dasc-02/anaconda3/lib/python3.6/site-packages/nbgrader/converters/base.py", line 74, in start
    self.convert_notebooks()
  File "/home/dku-dasc-02/anaconda3/lib/python3.6/site-packages/nbgrader/converters/base.py", line 413, in convert_notebooks
    raise NbGraderException(msg)
nbgrader.converters.base.NbGraderException: Please see the the above traceback for details on the specific errors on the above failures.
