### ISSUE TITLE
"manually graded task" cells cause metadata error

### ISSUE THREAD

**Issue by ibeatty** [jupyter/nbgrader#1303]
### Operating system

MacOS 10.15.2

### `nbgrader --version`

Python version 3.7.4 (default, Aug 13 2019, 15:17:50)
[Clang 4.0.1 (tags/RELEASE_401/final)]
nbgrader version 0.6.1

### `jupyterhub --version` (if used with JupyterHub)

Not using JupyterHub.

### `jupyter notebook --version` 

6.0.1

### Expected behavior

With the "create assignment" cell toolbar, I should be able to set a cell's type to "Manually graded task" and then have the notebook pass a Validation button test.

### Actual behavior

Whenever I set any cell in the notebook to "Manually graded task" -- even the only cell in the notebook, even if it has no content or just contains `pass` -- clicking the Validate button throws the following error:

```
Traceback (most recent call last):
  File "/Users/ibeatty/anaconda3/lib/python3.7/site-packages/nbgrader/server_extensions/validate_assignment/handlers.py", line 46, in validate_notebook
    result = validator.validate(fullpath)
  File "/Users/ibeatty/anaconda3/lib/python3.7/site-packages/nbgrader/validator.py", line 311, in validate
    nb = self._preprocess(nb)
  File "/Users/ibeatty/anaconda3/lib/python3.7/site-packages/nbgrader/validator.py", line 290, in _preprocess
    nb, resources = pp.preprocess(nb, resources)
  File "/Users/ibeatty/anaconda3/lib/python3.7/site-packages/nbgrader/preprocessors/checkcellmetadata.py", line 16, in preprocess
    raise ValidationError(msg)
jsonschema.exceptions.ValidationError: Notebook failed to validate; the nbgrader metadata may be corrupted.
```

### Steps to reproduce the behavior

1. Start jupyter notebook with `jupyter notebook` from the command line.
1. Create a new Python 3 notebook.
1. Turn on the Create Assignment toolbar from the View menu -> Cell Toolbar
1. Use the cell toolbar to change the automatically created, empty cell's type to Manually Graded Task.
1. Click the Validate button.

Boom.

**Comment by jdsonza** [comment]
I'm having this issue as well. Were you able to find any workarounds?

**Comment by ibeatty** [comment]
Yeah, sort of: I just don't set code cells to be manually graded tasks. Instead, I provide a markdown cell with instructions which carries the manually graded task metadata, and (if necessary) provide an empty code cell after it.

My guess is that the authors didn't envision any other use of that cell type, and therefore neither supported nor checked for code cells for it. The fact that it's an option at all is probably an oversight.

**Comment by AnnabellBrocker** [comment]
I have exactly the same problem.

Were you able to fix it?

Whenever I want to use a Manually gradded task Code cell, I receive the error described above.
As soon as I convert the code cell into a markdown cell, the validation is successful.

Also, what exactly is the difference between a "manually graded answer" and a "manually graded task" cell? Both have scoring possibilities

**Comment by perllaghu** [comment]
The two cells act differently.

See https://nbgrader.readthedocs.io/en/stable/user_guide/creating_and_grading_assignments.html
... and https://noteable.edina.ac.uk/nbguide/#section_ca - which may be slightly clearer

**Comment by AnnabellBrocker** [comment]
So it is intended that a "manually graded task" cell should not be a code cell?

And thanks for the second link, that was a little more understandable.
