### ISSUE TITLE
Formgrader 404 with JupyterHub on Azure machine

### ISSUE THREAD

**Issue by radusqrt** [jupyter/nbgrader#1321]
### Operating system
Linux version 5.0.0-1032-azure (buildd@lcy01-amd64-016) (gcc version 7.4.0 (Ubuntu 7.4.0-1ubuntu1~18.04.1)) #34-Ubuntu SMP Mon Feb 10 19:37:25 UTC 2020

### `nbgrader --version`
Python version 3.7.3 (default, Mar 27 2019, 22:11:17)
[GCC 7.3.0]
nbgrader version 0.7.0.dev

### `jupyterhub --version` (if used with JupyterHub)
1.0.0
ERROR:asyncio:Task exception was never retrieved
future: <Task finished coro=<JupyterHub.launch_instance_async() done, defined at /opt/tljh/user/lib/python3.7/site-packages/jupyterhub/app.py:2477> exception=SystemExit(0)>
Traceback (most recent call last):
  File "/opt/tljh/user/lib/python3.7/site-packages/jupyterhub/app.py", line 2492, in launch_instance
    loop.start()
  File "/opt/tljh/user/lib/python3.7/site-packages/tornado/platform/asyncio.py", line 149, in start
    self.asyncio_loop.run_forever()
  File "/opt/tljh/user/lib/python3.7/asyncio/base_events.py", line 539, in run_forever
    self._run_once()
  File "/opt/tljh/user/lib/python3.7/asyncio/base_events.py", line 1775, in _run_once
    handle._run()
  File "/opt/tljh/user/lib/python3.7/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/opt/tljh/user/lib/python3.7/site-packages/jupyterhub/app.py", line 2479, in launch_instance_async
    await self.initialize(argv)
  File "/opt/tljh/user/lib/python3.7/site-packages/jupyterhub/app.py", line 2085, in initialize
    super().initialize(*args, **kwargs)
  File "<decorator-gen-2>", line 2, in initialize
  File "/opt/tljh/user/lib/python3.7/site-packages/traitlets/config/application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "/opt/tljh/user/lib/python3.7/site-packages/traitlets/config/application.py", line 297, in initialize
    self.parse_command_line(argv)
  File "<decorator-gen-4>", line 2, in parse_command_line
  File "/opt/tljh/user/lib/python3.7/site-packages/traitlets/config/application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "/opt/tljh/user/lib/python3.7/site-packages/traitlets/config/application.py", line 532, in parse_command_line
    self.exit(0)
  File "/opt/tljh/user/lib/python3.7/site-packages/traitlets/config/application.py", line 654, in exit
    sys.exit(exit_status)
SystemExit: 0

### `jupyter notebook --version` 
6.0.3

### Expected behavior
Formgrader working normally.

### Actual behavior
Click on "Formgrader" ->

404 : Not Found
You are requesting a page that does not exist!

### Steps to reproduce the behavior
1. Deploy [TLJH](https://github.com/trallard/TLJH-azure-button) on an Azure machine.
2. Install nbgrader using the [instructions](https://nbgrader.readthedocs.io/en/latest/contributor_guide/installation_developer.html).
3. Click on Formgrader.

**Comment by llorencs** [comment]
Hello,
I am having the same issue. Followed the same steps. Checked how to link the configuration. And nothing. Also vm in Azure.

Thanks

**Comment by Xand1988** [comment]
Hello,

     I am experiencing exactly the same problem. However, my platform is google could, Kubernetes. If I install everything on the local Jupyter notebook, it is all functioning well.
