### ISSUE TITLE
FORMGRADER error

### ISSUE THREAD

**Issue by mboldin-temple** [jupyter/nbgrader#1337]
### Operating system
UBUNTU   Linux

### `nbgrader --version`
0.6.1
### `jupyter notebook --version` 
jupyter (1.0.0)
jupyter-client (6.1.3)
jupyter-console (6.1.0)
jupyter-core (4.6.3)

### Expected behavior
Use Formgrader menu item  in Jupyter
 
### Actual behavior

Browser screen:

nbgrader
Error
Manage Assignments
Gradebook
Manage Students
Sorry, the formgrader encountered an error. Please contact the administrator of the formgrader for further assistance.

Jupter --debug message
[W 09:14:01.345 NotebookApp] 404 GET /nbextensions/nbextensions_configurator/tree_tab/main.js?v=20200515091357 (127.0.0.1) 31.49ms referer=http://localhost:8888/tree
 
### Steps to reproduce the behavior
re-installed  jupyer and nbgrader
went through  nbgrader extension & serverextenstion enable steps
created nbgrader_config and quickstart course
made /srv/nbgrader/exchange  readable
ran jupter notebook both from base directory and also tried from course subdirectory

**Comment by mboldin-temple** [comment]
Here's another error message I found
[W 09:43:34.314 NotebookApp] Error loading server extension jupyter_nbextensions_configurator
    Traceback (most recent call last):
      File "/home/michael/.local/lib/python3.6/site-packages/notebook/notebookapp.py", line 1670, in init_server_extensions
        mod = importlib.import_module(modulename)
      File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
        return _bootstrap._gcd_import(name[level:], package, level)
      File "<frozen importlib._bootstrap>", line 994, in _gcd_import
      File "<frozen importlib._bootstrap>", line 971, in _find_and_load
      File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
    ModuleNotFoundError: No module named 'jupyter_nbextensions_configurator'

**Comment by mboldin-temple** [comment]
UPDATE: I can make everyting work if I both
(1)  invoke jupyter notebook in the course directory 
(2) add the cpourse firectory path as well

cd   -- course directory path --
 jupyter notebook  --course directory path -- 

This does not solve the problem
 ModuleNotFoundError: No module named 'jupyter_nbextensions_configurator'
but is a workaround

I suppose  jupyter_nbextensions_configurator was meant to avoid restating the directory

Also in the quickstart  config file, the comment here is misleading
# You only need this if you are running nbgrader on a shared
# server set up.
