### ISSUE TITLE
connection refused when notebook running on different server than jupyterhub

### ISSUE THREAD

**Issue by lickdragon** [jupyter/nbgrader#1351]
Hello all,
  I'm trying to run nbgrader in a setup where jupyterhub is on one server and the notebook is running on another server.
  Everything under the formgrader tab does not obviously not work.  Clicking into the Courses tab however results in this backtrace:

[E 2020-07-29 11:50:45.314 SingleUserNotebookApp handlers:179] Traceback (most recent call last):
      File "/usr/local/lib/python3.7/dist-packages/nbgrader/server_extensions/course_list/handlers.py", line 172, in get
        local_courses = yield self.check_for_local_formgrader(config)
      File "/usr/local/lib/python3.7/dist-packages/tornado/gen.py", line 735, in run
        value = future.result()
      File "/usr/local/lib/python3.7/dist-packages/tornado/gen.py", line 742, in run
        yielded = self.gen.throw(*exc_info)  # type: ignore
      File "/usr/local/lib/python3.7/dist-packages/nbgrader/server_extensions/course_list/handlers.py", line 63, in check_for_local_formgrader
        response = yield http_client.fetch(url, headers=header)
      File "/usr/local/lib/python3.7/dist-packages/tornado/gen.py", line 735, in run
        value = future.result()
    ConnectionRefusedError: [Errno 111] Connection refused

strace-ing the process shows that a connection to port 8000 on localhost is attempted.  This is the port that the configurable-http-proxy listens on the jupyterhub server, but nothing listens there on the notebook server.

I hacked up nbgrader/server_extensions/course_list/handlers.py to replace 127.0.0.1:8000 with the jupyterhub daemon's IP and port and there is no longer a backtrace, but instead "There are no available formgrader services."  When running 'jupyterhub notebook' on the jupyterhub server a formgrader service is shown.

Notebook server
```
[I 2020-07-29 12:24:47.184 SingleUserNotebookApp log:158] 200 GET /user/seys/api/terminals?_=1596043042278 (seys@127.0.0.1) 110.37ms
[I 2020-07-29 12:24:47.187 SingleUserNotebookApp log:158] 200 GET /user/seys/api/sessions?_=1596043042277 (seys@127.0.0.1) 1.81ms
[I 2020-07-29 12:24:47.370 SingleUserNotebookApp log:158] 200 GET /user/seys/api/contents?type=directory&_=1596043042279 (seys@127.0.0.1) 105.76ms
[W 2020-07-29 12:24:49.164 SingleUserNotebookApp handlers:71] Local formgrader does not seem to be running
[E 2020-07-29 12:24:49.186 SingleUserNotebookApp handlers:116] Formgrader not available at URL: http://128.104.160.38:8081/services/seys_example_course/formgrader
[I 2020-07-29 12:24:49.187 SingleUserNotebookApp log:158] 200 GET /user/seys/formgraders?_=1596043042280 (seys@127.0.0.1) 58.30ms
```
Jupyterhub server
```
Jul 29 12:24:49 jupyterhub1 jupyterhub[344806]: [I 2020-07-29 12:24:49.153 JupyterHub log:158] 30
2 GET /user/seys/formgrader/api/status -> /hub/user/seys/formgrader/api/status (@128.104.160.39) 2.67ms
Jul 29 12:24:49 jupyterhub1 jupyterhub[344806]: [E 2020-07-29 12:24:49.157 JupyterHub web:1792] Uncaught exception GET /hub/user/seys/formgrader/api/status (128.104.160.39)
Jul 29 12:24:49 jupyterhub1 jupyterhub[344806]:     HTTPServerRequest(protocol='http', host='128.104.160.38:8081', method='GET', uri='/hub/user/seys/formgrader/api/status', version='HTTP/1.1', remote_ip='128.104.160.39')
Jul 29 12:24:49 jupyterhub1 jupyterhub[344806]:     Traceback (most recent call last):
Jul 29 12:24:49 jupyterhub1 jupyterhub[344806]:       File "/usr/local/lib/python3.7/dist-packages/tornado/web.py", line 1703, in _execute
Jul 29 12:24:49 jupyterhub1 jupyterhub[344806]:         result = await result
Jul 29 12:24:49 jupyterhub1 jupyterhub[344806]:       File "/usr/local/lib/python3.7/dist-packages/jupyterhub/handlers/base.py", line 971, in get
Jul 29 12:24:49 jupyterhub1 jupyterhub[344806]:         if "api" in user_path.split("/") and not user.active:
Jul 29 12:24:49 jupyterhub1 jupyterhub[344806]:     AttributeError: 'NoneType' object has no attribute 'active'
Jul 29 12:24:49 jupyterhub1 jupyterhub[344806]:     
Jul 29 12:24:49 jupyterhub1 jupyterhub[344806]: [D 2020-07-29 12:24:49.164 JupyterHub base:890] No template for 500
Jul 29 12:24:49 jupyterhub1 jupyterhub[344806]: [E 2020-07-29 12:24:49.171 JupyterHub log:150] {
Jul 29 12:24:49 jupyterhub1 jupyterhub[344806]:       "Authorization": "token",
Jul 29 12:24:49 jupyterhub1 jupyterhub[344806]:       "Connection": "close",
Jul 29 12:24:49 jupyterhub1 jupyterhub[344806]:       "Accept-Encoding": "gzip",
Jul 29 12:24:49 jupyterhub1 jupyterhub[344806]:       "Host": "128.104.160.38:8081"
Jul 29 12:24:49 jupyterhub1 jupyterhub[344806]:     }
Jul 29 12:24:49 jupyterhub1 jupyterhub[344806]: [E 2020-07-29 12:24:49.171 JupyterHub log:158] 500 GET /hub/user/seys/formgrader/api/status (@128.104.160.39) 14.63ms
Jul 29 12:24:49 jupyterhub1 jupyterhub[344806]: [I 2020-07-29 12:24:49.185 JupyterHub log:158] 302 GET /services/seys_example_course/formgrader -> /hub/services/seys_example_course/formgrader (seys@128.104.160.39) 0.68ms
Jul 29 12:24:49 jupyterhub1 jupyterhub[344806]: [W 2020-07-29 12:24:49.194 JupyterHub log:158] 40
4 GET /hub/services/seys_example_course/formgrader (seys@128.104.160.39) 7.66ms
```

### Operating system
Debian Buster

### `nbgrader --version`
Python version 3.7.3 (default, Dec 20 2019, 18:57:59) 
[GCC 8.3.0]
nbgrader version 0.6.1

### `jupyterhub --version` (if used with JupyterHub)
0.9.6

### `jupyter notebook --version` 
6.0.3

**Comment by darkfishy** [comment]
Does the JupyterHub user for given token exist on that server? Because that's what JH is complaining about, that it didn't find a user.

**Comment by lickdragon** [comment]
[tThe](url) first error is jupyterhub trying to connect to localhost rather than the jupyterhub server.

After edit the source code to connect to the jupyterhub server instead of localhost, this is where the 404 comes in.  Probably I should not have confused this issue by mentioning the hack.

But to answer your question, yes that user exists and is the one I'm using to access the jupyterhub.  My experience the last couple of days is that I should not be mixing packages from PyPi which have very different release dates.  Possibly all that happened is that the URL is mismatching between new nbgrader and old jupyterhub.
