### ISSUE TITLE
Autograding fails if Autograding Test cell has maximum number of points 0

### ISSUE THREAD

**Issue by jjur** [jupyter/nbgrader#1353]
### `nbgrader --version`
nbgrader version 0.6.1
### `jupyter notebook --version` 
6.0.3
### Expected behavior

1. Create cell with Autograding Test
2. Assign maximum of 0 points for this test
3. Generate student´s version and fill with code that passes test
4. Autograding finishes and gives 0 points.

### Actual behavior

1. Create cell with Autograding Test
2. Assign maximum of 0 points for this test
3. Generate student´s version and fill with code that passes test
4. Autograding returns error for this submission.

### Log Output
.....
[INFO] Executing notebook with kernel: python3
[ERROR] There was an error processing assignment: /home/jovyan/submitted/student/notebook_demo
[ERROR] Traceback (most recent call last):
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbgrader/converters/base.py", line 336, in convert_notebooks
        self.convert_single_notebook(notebook_filename)
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbgrader/converters/autograde.py", line 195, in convert_single_notebook
        super(Autograde, self).convert_single_notebook(notebook_filename)
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbgrader/converters/base.py", line 292, in convert_single_notebook
        output, resources = self.exporter.from_filename(notebook_filename, resources=resources)
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbconvert/exporters/exporter.py", line 179, in from_filename
        return self.from_file(f, resources=resources, **kw)
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbconvert/exporters/exporter.py", line 197, in from_file
        return self.from_notebook_node(nbformat.read(file_stream, as_version=4), resources=resources, **kw)
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbconvert/exporters/notebook.py", line 32, in from_notebook_node
        nb_copy, resources = super(NotebookExporter, self).from_notebook_node(nb, resources, **kw)
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbconvert/exporters/exporter.py", line 139, in from_notebook_node
        nb_copy, resources = self._preprocess(nb_copy, resources)
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbconvert/exporters/exporter.py", line 316, in _preprocess
        nbc, resc = preprocessor(nbc, resc)
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbconvert/preprocessors/base.py", line 47, in __call__
        return self.preprocess(nb, resources)
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbgrader/preprocessors/saveautogrades.py", line 21, in preprocess
        nb, resources = super(SaveAutoGrades, self).preprocess(nb, resources)
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbconvert/preprocessors/base.py", line 69, in preprocess
        nb.cells[index], resources = self.preprocess_cell(cell, resources, index)
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbgrader/preprocessors/saveautogrades.py", line 70, in preprocess_cell
        self._add_score(cell, resources)
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbgrader/preprocessors/saveautogrades.py", line 42, in _add_score
        auto_score, _ = utils.determine_grade(cell, self.log)
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbgrader/utils.py", line 119, in determine_grade
        partial_grade = get_partial_grade(output, max_points, log)
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbgrader/utils.py", line 86, in get_partial_grade
        raise ValueError("partial credit cannot be greater than maximum points for cell")
    ValueError: partial credit cannot be greater than maximum points for cell
    
[WARNING] Removing failed assignment: /home/jovyan/autograded/student/notebook_demo
[ERROR] There was an error processing assignment "notebook_demo" for student "student"
[ERROR] Please see the the above traceback for details on the specific errors on the above failures.

**Comment by jjur** [comment]
Ok problem was somewhere else. 
Solved

**Comment by vpozdnyakov** [comment]
what was the solution? the same problem, I don't understand meaning of "partial credit cannot be greater than maximum points for cell". what is a credit?
