### ISSUE TITLE
'Connection refused' on second network interface

### ISSUE THREAD

**Issue by K1LLUM1N471** [jupyter/nbgrader#1366]
# Operating system
Ubuntu 18.04.4 LTS

### `nbgrader --version`
Python version 3.7.7 (default, Mar 26 2020, 15:48:22)
[GCC 7.3.0]
nbgrader version 0.6.1

### `jupyterhub --version` (if used with JupyterHub)
1.0.0
ERROR:asyncio:Task exception was never retrieved
future: <Task finished coro=<JupyterHub.launch_instance_async() done, defined at /opt/tljh/user/lib/python3.7/site-packages/jupyterhub/app.py:2477> exception=SystemExit(0)>
Traceback (most recent call last):
  File "/opt/tljh/user/lib/python3.7/site-packages/jupyterhub/app.py", line 2492, in launch_instance
    loop.start()
  File "/opt/tljh/user/lib/python3.7/site-packages/tornado/platform/asyncio.py", line 149, in start
    self.asyncio_loop.run_forever()
  File "/opt/tljh/user/lib/python3.7/asyncio/base_events.py", line 541, in run_forever
    self._run_once()
  File "/opt/tljh/user/lib/python3.7/asyncio/base_events.py", line 1786, in _run_once
    handle._run()
  File "/opt/tljh/user/lib/python3.7/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/opt/tljh/user/lib/python3.7/site-packages/jupyterhub/app.py", line 2479, in launch_instance_async
    await self.initialize(argv)
  File "/opt/tljh/user/lib/python3.7/site-packages/jupyterhub/app.py", line 2085, in initialize
    super().initialize(*args, **kwargs)
  File "<decorator-gen-2>", line 2, in initialize
  File "/opt/tljh/user/lib/python3.7/site-packages/traitlets/config/application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "/opt/tljh/user/lib/python3.7/site-packages/traitlets/config/application.py", line 297, in initialize
    self.parse_command_line(argv)
  File "<decorator-gen-4>", line 2, in parse_command_line
  File "/opt/tljh/user/lib/python3.7/site-packages/traitlets/config/application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "/opt/tljh/user/lib/python3.7/site-packages/traitlets/config/application.py", line 532, in parse_command_line
    self.exit(0)
  File "/opt/tljh/user/lib/python3.7/site-packages/traitlets/config/application.py", line 654, in exit
    sys.exit(exit_status)
SystemExit: 0

### `jupyter notebook --version` 
6.0.3

### Expected behavior
see Actual behavior

### Actual behavior
Our machine has two network interfaces.
When I go from the local side (http://10.x.x.x) on 'Courses' everything is working fine, but when I got from the WAN side (http://193.x.x.x) on 'Courses' I get the error message:
Traceback (most recent call last): File "/opt/tljh/user/lib/python3.7/site-packages/nbgrader/server_extensions/course_list/handlers.py", line 172, in get local_courses = yield self.check_for_local_formgrader(config) File "/opt/tljh/user/lib/python3.7/site-packages/tornado/gen.py", line 735, in run value = future.result() File "/opt/tljh/user/lib/python3.7/site-packages/tornado/gen.py", line 742, in run yielded = self.gen.throw(*exc_info) # type: ignore File "/opt/tljh/user/lib/python3.7/site-packages/nbgrader/server_extensions/course_list/handlers.py", line 63, in check_for_local_formgrader response = yield http_client.fetch(url, headers=header) File "/opt/tljh/user/lib/python3.7/site-packages/tornado/gen.py", line 735, in run value = future.result() ConnectionRefusedError: [Errno 111] Connection refused 

cat /etc/jupyterhub/jupyterhub_config.py | egrep -v "(^#.*|^$)"
c.JupyterHub.ip = '0.0.0.0'
c.JupyterHub.port = 80

Do I have to configure something more?

### Steps to reproduce the behavior
see Actual behavior

Kind regards,
K1LLUM1N471

**Comment by divingeek** [comment]
Hi,

Same issue, I don't manage to access courses from JupyterHub Web UI (TLJH installed).


### Operating system
Linux jupyter 5.4.44-2-pve #1 SMP PVE 5.4.44-2 (Wed, 01 Jul 2020 16:37:57 +0200) x86_64 x86_64 x86_64 GNU/Linux

(inside proxmox LXC)

### `nbgrader --version`
```

jupyter-XXXX@jupyter:~$ nbgrader --version
Python version 3.8.5 (default, Jul 28 2020, 12:59:40) 
[GCC 9.3.0]
nbgrader version 0.6.1
```

### `jupyterhub --version` (if used with JupyterHub)
1.2.1
not sure if this is relevant, i'm using **TLJH** in fact.

### `jupyter notebook --version` 
6.1.4

```
[SingleUserNotebookApp | ERROR] Traceback (most recent call last):
      File "/opt/tljh/user/lib/python3.7/site-packages/nbgrader/server_extensions/course_list/handlers.py", line 172, in get
        local_courses = yield self.check_for_local_formgrader(config)
      File "/opt/tljh/user/lib/python3.7/site-packages/tornado/gen.py", line 1133, in run
        value = future.result()
      File "/opt/tljh/user/lib/python3.7/site-packages/tornado/gen.py", line 1141, in run
        yielded = self.gen.throw(*exc_info)
      File "/opt/tljh/user/lib/python3.7/site-packages/nbgrader/server_extensions/course_list/handlers.py", line 63, in check_for_local_formgrader
        response = yield http_client.fetch(url, headers=header)
      File "/opt/tljh/user/lib/python3.7/site-packages/tornado/gen.py", line 1133, in run
        value = future.result()
    ConnectionRefusedError: [Errno 111] Connection refused
    
[SingleUserNotebookApp | INFO] 200 GET /user/XXXX/formgraders?_=1604748246611 (XXXX@**192.168.1.254**) 17.05ms

```

Is there config to add in nbgrader_config.py ?
