### ISSUE TITLE
NoSuchKernel when trying to validate notebook in an anaconda environment

### ISSUE THREAD

**Issue by mmagnuski** [jupyter/nbgrader#1375]
Trying to validate a source notebook in an anaconda environment produces a `jupyter_client.kernelspec.NoSuchKernel` error.

#### Operating system
Windows 10 build 18363

#### `nbgrader --version`
```
Python version 3.7.3 (default, Apr 24 2019, 15:29:51) [MSC v.1915 64 bit (AMD64)]
nbgrader version 0.6.1
```

#### `jupyter notebook --version` 
```
6.1.1
```

### Expected behavior
The notebook is validated.

### Actual behavior
I get `jupyter_client.kernelspec.NoSuchKernel` error:
```python-traceback
Traceback (most recent call last):
  File "C:\Users\mmagn\Continuum\anaconda3\envs\mne\lib\site-packages\nbgrader\server_extensions\validate_assignment\handlers.py", line 46, in validate_notebook
    result = validator.validate(fullpath)
  File "C:\Users\mmagn\Continuum\anaconda3\envs\mne\lib\site-packages\nbgrader\validator.py", line 311, in validate
    nb = self._preprocess(nb)
  File "C:\Users\mmagn\Continuum\anaconda3\envs\mne\lib\site-packages\nbgrader\validator.py", line 290, in _preprocess
    nb, resources = pp.preprocess(nb, resources)
  File "C:\Users\mmagn\Continuum\anaconda3\envs\mne\lib\site-packages\nbgrader\preprocessors\execute.py", line 41, in preprocess
    output = super(Execute, self).preprocess(nb, resources)
  File "C:\Users\mmagn\Continuum\anaconda3\envs\mne\lib\site-packages\nbconvert\preprocessors\execute.py", line 79, in preprocess
    self.execute()
  File "C:\Users\mmagn\Continuum\anaconda3\envs\mne\lib\site-packages\nbclient\util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "C:\Users\mmagn\Continuum\anaconda3\envs\mne\lib\site-packages\nbclient\util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "C:\Users\mmagn\Continuum\anaconda3\envs\mne\lib\site-packages\nest_asyncio.py", line 95, in run_until_complete
    return f.result()
  File "C:\Users\mmagn\Continuum\anaconda3\envs\mne\lib\asyncio\futures.py", line 178, in result
    raise self._exception
  File "C:\Users\mmagn\Continuum\anaconda3\envs\mne\lib\asyncio\tasks.py", line 223, in __step
    result = coro.send(None)
  File "C:\Users\mmagn\Continuum\anaconda3\envs\mne\lib\site-packages\nbclient\client.py", line 519, in async_execute
    async with self.async_setup_kernel(**kwargs):
  File "C:\Users\mmagn\Continuum\anaconda3\envs\mne\lib\site-packages\async_generator\_util.py", line 34, in __aenter__
    return await self._agen.asend(None)
  File "C:\Users\mmagn\Continuum\anaconda3\envs\mne\lib\site-packages\nbclient\client.py", line 477, in async_setup_kernel
    await self.async_start_new_kernel(**kwargs)
  File "C:\Users\mmagn\Continuum\anaconda3\envs\mne\lib\site-packages\nbclient\client.py", line 389, in async_start_new_kernel
    await ensure_async(self.km.start_kernel(extra_arguments=self.extra_arguments, **kwargs))
  File "C:\Users\mmagn\Continuum\anaconda3\envs\mne\lib\site-packages\nbclient\util.py", line 85, in ensure_async
    result = await obj
  File "C:\Users\mmagn\Continuum\anaconda3\envs\mne\lib\site-packages\jupyter_client\manager.py", line 569, in start_kernel
    kernel_cmd, kw = self.pre_start_kernel(**kw)
  File "C:\Users\mmagn\Continuum\anaconda3\envs\mne\lib\site-packages\jupyter_client\manager.py", line 257, in pre_start_kernel
    kernel_cmd = self.format_kernel_cmd(extra_arguments=extra_arguments)
  File "C:\Users\mmagn\Continuum\anaconda3\envs\mne\lib\site-packages\jupyter_client\manager.py", line 181, in format_kernel_cmd
    cmd = self.kernel_spec.argv + extra_arguments
  File "C:\Users\mmagn\Continuum\anaconda3\envs\mne\lib\site-packages\jupyter_client\manager.py", line 87, in kernel_spec
    self._kernel_spec = self.kernel_spec_manager.get_kernel_spec(self.kernel_name)
  File "C:\Users\mmagn\Continuum\anaconda3\envs\mne\lib\site-packages\jupyter_client\kernelspec.py", line 235, in get_kernel_spec
    raise NoSuchKernel(kernel_name)
jupyter_client.kernelspec.NoSuchKernel: No such kernel named conda-env-mne-py
```

### Steps to reproduce the behavior
* create a conda environement with jupyter notebook installed
* activate that environment
* install nbgrader to that env
* create a homework notebook and try to validate it

### Likely cause and proposed solution
This is likely caused by #714 (preserve kernel spec PR) which does not takes into account how kernels are referred to in notebook kernelspec metadata in conda environements.

When using conda environmants the notebook kernelspec metadata contains information about the conda environment  and its kernel.  In my case the kernelspec name is `conda-env-mne-py` - the `conda-env-mne` part is the conda environment name and `py` refers to the python kernel. However if I list jupyter kernels fot this conda environment I get this:
```
C:\prog\cmder
λ conda activate mne

C:\prog\cmder
(mne) λ jupyter kernelspec list
[ListKernelSpecs] WARNING | Config option `kernel_spec_manager_class` not recognized by `ListKernelSpecs`. Available kernels:
  python3    C:\Users\mmagn\Continuum\anaconda3\envs\mne\share\jupyter\kernels\python3
```
so the only available kernel in this environment is `python3`, there is no `conda-env-mne-py` kernel.

I think the easiest fix would be to:
* check if `conda-env` is in kernelspec name string
* if so, check if current conda env (`CONDA_DEFAULT_ENV` environment variable) is the one referred to in the kernelspec.  
  - If so -> infer kernel name based on language (`'language'` in `'kernelspec'` and version number (from `language_info`)
  - If not -> throw error asking user to activate correct conda env.

I'll try if this solves my issues locally soon, and then I can submit a PR if you are interested.

**Comment by mmann1123** [comment]
I am suddenly getting the same issue after months of successful use. The correct env is activated so not sure what is happening.  Any resolution to this?

**Comment by mmann1123** [comment]
Figured out a solution:
In nbgrader_config.py set the default kernel to one of the named kernels in `jupyter kernelspec list` (very end of the kernel path on the right)

``` python 
## Name of kernel to use to execute the cells. If not set, use the kernel_spec
#  embedded in the notebook.
c.ExecutePreprocessor.kernel_name = 'python3'

```
