### ISSUE TITLE
Autograde fails in notebook conversion

### ISSUE THREAD

**Issue by bobthefairycat** [jupyter/nbgrader#1377]
### Operating system
Ubuntu 18.04.5 LTS (Bionic Beaver)
### `nbgrader --version`
nbgrader version 0.6.1
### `jupyterhub --version` (if used with JupyterHub)
1.1.0
### `jupyter notebook --version` 
6.0.3
### Expected behavior
Grade student assignments.
### Actual behavior
```
[AutogradeApp | INFO] Copying [redacted]
[AutogradeApp | ERROR] There was an error processing assignment: [redacted]
[AutogradeApp | ERROR] Traceback (most recent call last):
      File "/s/appspace/anaconda-nbgrader/lib/python3.8/site-packages/nbgrader/converters/base.py", line 332, in convert_notebooks
        self.init_assignment(gd['assignment_id'], gd['student_id'])
      File "/s/appspace/anaconda-nbgrader/lib/python3.8/site-packages/nbgrader/converters/autograde.py", line 76, in init_assignment
        if s['id'] == student_id:
    TypeError: list indices must be integers or slices, not str

[AutogradeApp | WARNING] Removing failed assignment: [redacted]
[AutogradeApp | ERROR] There was an error processing assignment 'jn-1' for student [redacted]
[AutogradeApp | ERROR] Please see the the above traceback for details on the specific errors on the above failures.
```
### Steps to reproduce the behavior
Create assignment using "Create Assignment" in web interface. Use command line to run:

`nbgrader generate jn-1`
`nbgrader assign jn-1`

students run
`nbgrader fetch jn-1`
`nbgrader submit jn-1`
... and once the deadline has passed...
`nbgrader collect jn-1`
`nbgrader autograde --student="[Redacted]" --debug jn-1`

Student notebooks run in the web interface. Cannot access web interface of formgrader due to 404 error, but it is enabled.

I am aware I am using deprecated commands, but I would think this should not cause things to die like this... 

Sample student submission (test student):
```
{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "Before you turn this problem in, make sure everything runs as expected. First, **restart the kernel** (in the menubar, select Kernel$\\rightarrow$Restart) and then **run all cells** (in the menubar, select Cell$\\rightarrow$Run All).\n",
    "\n",
    "Make sure you fill in any place that says `YOUR CODE HERE` or \"YOUR ANSWER HERE\", as well as your name and collaborators below:"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "NAME = \"\"\n",
    "COLLABORATORS = \"\""
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "---"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {
    "deletable": false,
    "editable": false,
    "nbgrader": {
     "cell_type": "markdown",
     "checksum": "8a7dbabf564116c9426586162d926fdd",
     "grade": false,
     "grade_id": "cell-c875822ef3bcac91",
     "locked": true,
     "schema_version": 3,
     "solution": false,
     "task": false
    }
   },
   "source": [
    "The following is an exercise to familiarize yourself with using variable assignment and arithmetic expressions."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {
    "deletable": false,
    "nbgrader": {
     "cell_type": "code",
     "checksum": "3775484de87dcc826929debca5e57bb6",
     "grade": false,
     "grade_id": "cell-f2b907b2ad845b50",
     "locked": false,
     "schema_version": 3,
     "solution": true,
     "task": false
    }
   },
   "outputs": [],
   "source": [
    "# monthly expenses\n",
    "rent = 1000.0\n",
    "food = 200.0\n",
    "\n",
    "# create a variable, total_monthly_expenses, which is the sum of rent and food\n",
    "# refer to the variables in your expression\n",
    "# your code here\n",
    "\n",
    "# monthly income\n",
    "part_time_job = 400.0\n",
    "scholarship = 1000.0\n",
    "osap = 500.0\n",
    "\n",
    "# create a variable, total_monthly_income, which is the sum of part_time_job, scholarship, and osap\n",
    "# your code here\n",
    "\n",
    "# create a variable, savings, which is the result of total_monthly_expenses subtracted from total_monthly_income\n",
    "# your code here"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {
    "deletable": false,
    "editable": false,
    "nbgrader": {
     "cell_type": "code",
     "checksum": "7d7e9727692731bd5e9547334a38f6cc",
     "grade": true,
     "grade_id": "cell-50d8df44b84102b5",
     "locked": true,
     "points": 1,
     "schema_version": 3,
     "solution": false,
     "task": false
    }
   },
   "outputs": [],
   "source": [
    "from nose.tools import assert_equal\n",
    "assert_equal(total_monthly_expenses, 1200.0)\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {
    "deletable": false,
    "editable": false,
    "nbgrader": {
     "cell_type": "code",
     "checksum": "0a51f7546784e21322ffe002de4a8eb3",
     "grade": true,
     "grade_id": "cell-cfae8164732cd6eb",
     "locked": true,
     "points": 1,
     "schema_version": 3,
     "solution": false,
     "task": false
    }
   },
   "outputs": [],
   "source": [
    "from nose.tools import assert_equal\n",
    "assert_equal(total_monthly_income, 1900.0)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {
    "deletable": false,
    "editable": false,
    "nbgrader": {
     "cell_type": "code",
     "checksum": "3e762b66db12f2045290f28b95f854f6",
     "grade": true,
     "grade_id": "cell-b4a7862d0743742e",
     "locked": true,
     "points": 1,
     "schema_version": 3,
     "solution": false,
     "task": false
    }
   },
   "outputs": [],
   "source": [
    "from nose.tools import assert_equal\n",
    "assert_equal(savings, 700.0)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {
    "deletable": false,
    "editable": false,
    "nbgrader": {
     "cell_type": "markdown",
     "checksum": "d4fa7de67f6ff547e84bcb5eafb7e7d1",
     "grade": false,
     "grade_id": "cell-10faf4556c35bc96",
     "locked": true,
     "schema_version": 3,
     "solution": false,
     "task": false
    }
   },
   "source": [
    "The following is an exercise on resolving errors in Python code."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {
    "deletable": false,
    "nbgrader": {
     "cell_type": "code",
     "checksum": "cc797097171caaf1f06ad63c49ca7fd0",
     "grade": false,
     "grade_id": "cell-4e26fba1310279c6",
     "locked": false,
     "schema_version": 3,
     "solution": true,
     "task": false
    }
   },
   "outputs": [],
   "source": [
    "# your code here"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {
    "deletable": false,
    "editable": false,
    "nbgrader": {
     "cell_type": "code",
     "checksum": "fce1dc7857ce0bd5544bdfbf474e02b3",
     "grade": true,
     "grade_id": "cell-2fa37c7aaf02e4c2",
     "locked": true,
     "points": 0,
     "schema_version": 3,
     "solution": false,
     "task": false
    }
   },
   "outputs": [],
   "source": [
    "from nose.tools import assert_equal\n",
    "assert_equal(x, 2**0.5)\n",
    "assert_equal(y, (2**0.5)**2)"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.8.3"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}
```

**Comment by bobthefairycat** [comment]
Resolved! My mistake was trying to load, from a csv file, the student list in the `nbgrader_config.py` file. I removed the students from the database and loaded them using `nbgrader db student import`. For future reference, is there an easy way to flush the student database (dangerous operation but sometimes necessary)?

**Comment by jhamrick** [comment]
You can use `nbgrader db student remove`, but this only does one student at a time. It is not too complicated to use a script to loop over all the students in the database and remove them though, e.g.:

```
from nbgrader.api import Gradebook

gradebook = "sqlite:///gradebook.db"
course_id = "course101"
authenticator = None
force = True

with Gradebook(gradebook, course_id, authenticator) as gb:
    for student in gb.students:
        if len(student.submissions) > 0:
            if force:
                print("Removing associated grades")
            else:
                print(f"!!! There are grades in the database for student '{student.id}'.")
                print("!!! Removing this student will also remove these grades.")
                print("!!! If you are SURE this is what you want to do, rerun with force=True")
                continue

        print(f"Removing student with ID '{student.id}'")
        gb.remove_student(student.id)
```
