### ISSUE TITLE
Student cannot see Assignment

### ISSUE THREAD

**Issue by LeonHoeppner** [jupyter/nbgrader#1378]
### Operating system
Ubuntu 18.02
### `nbgrader --version`
Python version 3.7.3 (default, Mar 27 2019, 22:11:17)
[GCC 7.3.0]
nbgrader version 0.6.1
### `jupyterhub --version` (if used with JupyterHub)
1.0.0
ERROR:asyncio:Task exception was never retrieved
future: <Task finished coro=<JupyterHub.launch_instance_async() done, defined at /opt/tljh/user/lib/python3.7/site-packages/jupyterhub/app.py:2477> exception=SystemExit(0)>
Traceback (most recent call last):
  File "/opt/tljh/user/lib/python3.7/site-packages/jupyterhub/app.py", line 2492,in launch_instance    loop.start()
  File "/opt/tljh/user/lib/python3.7/site-packages/tornado/platform/asyncio.py", line 149, in start    self.asyncio_loop.run_forever()
  File "/opt/tljh/user/lib/python3.7/asyncio/base_events.py", line 539, in run_forever    self._run_once()
  File "/opt/tljh/user/lib/python3.7/asyncio/base_events.py", line 1775, in _run_once    handle._run()
  File "/opt/tljh/user/lib/python3.7/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)  File "/opt/tljh/user/lib/python3.7/site-packages/jupyterhub/app.py", line 2479,in launch_instance_async
    await self.initialize(argv)
  File "/opt/tljh/user/lib/python3.7/site-packages/jupyterhub/app.py", line 2085,in initialize    super().initialize(*args, **kwargs)
  File "/opt/tljh/user/lib/python3.7/site-packages/traitlets/config/application.py", line 86, in inner    return method(app, *args, **kwargs)
  File "/opt/tljh/user/lib/python3.7/site-packages/traitlets/config/application.py", line 326, in initialize    self.parse_command_line(argv)
  File "/opt/tljh/user/lib/python3.7/site-packages/traitlets/config/application.py", line 86, in inner    return method(app, *args, **kwargs)
  File "/opt/tljh/user/lib/python3.7/site-packages/traitlets/config/application.py", line 693, in parse_command_line    self.exit(0)
  File "/opt/tljh/user/lib/python3.7/site-packages/traitlets/config/application.py", line 827, in exit    sys.exit(exit_status)
SystemExit: 0
### `jupyter notebook --version` 
6.1.4
### Expected behavior
I want to create users in the Formgrader, so that the students can log in into the Jupyterhub and see their assignments.
### Actual behavior
I don't know if the error above has something to do with my problem: I wanted to release the student version of a notebook which was succesfull. But i actually don't know how to access it as a student. When i add users via the nbrader database or through the formgrader, they appear on the formgrader, but not on the Jupyterhub Admin Interface. So, I can't login as the student. However, I don't know how to make a connection between the Jupyterhub user which are needed to login into the Jupyterhub, and the users i create in the formgrader.
### Steps to reproduce the behavior
- Manually create a directory with the Course Name
- Place a global nbgrader_config.py in /etc/jupyter with Exchange setup
- Place a nbgrader_config.py in /home/user/.jupyter with information about course directory root
- Place a nbgrader_config.py in the courses directory with information about course directory root and course ID
- Place a Jupyterhub_config.py in /etc/jupyterhub with information about user

Detailed content of the files taken from: https://github.com/jupyter/nbgrader/tree/7f916faaa6fdad35113c0b80e818ebb87f8cf376/demos/demo_multiple_classes

**Comment by guillermouberomero** [comment]
Hi! I had the same problem and i solved it by putting as the Student ID (in Formgrader, manage students), the JupyterHub username.

I hope it helps you! :)
