### ISSUE TITLE
manually grader raises error

### ISSUE THREAD

**Issue by donatog** [jupyter/nbgrader#1404]

**Comment by wmwolf** [comment]
I'm seeing something similar.

- `nbgrader --version`: 0.7.0.dev; specifically `5a81fd5` (to work with [ngshare](https://ngshare.readthedocs.io/en/latest/))
- `jupyterhub --version` 1.3.0
- `jupyter notebook --version`: 6.1.6

This is running z2jh on a kubernetes cluster (hence using ngshare for the exchange). I was able to release an assignment, have a student download it, complete it, and submit it. Then I fetched it and auto-graded it from within formgrader, but attempting to open a particular submission for manual grading gives the error described by @donatog.

Here is the log output associated with the error:

```
[SingleUserNotebookApp | ERROR] Uncaught exception GET /user/teacher/formgrader/submissions/810e2edd7a394066a15d9e0ee45db8ff/ (10.128.0.8)
    HTTPServerRequest(protocol='https', host='MYDOMAIN.com', method='GET', uri='/user/teacher/formgrader/submissions/810e2edd7a394066a15d9e0ee45db8ff/', version='HTTP/1.1', remote_ip='10.128.0.8')
    Traceback (most recent call last):
      File "/opt/conda/lib/python3.8/site-packages/tornado/web.py", line 1702, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/opt/conda/lib/python3.8/site-packages/tornado/web.py", line 3173, in wrapper
        return method(self, *args, **kwargs)
      File "/opt/conda/lib/python3.8/site-packages/nbgrader/server_extensions/formgrader/base.py", line 108, in wrapper
        return f(self, *args, **kwargs)
      File "/opt/conda/lib/python3.8/site-packages/nbgrader/server_extensions/formgrader/base.py", line 117, in wrapper
        return f(self, *args, **kwargs)
      File "/opt/conda/lib/python3.8/site-packages/nbgrader/server_extensions/formgrader/handlers.py", line 125, in get
        html, _ = self.exporter.from_filename(filename, resources=resources)
      File "/opt/conda/lib/python3.8/site-packages/nbconvert/exporters/exporter.py", line 181, in from_filename
        return self.from_file(f, resources=resources, **kw)
      File "/opt/conda/lib/python3.8/site-packages/nbconvert/exporters/exporter.py", line 199, in from_file
        return self.from_notebook_node(nbformat.read(file_stream, as_version=4), resources=resources, **kw)
      File "/opt/conda/lib/python3.8/site-packages/nbconvert/exporters/html.py", line 119, in from_notebook_node
        return super().from_notebook_node(nb, resources, **kw)
      File "/opt/conda/lib/python3.8/site-packages/nbconvert/exporters/templateexporter.py", line 384, in from_notebook_node
        output = self.template.render(nb=nb_copy, resources=resources)
      File "/opt/conda/lib/python3.8/site-packages/nbconvert/exporters/templateexporter.py", line 148, in template
        self._template_cached = self._load_template()
      File "/opt/conda/lib/python3.8/site-packages/nbconvert/exporters/templateexporter.py", line 355, in _load_template
        return self.environment.get_template(template_file)
      File "/opt/conda/lib/python3.8/site-packages/jinja2/environment.py", line 883, in get_template
        return self._load_template(name, self.make_globals(globals))
      File "/opt/conda/lib/python3.8/site-packages/jinja2/environment.py", line 857, in _load_template
        template = self.loader.load(self, name, globals)
      File "/opt/conda/lib/python3.8/site-packages/jinja2/loaders.py", line 429, in load
        raise TemplateNotFound(name)
    jinja2.exceptions.TemplateNotFound: formgrade
[SingleUserNotebookApp | ERROR] {
      "X-Scheme": "https",
      "X-Real-Ip": "10.128.0.8",
      "X-Forwarded-Server": "autohttps-7fcf79f997-dnchd",
      "X-Forwarded-Proto": "https,http",
      "X-Forwarded-Port": "443,80",
      "X-Forwarded-Host": "MYDOMAIN.com",
      "X-Forwarded-For": "10.128.0.8,::ffff:10.0.5.85",
      "Referer": "https://MYDOMAIN.com/user/teacher/formgrader/manage_students/student/lab1",
      "Cookie": "jupyterhub-user-teacher=[secret]; jupyterhub-session-id=[secret]; _xsrf=[secret]",
      "Accept-Language": "en-us",
      "Accept-Encoding": "gzip, deflate, br",
      "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
      "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0.2 Safari/605.1.15",
      "Host": "MYDOMAIN.com",
      "Connection": "close"
    }
[SingleUserNotebookApp | ERROR] 500 GET /user/teacher/formgrader/submissions/810e2edd7a394066a15d9e0ee45db8ff/ (teacher@10.128.0.8) 316.50ms
```

I get 200's for other requests to the formgrader resource, but when trying to access a particular submission for manual grading, I get this problem. I'm not really sure what the missing template is telling me.

**Comment by wmwolf** [comment]
My apologies for not looking deeper in the issues archive. It seems that downgrading `nbconvert` in my dockerfile to 5.6.1 solves the issue, as suggested in #1391.

@donatog, have you given downgrading `nbconvert` a try? In any case, this issue should probably be closed in favor of #1391, unless there is some unique feature here.

**Comment by jhamrick** [comment]
Closing as duplicate.

**Comment by donatog** [comment]
Yesss, I did

Il mar 19 gen 2021, 01:55 Bill Wolf ***@***.***> ha scritto:
