### ISSUE TITLE
Manually collected submissions are skipped by autograder 

### ISSUE THREAD

**Issue by andrewdnolan** [jupyter/nbgrader#1409]
### Operating system
I'm working locally on OSX. Student submissions occur through our learning magament system (LMS), therefore JupyterHub is not used for this course. 

### `nbgrader --version`
```
Python version 3.7.9 | packaged by conda-forge | (default, Dec  9 2020, 20:58:55)
[Clang 11.0.0 ]
nbgrader version 0.6.1
```
### `jupyter notebook --version`   
```
6.1.6
```
### Expected behavior
I'm attempting to autograde an individual students assignment from the formgrader. I've downloaded the submitted assignments from our LMS and distributed them into their respective folders (eg. `submitted/STUDENT_ID/01_intro2python/` where `STUDENT_ID` is the respecitve students IDs and the assignment name is `01_intro2python`. 

### Actual behavior

When clicking the autograde button from the formgrader for the first student (or any) submission I receive the error:  
```
[INFO] Creating/updating student with ID 'Alexandre': {}
[INFO] Overwriting files with master versions from the source directory
[INFO] Copying /Users/andrewnolan/sfuvault/Department/TAing/EASC_305_SPRING_2020/EASC-305-nbgrader/source/./01_intro2python/well_data.txt -> /Users/andrewnolan/sfuvault/Department/TAing/EASC_305_SPRING_2020/EASC-305-nbgrader/autograded/Alexandre/01_intro2python/well_data.txt
[INFO] Copying /Users/andrewnolan/sfuvault/Department/TAing/EASC_305_SPRING_2020/EASC-305-nbgrader/source/./01_intro2python/ammonoids.mat -> /Users/andrewnolan/sfuvault/Department/TAing/EASC_305_SPRING_2020/EASC-305-nbgrader/autograded/Alexandre/01_intro2python/ammonoids.mat
[WARNING] Skipping unknown notebook: /Users/andrewnolan/sfuvault/Department/TAing/EASC_305_SPRING_2020/EASC-305-nbgrader/submitted/Alexandre/01_intro2python/nottalexandrehill_156676_14919471_01_intro2python_Alex_Nott.ipynb
[ERROR] No notebooks found, did you forget to run 'nbgrader generate_assignment'?
[ERROR] There was an error processing assignment: /Users/andrewnolan/sfuvault/Department/TAing/EASC_305_SPRING_2020/EASC-305-nbgrader/submitted/Alexandre/01_intro2python
[ERROR] Traceback (most recent call last):
      File "/Users/andrewnolan/anaconda3/envs/EASC305/lib/python3.7/site-packages/nbgrader/converters/base.py", line 332, in convert_notebooks
        self.init_assignment(gd['assignment_id'], gd['student_id'])
      File "/Users/andrewnolan/anaconda3/envs/EASC305/lib/python3.7/site-packages/nbgrader/converters/autograde.py", line 154, in init_assignment
        raise NbGraderException(msg)
    nbgrader.converters.base.NbGraderException: No notebooks found, did you forget to run 'nbgrader generate_assignment'?
    
[WARNING] Removing failed assignment: /Users/andrewnolan/sfuvault/Department/TAing/EASC_305_SPRING_2020/EASC-305-nbgrader/autograded/Alexandre/01_intro2python
[ERROR] There was an error processing assignment '01_intro2python' for student 'Alexandre'
[ERROR] Please see the the above traceback for details on the specific errors on the above failures.
```

I've created and generated the assignment from the formgrader. I can corroborate that the assignment has been generated by running `nbgrader db assignment list` which prints: 
```
[DbAssignmentListApp | WARNING] Config option `kernel_spec_manager_class` not recognized by `DbAssignmentListApp`.
There are 2 assignments in the database:
01_intro2python (due: None)
    - 01_intro2python
03_statistics_p2 (due: None)
    - 03_statistical_tests
```

Running `nbgrader db assignment list` the 11 student IDs in the course are displayed, though I will hold off from showing output the sake of student privacy. 

I'm curious what I might be doing wrong here? There seems to be a similar issue  #1219 , but there doesn't appear to be any resolution there. 

I appreciate any help in resolving this. I'm new to `nbgrader` so I'm sure its operator error, but am at a bit of a loss.

**Comment by jhamrick** [comment]
It looks to me like the notebook got renamed from `01_intro2python.ipynb` to ``nottalexandrehill_156676_14919471_01_intro2python_Alex_Nott.ipynb`. If you rename it back to the original name, does it then work?

**Comment by sigurdurb** [comment]
I had basically the same error when a student renamed their notebook.

First when trying to autograde in Formgrader we got this:
`nbgrader.converters.base.NbGraderException: No notebooks found, did you forget to run 'nbgrader generate_assignment'?`

and yes, renaming the notebook solved this issue.

nbgrader.log for reference:
```
[SingleUserNotebookApp | WARNING] Skipping unknown notebook: /home/gagr20221/gagr20221/submitted/sarahb19/Assignment-1-Exploratory-Data-Analysis/A01-Exploratory-Data-Analysis-sarahb19.ipynb
[SingleUserNotebookApp | ERROR] No notebooks found, did you forget to run 'nbgrader generate_assignment'?
[SingleUserNotebookApp | ERROR] There was an error processing assignment: /home/gagr20221/gagr20221/submitted/sarahb19/Assignment-1-Exploratory-Data-Analysis
[SingleUserNotebookApp | ERROR] Traceback (most recent call last):
      File "/etc/jupyterhub/nbgr/nbgrader/nbgrader/converters/base.py", line 386, in convert_notebooks
        self.init_assignment(gd['assignment_id'], gd['student_id'])
      File "/etc/jupyterhub/nbgr/nbgrader/nbgrader/converters/autograde.py", line 151, in init_assignment
        raise NbGraderException(msg)
    nbgrader.converters.base.NbGraderException: No notebooks found, did you forget to run 'nbgrader generate_assignment'?

[SingleUserNotebookApp | WARNING] Removing failed assignment: /home/gagr20221/gagr20221/autograded/sarahb19/Assignment-1-Exploratory-Data-Analysis
[SingleUserNotebookApp | ERROR] There was an error processing assignment 'Assignment-1-Exploratory-Data-Analysis' for student 'sarahb19'
[SingleUserNotebookApp | ERROR] Please see the the above traceback for details on the specific errors on the above failures.
```
