### ISSUE TITLE
Pytests not working?

### ISSUE THREAD

**Issue by trevorcampbell** [jupyter/nbgrader#1413]
Hi folks -- we're using nbgrader in the UBC stats department for a number of our courses. I am working on a few enhancements for a potential PR later on down the road, so I figured I should run the suite of tests to avoid regressions. But I'm having trouble getting the tests to run.

I have tried PyTests versions 3.8.0, 4.6.11, 5.4.3, and 6.2.0 -- all give me the exact same error. 

In the repository root I run: `python3 tasks.py tests`

and see the following error:

```
pytest --cov nbgrader --no-cov-on-fail -v -x --reruns 4
ERROR: usage: pytest [options] [file_or_dir] [file_or_dir] [...]
pytest: error: unrecognized arguments: --cov --no-cov-on-fail --reruns 4
  inifile: /home/trevor/repos/dsci/nbgrader/pytest.ini
  rootdir: /home/trevor/repos/dsci/nbgrader

Traceback (most recent call last):
  File "tasks.py", line 156, in <module>
    args.func(args)
  File "tasks.py", line 92, in tests
    _run_tests(mark=None, skip=args.skip, junitxml=args.junitxml)
  File "tasks.py", line 73, in _run_tests
    run(" ".join(cmd))
  File "tasks.py", line 15, in run
    return sp.check_call(cmd, shell=True)
  File "/usr/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'pytest --cov nbgrader --no-cov-on-fail -v -x --reruns 4' returned non-zero exit status 4.
```

I must be doing something wrong here, but it seems like it's `pytest` itself complaining about the command line arguments that `tasks.py` passes to it. Help would be much appreciated. Thank you!

### Operating system

`lsb_release -a`

```
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.2 LTS
Release:	20.04
Codename:	focal
```

`uname -a`:

```
Linux 5.4.0-65-generic #73-Ubuntu SMP Mon Jan 18 17:25:17 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```
### `nbgrader --version`

```
Python version 3.8.5 (default, Jul 28 2020, 12:59:40) 
[GCC 9.3.0]
nbgrader version 0.7.0.dev
```

### `jupyter notebook --version` 

```
6.1.4
```

**Comment by trevorcampbell** [comment]
Hold the phone -- I might be missing a package. One moment.

**Comment by trevorcampbell** [comment]
yup -- was missing `pytest-cov` and `pytest-rerunfailures`. Back to it!
