### ISSUE TITLE
nbgrader feedback  fail 

### ISSUE THREAD

**Issue by 2010hexi** [jupyter/nbgrader#1417]
when click Generate Feedback button, shows  the following message:

```
[FeedbackApp | WARNING] Config option `template_path` not recognized by `HTMLExporter`.  Did you mean one of: `extra_template_paths, template_name, template_paths`?
[FeedbackApp | INFO] Copying /home/grader/workshop2_2021/autograded/1002/sample/timestamp.txt -> /home/grader/workshop2_2021/feedback/1002/sample/timestamp.txt
[FeedbackApp | INFO] Converting notebook /home/grader/workshop2_2021/autograded/1002/sample/Sample01.ipynb
<jinja2.environment.Environment object at 0x7f5aeae95340> feedback.tpl
[FeedbackApp | ERROR] There was an error processing assignment: /home/grader/workshop2_2021/autograded/1002/sample
[FeedbackApp | ERROR] Traceback (most recent call last):
      File "/opt/anaconda3/lib/python3.8/site-packages/nbgrader/converters/base.py", line 336, in convert_notebooks
        self.convert_single_notebook(notebook_filename)
      File "/opt/anaconda3/lib/python3.8/site-packages/nbgrader/converters/base.py", line 292, in convert_single_notebook
        output, resources = self.exporter.from_filename(notebook_filename, resources=resources)
      File "/opt/anaconda3/lib/python3.8/site-packages/nbconvert/exporters/exporter.py", line 181, in from_filename
        return self.from_file(f, resources=resources, **kw)
      File "/opt/anaconda3/lib/python3.8/site-packages/nbconvert/exporters/exporter.py", line 199, in from_file
        return self.from_notebook_node(nbformat.read(file_stream, as_version=4), resources=resources, **kw)
      File "/opt/anaconda3/lib/python3.8/site-packages/nbconvert/exporters/html.py", line 119, in from_notebook_node
        return super().from_notebook_node(nb, resources, **kw)
      File "/opt/anaconda3/lib/python3.8/site-packages/nbconvert/exporters/templateexporter.py", line 384, in from_notebook_node
        output = self.template.render(nb=nb_copy, resources=resources)
      File "/opt/anaconda3/lib/python3.8/site-packages/nbconvert/exporters/templateexporter.py", line 148, in template
        self._template_cached = self._load_template()
      File "/opt/anaconda3/lib/python3.8/site-packages/nbconvert/exporters/templateexporter.py", line 355, in _load_template
        return self.environment.get_template(template_file)
      File "/opt/anaconda3/lib/python3.8/site-packages/jinja2/environment.py", line 883, in get_template
        return self._load_template(name, self.make_globals(globals))
      File "/opt/anaconda3/lib/python3.8/site-packages/jinja2/environment.py", line 857, in _load_template
        template = self.loader.load(self, name, globals)
      File "/opt/anaconda3/lib/python3.8/site-packages/jinja2/loaders.py", line 430, in load
        raise TemplateNotFound(name)
    jinja2.exceptions.TemplateNotFound: feedback.tpl

[FeedbackApp | WARNING] Removing failed assignment: /home/grader/workshop2_2021/feedback/1002/sample
[FeedbackApp | ERROR] There was an error processing assignment 'sample' for student '1002'
[FeedbackApp | ERROR] Please see the the above traceback for details on the specific errors on the above failures.
```

### Operating system
ubuntu 18.04

### `nbgrader --version`
nbgrader version 0.6.1

### `jupyterhub --version` (if used with JupyterHub)
1.0.0

### `jupyter notebook --version` 
6.1.4

### Expected behavior
generate feedback 
### Actual behavior
CANNOT generate feedback, 
given such warning 

```
[WARNING] Config option `template_path` not recognized by `HTMLExporter`.  Did you mean one of: `extra_template_paths, template_name, template_paths`?

```

not sure if this cause cannot find out the  feedback.tpl error

```
File "/opt/anaconda3/lib/python3.8/site-packages/jinja2/loaders.py", line 430, in load
        raise TemplateNotFound(name)
    jinja2.exceptions.TemplateNotFound: feedback.tpl
```

**Comment by jhamrick** [comment]
This is the same issue as #1373, will be fixed by #1421. In the meantime you can downgrade to nbconvert 5.6.1.
