### ISSUE TITLE
Error During Autograding 

### ISSUE THREAD

**Issue by ayush714** [jupyter/nbgrader#1455]
Hey, After collecting, If I am autograding, it is showing me below error. 

There was an error autograding 'ps1' for student 'jupyter-ayush488':

Log Output
[INFO] Copying /home/jupyter-ayush488/ML001/submitted/jupyter-ayush488/ps1/jupyter.png -> /home/jupyter-ayush488/ML001/autograded/jupyter-ayush488/ps1/jupyter.png
[INFO] Copying /home/jupyter-ayush488/ML001/submitted/jupyter-ayush488/ps1/timestamp.txt -> /home/jupyter-ayush488/ML001/autograded/jupyter-ayush488/ps1/timestamp.txt
[INFO] Creating/updating student with ID 'jupyter-ayush488': {}
[INFO] SubmittedAssignment<ps1 for jupyter-ayush488> submitted at 2021-06-14 17:56:30.466807
[INFO] Overwriting files with master versions from the source directory
[INFO] Copying /home/jupyter-ayush488/ML001/source/./ps1/jupyter.png -> /home/jupyter-ayush488/ML001/autograded/jupyter-ayush488/ps1/jupyter.png
[INFO] Sanitizing /home/jupyter-ayush488/ML001/submitted/jupyter-ayush488/ps1/problem1.ipynb
[INFO] Converting notebook /home/jupyter-ayush488/ML001/submitted/jupyter-ayush488/ps1/problem1.ipynb
[INFO] Writing 8695 bytes to /home/jupyter-ayush488/ML001/autograded/jupyter-ayush488/ps1/problem1.ipynb
[INFO] Autograding /home/jupyter-ayush488/ML001/autograded/jupyter-ayush488/ps1/problem1.ipynb
[INFO] Converting notebook /home/jupyter-ayush488/ML001/autograded/jupyter-ayush488/ps1/problem1.ipynb
[INFO] Executing notebook with kernel: python
[ERROR] There was an error processing assignment: /home/jupyter-ayush488/ML001/submitted/jupyter-ayush488/ps1
[ERROR] Traceback (most recent call last):
      File "/home/jupyter-ayush488/.local/lib/python3.7/site-packages/nbgrader/converters/base.py", line 332, in convert_notebooks
        self.convert_single_notebook(notebook_filename)
      File "/home/jupyter-ayush488/.local/lib/python3.7/site-packages/nbgrader/converters/autograde.py", line 195, in convert_single_notebook
        super(Autograde, self).convert_single_notebook(notebook_filename)
      File "/home/jupyter-ayush488/.local/lib/python3.7/site-packages/nbgrader/converters/base.py", line 288, in convert_single_notebook
        output, resources = self.exporter.from_filename(notebook_filename, resources=resources)
      File "/home/jupyter-ayush488/.local/lib/python3.7/site-packages/nbconvert/exporters/exporter.py", line 179, in from_filename
        return self.from_file(f, resources=resources, **kw)
      File "/home/jupyter-ayush488/.local/lib/python3.7/site-packages/nbconvert/exporters/exporter.py", line 197, in from_file
        return self.from_notebook_node(nbformat.read(file_stream, as_version=4), resources=resources, **kw)
      File "/home/jupyter-ayush488/.local/lib/python3.7/site-packages/nbconvert/exporters/notebook.py", line 32, in from_notebook_node
        nb_copy, resources = super(NotebookExporter, self).from_notebook_node(nb, resources, **kw)
      File "/home/jupyter-ayush488/.local/lib/python3.7/site-packages/nbconvert/exporters/exporter.py", line 139, in from_notebook_node
        nb_copy, resources = self._preprocess(nb_copy, resources)
      File "/home/jupyter-ayush488/.local/lib/python3.7/site-packages/nbconvert/exporters/exporter.py", line 316, in _preprocess
        nbc, resc = preprocessor(nbc, resc)
      File "/home/jupyter-ayush488/.local/lib/python3.7/site-packages/nbconvert/preprocessors/base.py", line 47, in __call__
        return self.preprocess(nb, resources)
      File "/home/jupyter-ayush488/.local/lib/python3.7/site-packages/nbgrader/preprocessors/execute.py", line 41, in preprocess
        output = super(Execute, self).preprocess(nb, resources)
      File "/home/jupyter-ayush488/.local/lib/python3.7/site-packages/nbconvert/preprocessors/execute.py", line 405, in preprocess
        nb, resources = super(ExecutePreprocessor, self).preprocess(nb, resources)
      File "/home/jupyter-ayush488/.local/lib/python3.7/site-packages/nbconvert/preprocessors/base.py", line 69, in preprocess
        nb.cells[index], resources = self.preprocess_cell(cell, resources, index)
      File "/home/jupyter-ayush488/.local/lib/python3.7/site-packages/nbconvert/preprocessors/execute.py", line 438, in preprocess_cell
        reply, outputs = self.run_cell(cell, cell_index, store_history)
      File "/home/jupyter-ayush488/.local/lib/python3.7/site-packages/nbconvert/preprocessors/execute.py", line 578, in run_cell
        exec_reply = self._poll_for_reply(parent_msg_id, cell, timeout)
      File "/home/jupyter-ayush488/.local/lib/python3.7/site-packages/nbconvert/preprocessors/execute.py", line 479, in _poll_for_reply
        if msg['parent_header'].get('msg_id') == msg_id:
    TypeError: 'coroutine' object is not subscriptable
    
[WARNING] Removing failed assignment: /home/jupyter-ayush488/ML001/autograded/jupyter-ayush488/ps1
[ERROR] There was an error processing assignment 'ps1' for student 'jupyter-ayush488'
[ERROR] Please see the the above traceback for details on the specific errors on the above failures.
Traceback
Traceback (most recent call last):
  File "/home/jupyter-ayush488/.local/lib/python3.7/site-packages/nbgrader/utils.py", line 533, in capture_log
    app.start()
  File "/home/jupyter-ayush488/.local/lib/python3.7/site-packages/nbgrader/converters/base.py", line 75, in start
    self.convert_notebooks()
  File "/home/jupyter-ayush488/.local/lib/python3.7/site-packages/nbgrader/converters/base.py", line 409, in convert_notebooks
    raise NbGraderException(msg)
nbgrader.converters.base.NbGraderException: Please see the the above traceback for details on the specific errors on the above failures.

### Operating system
Nan 

### `nbgrader --version`
nbgrader version 0.6.2

### `jupyterhub --version` (if used with JupyterHub)
1.4.0

**Comment by wanghan03** [comment]
Make sure your jupyter-client version is not 6.1.13 or 6.2.0, they've identified a similar issue and it's been yanked from release (see https://pypi.org/project/jupyter-client/#history and https://github.com/jupyter/jupyter_client/issues/637).

I ran into a similar issue and was able to fix it by installing `jupyer-client==6.1.12`

**Comment by ShyamCVL** [comment]
[requirements_new.txt](https://github.com/jupyter/nbgrader/files/7755578/requirements_new.txt)
I have attached a requirements file for a working jupyterhub with nbgrader extensions.
Do verify the versions for the packages especially the ones below are matching :

1.` nbgrader version==0.6.2`
2. `jupyter notebook==6.4.4`
3.` jupyter-client==6.1.12`

Me and my colleagues wasted a lot of time behind this hope this helps :D.

**Comment by goekce** [comment]
Thanks @ghost !
In my case it was sufficient to create `requirements.txt` with:
```
nbgrader==0.6.2                                                                                                                                                                                                                              
jupyter-client==6.1.12
```

**Comment by CarloNicolini** [comment]
Had this same error using a virtual environment with the latest Python 3.9.9.
Created a new empty environment on Python 3.7, installed the specific versions and everything run smoothly.

To be clear that was my installation

```
$> virtualenv venv --python=3.7
$> source venv/bin/activate
$> pip install nbgrader==0.6.2 jupyter-client=6.1.12
```
