### ISSUE TITLE
Error in validator

### ISSUE THREAD

**Issue by SJaffa** [jupyter/nbgrader#1512]
### Operating system
Ubuntu 20.04
### `nbgrader --version`
nbgrader version 0.6.2
### `jupyter notebook --version` 
6.4.4
### Expected behavior
Using the instructor notebooks, all cells run and pass tests, so the 'Validate button should give a 'pass'
### Steps to reproduce the behavior
Error message:
```
Traceback (most recent call last):
  File "/home/user/.local/lib/python3.8/site-packages/nbgrader/server_extensions/validate_assignment/handlers.py", line 46, in validate_notebook
    result = validator.validate(fullpath)
  File "/home/user/.local/lib/python3.8/site-packages/nbgrader/validator.py", line 311, in validate
    nb = self._preprocess(nb)
  File "/home/user/.local/lib/python3.8/site-packages/nbgrader/validator.py", line 290, in _preprocess
    nb, resources = pp.preprocess(nb, resources)
  File "/home/user/.local/lib/python3.8/site-packages/nbgrader/preprocessors/execute.py", line 41, in preprocess
    output = super(Execute, self).preprocess(nb, resources)
  File "/home/user/.local/lib/python3.8/site-packages/nbconvert/preprocessors/execute.py", line 405, in preprocess
    nb, resources = super(ExecutePreprocessor, self).preprocess(nb, resources)
  File "/home/user/.local/lib/python3.8/site-packages/nbconvert/preprocessors/base.py", line 69, in preprocess
    nb.cells[index], resources = self.preprocess_cell(cell, resources, index)
  File "/home/user/.local/lib/python3.8/site-packages/nbconvert/preprocessors/execute.py", line 438, in preprocess_cell
    reply, outputs = self.run_cell(cell, cell_index, store_history)
  File "/home/user/.local/lib/python3.8/site-packages/nbconvert/preprocessors/execute.py", line 578, in run_cell
    exec_reply = self._poll_for_reply(parent_msg_id, cell, timeout)
  File "/home/user/.local/lib/python3.8/site-packages/nbconvert/preprocessors/execute.py", line 479, in _poll_for_reply
    if msg['parent_header'].get('msg_id') == msg_id:
TypeError: 'coroutine' object is not subscriptable
```

**Comment by astraw** [comment]
This is similar to https://github.com/jupyter/nbgrader/issues/1455 .

For me installing `jupyter-client==6.1.12` fixed the issue.
