### ISSUE TITLE
Jupyterhub: "Module not found" when installing nbextension

### ISSUE THREAD

**Issue by Anphisa** [jupyter/nbgrader#1545]
### Operating system
Operating System: CentOS Linux 7 (Core)
CPE OS Name: cpe:/o:centos:centos:7
Kernel: Linux 3.10.0-1160.53.1.el7.x86_64
Architecture: x86-64

### `nbgrader --version`
nbgrader version 0.6.2

### `jupyterhub --version` (if used with JupyterHub)
1.4.2

### `jupyter notebook --version` 
6.4.3

### Expected behavior
Installation of notebook extensions for nbgrader

### Actual behavior
"Module not found" error:
```
Traceback (most recent call last):
  File "/jupyterhub/soft/apps/jupyterhub_1.4.2_venv/bin/jupyter-nbextension", line 8, in <module>
    sys.exit(main())
  File "/jupyterhub/soft/apps/jupyterhub_1.4.2_venv/lib/python3.8/site-packages/jupyter_core/application.py", line 254, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/jupyterhub/soft/apps/jupyterhub_1.4.2_venv/lib/python3.8/site-packages/traitlets/config/application.py", line 846, in launch_instance
    app.start()
  File "/jupyterhub/soft/apps/jupyterhub_1.4.2_venv/lib/python3.8/site-packages/notebook/nbextensions.py", line 980, in start
    super().start()
  File "/jupyterhub/soft/apps/jupyterhub_1.4.2_venv/lib/python3.8/site-packages/jupyter_core/application.py", line 243, in start
    self.subapp.start()
  File "/jupyterhub/soft/apps/jupyterhub_1.4.2_venv/lib/python3.8/site-packages/notebook/nbextensions.py", line 708, in start
    self.install_extensions()
  File "/jupyterhub/soft/apps/jupyterhub_1.4.2_venv/lib/python3.8/site-packages/notebook/nbextensions.py", line 679, in install_extensions
    full_dests = install(self.extra_args[0],
  File "/jupyterhub/soft/apps/jupyterhub_1.4.2_venv/lib/python3.8/site-packages/notebook/nbextensions.py", line 203, in install_nbextension_python
    m, nbexts = _get_nbextension_metadata(module)
  File "/jupyterhub/soft/apps/jupyterhub_1.4.2_venv/lib/python3.8/site-packages/notebook/nbextensions.py", line 1114, in _get_nbextension_metadata
    m = import_item(module)
  File "/jupyterhub/soft/apps/jupyterhub_1.4.2_venv/lib/python3.8/site-packages/traitlets/utils/importstring.py", line 38, in import_item
    return __import__(parts[0])
ModuleNotFoundError: No module named 'nbgrader'
```

### Steps to reproduce the behavior
`pip install nbgrader`
`jupyter nbextension install --sys-prefix --py nbgrader`

**Comment by szazs89** [comment]
Hi, have you run `pip` for the virtual env. of jupyterhub (`$venv/bin/pip`)? What does `pip list | grep jupy` show?

**Comment by Anphisa** [comment]
Thank you @szazs89! I did run the pip in the venv. Weirdly, the error automagically resolved. Can't say what happened (I changed nothing), but it works now. I'll close the issue.
