### ISSUE TITLE
`ImportError: cannot import name 'contextfilter' from 'jinja2'`

### ISSUE THREAD

**Issue by goekce** [jupyter/nbgrader#1555]
Using nbgrader 0.6.2 (also tried with 0.7.0-dev)

```
jupyter-nbconvert \
	--Exporter.preprocessors=nbgrader.preprocessors.LockCells \
	--Exporter.preprocessors=nbgrader.preprocessors.ClearSolutions \
	--Exporter.preprocessors=nbgrader.preprocessors.ClearOutput \
	--Exporter.preprocessors=nbgrader.preprocessors.CheckCellMetadata \
	--Exporter.preprocessors=nbgrader.preprocessors.ClearHiddenTests \
	--Exporter.preprocessors=nbgrader.preprocessors.ClearMarkScheme \
	--Exporter.preprocessors=nbgrader.preprocessors.ComputeChecksums \
	--stdout \
	--to ipynb \
	source.ipynb \
	> release.ipynb
```

leads to:

```
Traceback (most recent call last):
  File "/builds/lsi/inf2-notes/nbgrader/bin/jupyter-nbconvert", line 5, in <module>
    from nbconvert.nbconvertapp import main
  File "/builds/lsi/inf2-notes/nbgrader/lib/python3.10/site-packages/nbconvert/__init__.py", line 4, in <module>
    from .exporters import *
  File "/builds/lsi/inf2-notes/nbgrader/lib/python3.10/site-packages/nbconvert/exporters/__init__.py", line 3, in <module>
    from .html import HTMLExporter
  File "/builds/lsi/inf2-notes/nbgrader/lib/python3.10/site-packages/nbconvert/exporters/html.py", line 12, in <module>
    from jinja2 import contextfilter
ImportError: cannot import name 'contextfilter' from 'jinja2'
```

Apparently Jinja2 replaced contextfilter, here is a related issue from another project.

https://github.com/great-expectations/great_expectations/issues/4538

Pinning `jinja2==3.0.3` resolves the issue.

Should this be fixed in `jupyter-nbconvert` or here?

**Comment by damianavila** [comment]
> Should this be fixed in jupyter-nbconvert or here?

It seems to be an upstream issue, so I would report it there, IMHO.

**Comment by goekce** [comment]
This is related to an older jupyter-nbconvert version, so I don't think that it will be fixed.

Thanks for your opinion, at least this issue could help others.
