### ISSUE TITLE
nbgrader update should not bail out on exception

### ISSUE THREAD

**Issue by WolfgangFahl** [jupyter/nbgrader#1625]
### Operating system
docker image
```bash
uname -a
Linux f04418b6931a 5.10.104-linuxkit #1 SMP Thu Mar 17 17:08:06 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```
### `nbgrader --version`
nbgrader --version
Python version 3.9.13 | packaged by conda-forge | (main, May 27 2022, 16:56:21) 
[GCC 10.3.0]
nbgrader version 0.7.0

### Expected behavior
nbgrader update . should continue on error and display a list of problems when finished

### Actual behavior
```
nbgrader update .
UpdateApp | INFO] Updating metadata for notebook: ...
...
UpdateApp | ERROR] Traceback (most recent call last):
      File "/home/jovyan/.local/lib/python3.9/site-packages/nbgrader/apps/updateapp.py", line 81, in start
        write(nb, notebook)
      File "/home/jovyan/.local/lib/python3.9/site-packages/nbgrader/nbgraderformat/v3.py", line 121, in write_v3
        MetadataValidatorV3().validate_nb(nb)
      File "/home/jovyan/.local/lib/python3.9/site-packages/nbgrader/nbgraderformat/v3.py", line 110, in validate_nb
        raise ValidationError("Duplicate grade id: {}".format(grade_id))
    jsonschema.exceptions.ValidationError: Duplicate grade id: ...
    
[UpdateApp | ERROR] Notebook '.....' failed to validate, metadata is corrupted
```
and update process top

### Steps to reproduce the behavior

- collect a few valid notebooks

- create two corrupted notebooks e.g. by duplicating a ce
- run nbgrader update

**Comment by jhamrick** [comment]
Seems like a reasonable thing to have an option to continue on error, and just printing the errors at the end.
