### ISSUE TITLE
Demo not starting

### ISSUE THREAD

**Issue by perllaghu** [jupyter/nbgrader#1668]
I've tried as both the remote server and the Docker image route (in both cases, the root OS is ubuntu 22:04) and get the same error:

```
  Running setup.py develop for nbgrader
    error: subprocess-exited-with-error
    
    × python setup.py develop did not run successfully.
    │ exit code: 1
    ╰─> [77 lines of output]
        running develop
        /usr/lib/python3/dist-packages/setuptools/command/easy_install.py:158: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
          warnings.warn(
        /usr/lib/python3/dist-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
          warnings.warn(
        /usr/lib/python3/dist-packages/pkg_resources/__init__.py:116: PkgResourcesDeprecationWarning: 1.1build1 is an invalid version and will not be supported in a future release
          warnings.warn(
        running egg_info
        writing nbgrader.egg-info/PKG-INFO
        writing dependency_links to nbgrader.egg-info/dependency_links.txt
        writing entry points to nbgrader.egg-info/entry_points.txt
        writing requirements to nbgrader.egg-info/requires.txt
        writing top-level names to nbgrader.egg-info/top_level.txt
        reading manifest file 'nbgrader.egg-info/SOURCES.txt'
        reading manifest template 'MANIFEST.in'
        warning: no directories found matching 'nbgrader/labextension'
        no previously-included directories found matching '**/node_modules'
        no previously-included directories found matching 'lib'
        no previously-included directories found matching 'nbgrader/docs/build'
        warning: no previously-included files matching '*.pyc' found anywhere in distribution
        warning: no previously-included files matching '.ipynb_checkpoints' found anywhere in distribution
        warning: no previously-included files matching '__pycache__' found anywhere in distribution
        warning: no previously-included files matching '.git' found anywhere in distribution
        warning: no previously-included files matching '*.pyo' found anywhere in distribution
        warning: no previously-included files matching '*~' found anywhere in distribution
        no previously-included directories found matching 'demos'
        no previously-included directories found matching 'tools'
        no previously-included directories found matching 'paper'
        no previously-included directories found matching 'binder'
        adding license file 'LICENSE'
        writing manifest file 'nbgrader.egg-info/SOURCES.txt'
        running build_ext
        Creating /usr/local/lib/python3.10/dist-packages/nbgrader.egg-link (link to .)
        Adding nbgrader 0.8.0 to easy-install.pth file
        Installing nbgrader script to /usr/local/bin
        
        Installed /srv/nbgrader/nbgrader
        running post_develop
        yarn not found, ignoring yarn.lock file
        yarn install v1.21.1
        [1/4] Resolving packages...
        [2/4] Fetching packages...
        warning @blueprintjs/core@3.54.0: Invalid bin entry for "upgrade-blueprint-2.0.0-rename" (in "@blueprintjs/core").
        warning @blueprintjs/core@3.54.0: Invalid bin entry for "upgrade-blueprint-3.0.0-rename" (in "@blueprintjs/core").
        error @playwright/test@1.22.2: The engine "node" is incompatible with this module. Expected version ">=14". Got "12.22.9"
        error Found incompatible module.
        info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
        Traceback (most recent call last):
          File "<string>", line 2, in <module>
          File "<pip-setuptools-caller>", line 34, in <module>
          File "/srv/nbgrader/nbgrader/setup.py", line 62, in <module>
            setup(**setup_args)
          File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 153, in setup
            return distutils.core.setup(**attrs)
          File "/usr/lib/python3/dist-packages/setuptools/_distutils/core.py", line 148, in setup
            return run_commands(dist)
          File "/usr/lib/python3/dist-packages/setuptools/_distutils/core.py", line 163, in run_commands
            dist.run_commands()
          File "/usr/lib/python3/dist-packages/setuptools/_distutils/dist.py", line 967, in run_commands
            self.run_command(cmd)
          File "/usr/lib/python3/dist-packages/setuptools/_distutils/dist.py", line 986, in run_command
            cmd_obj.run()
          File "/tmp/pip-build-env-gpe5ljz7/overlay/local/lib/python3.10/dist-packages/jupyter_packaging/setupbase.py", line 151, in run
            self.run_command(post_build.__name__)
          File "/usr/lib/python3/dist-packages/setuptools/_distutils/cmd.py", line 313, in run_command
            self.distribution.run_command(command)
          File "/usr/lib/python3/dist-packages/setuptools/_distutils/dist.py", line 986, in run_command
            cmd_obj.run()
          File "/tmp/pip-build-env-gpe5ljz7/overlay/local/lib/python3.10/dist-packages/jupyter_packaging/setupbase.py", line 127, in run
            func()
          File "/tmp/pip-build-env-gpe5ljz7/overlay/local/lib/python3.10/dist-packages/jupyter_packaging/setupbase.py", line 231, in builder
            run(npm_cmd + ["install"], cwd=node_package)
          File "/tmp/pip-build-env-gpe5ljz7/overlay/local/lib/python3.10/dist-packages/jupyter_packaging/setupbase.py", line 297, in run
            return subprocess.check_call(cmd, **kwargs)
          File "/usr/lib/python3.10/subprocess.py", line 369, in check_call
            raise CalledProcessError(retcode, cmd)
        subprocess.CalledProcessError: Command '['/usr/local/bin/jlpm', 'install']' returned non-zero exit status 1.
        [end of output]
```

..... and I pick out

    error @playwright/test@1.22.2: The engine "node" is incompatible with this module. Expected version ">=14". Got "12.22.9"

as the primary issue.

I've tried manually updating `nodejs` manually, and reverting to `Ubuntu 20:04` - neither _magically_ fixed it.

(related to #1664 - checking the action of the `feedback` link)

**Comment by brichet** [comment]
Thanks for opening this @perllaghu.
I started #1674, which should fix the error with the docker. 
Can you try it ?

I don't really understand how it is related to #1664,.

**Comment by perllaghu** [comment]
It's connected - because I need to test nbgrader in an isolated environment, away from my K8 cluster, my Docker images, and even possible pollution from libraries already installed on my workstation.
