### ISSUE TITLE
nbconvert markdown_mistune.py breaks Manual grading view

### ISSUE THREAD

**Issue by Adamtaranto** [jupyter/nbgrader#1689]
### Operating system
Mac OS Big Sur 11.7

### `nbgrader --version`

Python version 3.8.13 | packaged by conda-forge | (default, Mar 25 2022, 06:05:47) 
[Clang 12.0.1 ]
nbgrader version 0.8.1

### `jupyter notebook --version` 
6.4.12

### Expected behavior

Trying to open submission for manual grading after successful autograding.

### Actual behavior

Autograding works fine, but when trying to open any individual submission for manual grading a get an error page with:

```
"Sorry, the formgrader encountered an error. Please contact the administrator of the formgrader for further assistance."
```

Based on the terminal output below, I think the error is coming from a function in nbconvert's `markdown_mistune.py` which is trying to set cell formatting with pygments. The code on line 171 is in a try catch exception, so I don't know how it is managing to throw an error that breaks nbgrader. 

This is only happening with one particular assignment. Other assignments in the same nbgrader instance are behaving normally.

Please help! I need a quick fix so I can mark this batch of assignments.

### Steps to reproduce the behaviour
I can send you a copy of the assignment source and one of the submission that is breaking the manual grading view.

```
[I 13:50:30.341 NotebookApp] Released assignments:
[E 13:50:30.948 NotebookApp] Uncaught exception GET /formgrader/submissions/08a43561e2e445cfae5468357d01292e/ (::1)
    HTTPServerRequest(protocol='http', host='localhost:8888', method='GET', uri='/formgrader/submissions/08a43561e2e445cfae5468357d01292e/', version='HTTP/1.1', remote_ip='::1')
    Traceback (most recent call last):
      File "/opt/anaconda3/envs/nbgrader2/lib/python3.8/site-packages/tornado/web.py", line 1711, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/opt/anaconda3/envs/nbgrader2/lib/python3.8/site-packages/tornado/web.py", line 3208, in wrapper
        return method(self, *args, **kwargs)
      File "/opt/anaconda3/envs/nbgrader2/lib/python3.8/site-packages/nbgrader/server_extensions/formgrader/base.py", line 109, in wrapper
        return f(self, *args, **kwargs)
      File "/opt/anaconda3/envs/nbgrader2/lib/python3.8/site-packages/nbgrader/server_extensions/formgrader/base.py", line 118, in wrapper
        return f(self, *args, **kwargs)
      File "/opt/anaconda3/envs/nbgrader2/lib/python3.8/site-packages/nbgrader/server_extensions/formgrader/handlers.py", line 127, in get
        html, _ = self.exporter.from_filename(filename, resources=resources)
      File "/opt/anaconda3/envs/nbgrader2/lib/python3.8/site-packages/nbconvert/exporters/exporter.py", line 190, in from_filename
        return self.from_file(f, resources=resources, **kw)
      File "/opt/anaconda3/envs/nbgrader2/lib/python3.8/site-packages/nbconvert/exporters/exporter.py", line 207, in from_file
        return self.from_notebook_node(
      File "/opt/anaconda3/envs/nbgrader2/lib/python3.8/site-packages/nbconvert/exporters/html.py", line 223, in from_notebook_node
        return super().from_notebook_node(nb, resources, **kw)
      File "/opt/anaconda3/envs/nbgrader2/lib/python3.8/site-packages/nbconvert/exporters/templateexporter.py", line 401, in from_notebook_node
        output = self.template.render(nb=nb_copy, resources=resources)
      File "/opt/anaconda3/envs/nbgrader2/lib/python3.8/site-packages/jinja2/environment.py", line 1301, in render
        self.environment.handle_exception()
      File "/opt/anaconda3/envs/nbgrader2/lib/python3.8/site-packages/jinja2/environment.py", line 936, in handle_exception
        raise rewrite_traceback_stack(source=source)
      File "/opt/anaconda3/envs/nbgrader2/lib/python3.8/site-packages/nbgrader/server_extensions/formgrader/templates/formgrade/index.html.j2", line 94, in top-level template code
        <div><textarea id="{{ cell.metadata.nbgrader.grade_id }}-comment" class="comment tabbable"></textarea></div>
      File "/opt/anaconda3/envs/nbgrader2/share/jupyter/nbconvert/templates/classic/index.html.j2", line 3, in top-level template code
        {% from 'jupyter_widgets.html.j2' import jupyter_widgets %}
      File "/opt/anaconda3/envs/nbgrader2/share/jupyter/nbconvert/templates/classic/base.html.j2", line 2, in top-level template code
        {% from 'celltags.j2' import celltags %}
      File "/opt/anaconda3/envs/nbgrader2/share/jupyter/nbconvert/templates/base/display_priority.j2", line 1, in top-level template code
        {%- extends 'base/null.j2' -%}
      File "/opt/anaconda3/envs/nbgrader2/share/jupyter/nbconvert/templates/base/null.j2", line 26, in top-level template code
        {%- block body -%}
      File "/opt/anaconda3/envs/nbgrader2/lib/python3.8/site-packages/nbgrader/server_extensions/formgrader/templates/formgrade/index.html.j2", line 39, in block 'body'
        {{ super() }}
      File "/opt/anaconda3/envs/nbgrader2/share/jupyter/nbconvert/templates/base/null.j2", line 29, in block 'body'
        {%- block body_loop -%}
      File "/opt/anaconda3/envs/nbgrader2/share/jupyter/nbconvert/templates/base/null.j2", line 31, in block 'body_loop'
        {%- block any_cell scoped -%}
      File "/opt/anaconda3/envs/nbgrader2/share/jupyter/nbconvert/templates/base/null.j2", line 87, in block 'any_cell'
        {%- block markdowncell scoped-%} {%- endblock markdowncell -%}
      File "/opt/anaconda3/envs/nbgrader2/lib/python3.8/site-packages/nbgrader/server_extensions/formgrader/templates/formgrade/index.html.j2", line 108, in block 'markdowncell'
        {{ cell.source  | markdown2html | strip_files_prefix }}
      File "/opt/anaconda3/envs/nbgrader2/lib/python3.8/site-packages/nbconvert/exporters/html.py", line 204, in markdown2html
        return MarkdownWithMath(renderer=renderer).render(source)
      File "/opt/anaconda3/envs/nbgrader2/lib/python3.8/site-packages/nbconvert/filters/markdown_mistune.py", line 142, in render
        return self.parse(s)
      File "/opt/anaconda3/envs/nbgrader2/lib/python3.8/site-packages/mistune/markdown.py", line 50, in parse
        result = self.block.render(tokens, self.inline, state)
      File "/opt/anaconda3/envs/nbgrader2/lib/python3.8/site-packages/mistune/block_parser.py", line 274, in render
        return inline.renderer.finalize(data)
      File "/opt/anaconda3/envs/nbgrader2/lib/python3.8/site-packages/mistune/renderers.py", line 220, in finalize
        return ''.join(data)
      File "/opt/anaconda3/envs/nbgrader2/lib/python3.8/site-packages/mistune/block_parser.py", line 291, in _iter_render
        yield method(children, *params)
      File "/opt/anaconda3/envs/nbgrader2/lib/python3.8/site-packages/nbconvert/filters/markdown_mistune.py", line 171, in block_code
        lang = info.strip().split(None, 1)[0]
    IndexError: list index out of range
[E 13:50:30.953 NotebookApp] {
      "Host": "localhost:8888",
      "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9",
      "Referer": "http://localhost:8888/formgrader/manage_students/45842/Assignment_2",
      "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36"
    }
[E 13:50:30.953 NotebookApp] 500 GET /formgrader/submissions/08a43561e2e445cfae5468357d01292e/ (::1) 620.900000ms referer=http://localhost:8888/formgrader/manage_students/45842/Assignment_2

```

**Comment by Adamtaranto** [comment]
I have found the problem. nbgrader is passing an all whitespace string of four spaces ('    ') to the block_code() method of an nbconvert IPythonRenderer(HTMLRenderer) object, as defined in  "nbconvert/filters/markdown_mistune.py"

When this string is processed with info.strip().split(None, 1) it yields an empty list which has no index [0]

I've added some print statements to the offending code that will report the 'info' strings that are being passed from nbgrader. When I try to load the submission for manual grading I see ' python' passed in and processed correctly, and then '    ', which breaks things.

```python
def block_code(self, code, info=None):
        lang = ""
        lexer = None
        if info:
            try:
                print("WARNING: SOMETHING BROKEN HERE!!!!")
                print(f"info={repr(info)}")
                lang = info.strip().split(None, 1)[0]
                lexer = get_lexer_by_name(lang, stripall=True)
            except ClassNotFound:
                code = lang + "\n" + code
                lang = None

        if not lang:
            return super().block_code(code)

        formatter = HtmlFormatter()
        return highlight(code, lexer, formatter)
```

For now I have fixed the issue by doing a force uninstall of nbconvert and then reinstalling with pip in developer mode so that I could manually patch the code. 

```bash
conda remove --force nbconvert 
mkdir local_packages && cd local_packages
git clone https://github.com/jupyter/nbconvert.git
cd nbconvert
pip install -e .
```

Patched markdown_mistune.py code:

```python
    def block_code(self, code, info=None):
        lang = ""
        lexer = None
        if info:
            try:
                # print("WARNING: SOMETHING BROKEN HERE!!!!")
                # print(f"info={repr(info)}")
                # Only try to set 'lang' if split 'info' list not empty.
                if info.strip().split(None, 1):
                    lang = info.strip().split(None, 1)[0]
                    lexer = get_lexer_by_name(lang, stripall=True)
            except ClassNotFound:
                code = lang + "\n" + code
                lang = None

        if not lang:
            return super().block_code(code)

        formatter = HtmlFormatter()
        return highlight(code, lexer, formatter)
```

This should probably be fixed upstream in nbgrader to prevent blank strings being passed as the info argument in the first place. I'm not sure exactly where the blank string is coming from or which the problem only occurs with some of my assignment docs.

Can send example doc if someone wants to figure out the root issue.

**Comment by rhema** [comment]
Bumping this, as I also ran into this bug in case it is helpful. Here's a quick doc that illustrates the same breaking code path: 
![image](https://github.com/jupyter/nbgrader/assets/325536/d31e38a0-6c6e-4736-9457-bbd96552a078)

It seems that adding a space after the docstring breaks .html conversion. The one on the right successfully uses nbconvert to make html, but the one on the right fails with the extra space.

**Comment by Adamtaranto** [comment]
Ah, this makes so much sense! Thanks @rhema 

I'll open a pull request with nbconvert
