### ISSUE TITLE
"Loading, please wait..." message not resolving under "Manage Assignments"

### ISSUE THREAD

**Issue by dynelson** [jupyter/nbgrader#1710]
Operating system: Ventura 13.0.1

`nbgrader version 0.8.1

`jupyter notebook version 6.5.2

Hi nbgrader support --

I've loaded 2 sample assignments titled ps1 into the directories submitted/student_a/ps1 and submitted/student_b/ps1.  When I navigate to Formgrader/Manage Assignments, the number "2" is displayed under "Submission," as expected. However, after clicking on "2", the message "Loading, please wait..." is displayed under "Student Name" and never resolves.  

Per the instructions I tried typing 

cd "/Users/me"
nbgrader autograde "ps1"

into the terminal.  This came back:

[AutogradeApp | WARNING] No nbgrader_config.py file found (rerun with --debug to see where nbgrader is looking)
[AutogradeApp | INFO] Copying /Users/me/submitted/student_a/ps1/.DS_Store ->
 /Users/me/autograded/student_a/ps1/.DS_Store
[AutogradeApp | INFO] Creating/updating student with ID 'student_a': {}
[AutogradeApp | INFO] Overwriting files with master versions from the source directory
[AutogradeApp | INFO] Copying /Users/davidyrueta/source/./ps1/.DS_Store -> 
/Users/me/autograded/student_a/ps1/.DS_Store
[AutogradeApp | INFO] Sanitizing /Users/me/submitted/student_a/ps1/ps1.ipynb
[AutogradeApp | INFO] Converting notebook /Users/me/submitted/student_a/ps1/ps1.ipynb
[AutogradeApp | INFO] Writing 4040 bytes to /Users/me/autograded/student_a/ps1/ps1.ipynb
[AutogradeApp | INFO] Autograding /Users/me/autograded/student_a/ps1/ps1.ipynb
[AutogradeApp | INFO] Converting notebook /Users/me/autograded/student_a/ps1/ps1.ipynb
[AutogradeApp | INFO] Writing 7162 bytes to /Users/me/autograded/student_a/ps1/ps1.ipynb
[AutogradeApp | INFO] Setting destination file permissions to 444
[AutogradeApp | INFO] Copying /Users/me/submitted/student_b/ps1/.DS_Store -> 
/Users/me/autograded/student_b/ps1/.DS_Store
[AutogradeApp | INFO] Creating/updating student with ID 'student_b': {}
[AutogradeApp | INFO] Overwriting files with master versions from the source directory
[AutogradeApp | INFO] Copying /Users/me/source/./ps1/.DS_Store ->
 /Users/davidyrueta/autograded/student_b/ps1/.DS_Store
[AutogradeApp | INFO] Sanitizing /Users/me/submitted/student_b/ps1/ps1.ipynb
[AutogradeApp | INFO] Converting notebook /Users/me/submitted/student_b/ps1/ps1.ipynb
[AutogradeApp | INFO] Writing 4052 bytes to /Users/me/autograded/student_b/ps1/ps1.ipynb
[AutogradeApp | INFO] Autograding /Users/me/autograded/student_b/ps1/ps1.ipynb
[AutogradeApp | INFO] Converting notebook /Users/me/autograded/student_b/ps1/ps1.ipynb
[AutogradeApp | INFO] Writing 7174 bytes to /Users/me/autograded/student_b/ps1/ps1.ipynb
[AutogradeApp | INFO] Setting destination file permissions to 444

I suppose the warning 

[AutogradeApp | WARNING] No nbgrader_config.py file found (rerun with --debug to see where nbgrader is looking)

is part of the problem!  Not sure what I'm supposed to rerun (sorry, I'm a complete newbie).  Please help!

And thanks for developing such a cool app.  Much appreciated!

**Comment by perllaghu** [comment]
Have you created the directory `/srv/nbgrader/exchange` (as per the warning in formgrader)?

**Comment by dynelson** [comment]
Hi perllaghu --
Nope, I hadn't.  Sorry for being such a newbie, and thank you for taking a look!  

I wrote the command to make /srv/nbgrader/exchange per the docs.  Now when I click on "# of Submissions" this is the output:

[E 04:37:28.571 NotebookApp] Uncaught exception GET /formgrader/api/submissions/ps1 (::1)
    HTTPServerRequest(protocol='http', host='localhost:8890', method='GET', uri='/formgrader/api/submissions/ps1', version='HTTP/1.1', remote_ip='::1')
    Traceback (most recent call last):
      File "/Users/davidyrueta/opt/anaconda3/lib/python3.9/site-packages/tornado/web.py", line 1711, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/Users/davidyrueta/opt/anaconda3/lib/python3.9/site-packages/tornado/web.py", line 3208, in wrapper
        return method(self, *args, **kwargs)
      File "/Users/davidyrueta/opt/anaconda3/lib/python3.9/site-packages/nbgrader/server_extensions/formgrader/base.py", line 108, in wrapper
        return f(self, *args, **kwargs)
      File "/Users/davidyrueta/opt/anaconda3/lib/python3.9/site-packages/nbgrader/server_extensions/formgrader/base.py", line 117, in wrapper
        return f(self, *args, **kwargs)
      File "/Users/davidyrueta/opt/anaconda3/lib/python3.9/site-packages/nbgrader/server_extensions/formgrader/apihandlers.py", line 167, in get
        submissions = self.api.get_submissions(assignment_id)
      File "/Users/davidyrueta/opt/anaconda3/lib/python3.9/site-packages/nbgrader/apps/api.py", line 587, in get_submissions
        db_submissions = gb.submission_dicts(assignment_id)
      File "/Users/davidyrueta/opt/anaconda3/lib/python3.9/site-packages/nbgrader/api.py", line 3053, in submission_dicts
        all_scores = aliased(union_all(
      File "/Users/davidyrueta/opt/anaconda3/lib/python3.9/site-packages/sqlalchemy/orm/util.py", line 1357, in aliased
        return AliasedClass(
      File "/Users/davidyrueta/opt/anaconda3/lib/python3.9/site-packages/sqlalchemy/orm/util.py", line 496, in __init__
        mapper = insp.mapper
    AttributeError: 'CompoundSelect' object has no attribute 'mapper'
[E 04:37:28.584 NotebookApp] {
      "Host": "localhost:8890",
      "Accept": "application/json, text/javascript, */*; q=0.01",
      "Referer": "http://localhost:8890/formgrader/manage_submissions/ps1",
      "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.1 Safari/605.1.15"
    }
[E 04:37:28.584 NotebookApp] 500 GET /formgrader/api/submissions/ps1 (::1) 30.490000ms referer=http://localhost:8890/formgrader/manage_submissions/ps1

I looked up the error  Uncaught exception GET and read this error can be resolved by upgrading nbconvert, so I typed 
 
pip install --upgrade --user nbconvert

and received these messages:

  WARNING: The scripts jupyter-dejavu and jupyter-nbconvert are installed in '/Users/davidyrueta/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
spyder 5.3.3 requires pyqt5<5.16, which is not installed.
spyder 5.3.3 requires pyqtwebengine<5.16, which is not installed.
nbgrader 0.6.2 requires nbconvert==5.6.1, but you have nbconvert 7.2.6 which is incompatible.
nbgrader 0.6.2 requires sqlalchemy<1.4, but you have sqlalchemy 1.4.39 which is incompatible.
nbgrader 0.6.2 requires traitlets==4.3.3, but you have traitlets 5.1.1 which is incompatible.

Do I need to revert to lower versions of nbconvert, sqlalchemy and traitlets?

**Comment by dynelson** [comment]
I tried downgrading to 5.6.1 with the command conda install "nbconvert=5.6.1" and received this message:

UnsatisfiableError: The following specifications were found
to be incompatible with the existing python installation in your environment:

Specifications:

  - nbconvert=5.6.1 -> python[version='>=2.7,<2.8.0a0|>=3.8,<3.9.0a0|>=3.7,<3.8.0a0|>=3.6,<3.7.0a0']

Your python: python=3.9

If python is on the left-most side of the chain, that's the version you've asked for.
When python appears to the right, that indicates that the thing on the left is somehow
not available for the python version you are constrained to. Note that conda will not
change your python version to a different minor version unless you explicitly specify
that.

Thoughts?  Thank you!

**Comment by perllaghu** [comment]
Hmm... nbconvert should be a problem any more.

What version of nbgrader are you using (`pip list`)?

I have the following (massively cut down from my full list)

```
jupyter_client            7.3.0
jupyter_console           6.4.4
jupyter_core              4.9.2
jupyter_server            1.17.0
jupyterlab                3.3.4
nbclassic                 0.3.7
nbclient                  0.6.3
nbconvert                 6.5.0
nbformat                  5.3.0
nbgrader                  0.7.1
notebook                  6.4.11
sqlalchemy                1.4.36
``` 

NBGrader 0.6.0 *did* have nbconvert problems, but they were fixed in later releases

**Comment by perllaghu** [comment]
Can you upgrade to nbgrader 0.7?

**Comment by dynelson** [comment]
Sure. Can you tell me what to type? I tried conda install “nbgrader = 0.7.0” and received this message

Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.

PackagesNotFoundError: The following packages are not available from current channels:

  - nbgrader=0.7.0

Current channels:

  - https://repo.anaconda.com/pkgs/main/osx-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/osx-64
  - https://repo.anaconda.com/pkgs/r/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.

The command I used to install nbgrader was 

conda install -c conda-forge nbgrader

Thank you!

**Comment by perllaghu** [comment]
`conda upgrade nbgrader` will upgrade the library `nbgrader` to the latest version

**Comment by dynelson** [comment]
I ran that command and it seemed to execute.  But when I ran pip list, nbgrader returns as version 0.6.2.  

Should I try to uninstall and reinstall Anaconda?

**Comment by dynelson** [comment]
Hi perllaghu --
I seem stuck at nbgrader version 0.6.2 and can't upgrade.  

I followed the instructions here https://docs.anaconda.com/anaconda/install/uninstall/
to remove the anaconda3 distribution from my machine. I then ran the graphical installer to reinstall Anaconda. That failed with a message saying Anaconda is already installed on the machine, and to update to the latest version.  

I followed the prompts and ran conda update anaconda to upgrade to anaconda3.  When I opened a Jupyter notebook, Formgrader was gone, so I reinstalled nbgrader using the command conda install -c conda-forge nbgrader.  

Formgrader appeared, but Manage Submissions still won't load.  When I ran pip list, I'm still stuck at nbgrader version 0.6.2, and can't seem to upgrade. 

Thoughts?  Thanks for all your help.

**Comment by dynelson** [comment]
Last comment.  After uninstalling and reinstalling Anaconda, I ran the script in the terminal to reinstall the nbgrader package, and received this message:

(base) davidyrueta@Davids-MBP-2 ~ % conda install -c conda-forge nbgrader
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: done\

It seems that the version of nbgrader from the "next repodata source" is 0.6.2:

The following NEW packages will be INSTALLED:

  alembic            conda-forge/noarch::alembic-1.8.1-pyhd8ed1ab_0
  importlib_resourc~ conda-forge/noarch::importlib_resources-5.10.1-pyhd8ed1ab_0
  mako               conda-forge/noarch::mako-1.2.4-pyhd8ed1ab_0
  nbgrader           conda-forge/osx-64::nbgrader-0.6.2-py39h6e9494a_2
  python_abi         conda-forge/osx-64::python_abi-3.9-2_cp39
  rapidfuzz          conda-forge/osx-64::rapidfuzz-2.13.6-py39h7a8716b_0

This must be why I'm stuck at 0.6.2, which seems related to the particular type of "environment solution" implemented by the installer.  Is there any way to fix this?

Thanks!

**Comment by perllaghu** [comment]
You don't need to remove the whole anaconda install to upgrade a library
 
It's tricky for me to replicate what you have, as I run jupyter notebooks in a cluster, not on my workstation, and I already have a different method of installing python libraries across the various projects & services & code-bases I have.

`conda install -c conda-forge nbgrader==0.8.1` doesn't work for you?

**Comment by perllaghu** [comment]
Ah... and you can also try `conda install -c conda-forge nbgrader -v -v -v` for lots and lots and lots of verbose information.... that may tell you what's locking nbgrader to such an old version

**Comment by dynelson** [comment]
It doesn’t seem to:

(base) ***@***.*** ~ % conda install -c conda-forge nbgrader==0.8.1
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: \

I’m stuck here for now.  

At this point, I imagine my issue is way beyond nbgrader and into the particulars of my machine config. Just want to let you know I really appreciate your help.

**Comment by perllaghu** [comment]
Yep.... There's some other library that has nbgrader=0.6.* has a requirement - and that's stopping the update

**Comment by dynelson** [comment]
OK, well I'll try to follow up on that idea elsewhere and see where I get. If I can find a solution, I'll make sure to post it.  Thanks again!

**Comment by dynelson** [comment]
For what it's worth, I encountered the sam problem while trying to install nbgrader on a different Mac running Ventrura.  I'm wondering if the issue is related to Ventura.

**Comment by dynelson** [comment]
UPDATE: 
Writing `conda install jupyter` in the terminal resolved the package inconsistencies and allowed me to upgrade to nbgrader version 0.8.1, but didn't resolve the loading issue. 

Here is the terminal output that results from trying to load assignments into the "Manage Assignments" window:

[E 17:31:52.161 NotebookApp] Uncaught exception GET /formgrader/api/submissions/ps1 (127.0.0.1)
    HTTPServerRequest(protocol='http', host='localhost:8891', method='GET', uri='/formgrader/api/submissions/ps1', version='HTTP/1.1', remote_ip='127.0.0.1')
    Traceback (most recent call last):
      File "/Users/davidyrueta/opt/anaconda3/lib/python3.9/site-packages/tornado/web.py", line 1702, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/Users/davidyrueta/opt/anaconda3/lib/python3.9/site-packages/tornado/web.py", line 3173, in wrapper
        return method(self, *args, **kwargs)
      File "/Users/davidyrueta/opt/anaconda3/lib/python3.9/site-packages/nbgrader/server_extensions/formgrader/base.py", line 108, in wrapper
        return f(self, *args, **kwargs)
      File "/Users/davidyrueta/opt/anaconda3/lib/python3.9/site-packages/nbgrader/server_extensions/formgrader/base.py", line 117, in wrapper
        return f(self, *args, **kwargs)
      File "/Users/davidyrueta/opt/anaconda3/lib/python3.9/site-packages/nbgrader/server_extensions/formgrader/apihandlers.py", line 167, in get
        submissions = self.api.get_submissions(assignment_id)
      File "/Users/davidyrueta/opt/anaconda3/lib/python3.9/site-packages/nbgrader/apps/api.py", line 587, in get_submissions
        db_submissions = gb.submission_dicts(assignment_id)
      File "/Users/davidyrueta/opt/anaconda3/lib/python3.9/site-packages/nbgrader/api.py", line 3053, in submission_dicts
        all_scores = aliased(union_all(
      File "/Users/davidyrueta/opt/anaconda3/lib/python3.9/site-packages/sqlalchemy/orm/util.py", line 1357, in aliased
        return AliasedClass(
      File "/Users/davidyrueta/opt/anaconda3/lib/python3.9/site-packages/sqlalchemy/orm/util.py", line 496, in __init__
        mapper = insp.mapper
    AttributeError: 'CompoundSelect' object has no attribute 'mapper'
[E 17:31:52.169 NotebookApp] {
      "Host": "localhost:8891",
      "Accept": "application/json, text/javascript, */*; q=0.01",
      "Referer": "http://localhost:8891/formgrader/manage_submissions/ps1",
      "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:108.0) Gecko/20100101 Firefox/108.0"

Any help interpreting this would be greatly appreciated!

**Comment by brichet** [comment]
@dynelson what is the status of this issue ? Did you fix it ?

**Comment by dynelson** [comment]
Nope, never did.  Had to move on.  If you’re interested in a working alternative to NbGrader, let me know and we discuss what I ended up using.
