### ISSUE TITLE
Give helpful error message when installing to a non-existent profile

### ISSUE THREAD

**Issue by jhamrick** [jupyter/nbgrader#186]
If you are installing the nbextension to a profile that doesn't exist, you'll get a nasty error like this:

```
$ python -m nbgrader --install --activate foo
symlink /usr/local/share/jupyter/nbextensions/nbgrader -> /Users/jhamrick/project/tools/nbgrader/nbgrader/nbextensions/nbgrader
Traceback (most recent call last):
  File "/usr/local/Cellar/python3/3.4.2_1/Frameworks/Python.framework/Versions/3.4/lib/python3.4/runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/Cellar/python3/3.4.2_1/Frameworks/Python.framework/Versions/3.4/lib/python3.4/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/jhamrick/project/tools/nbgrader/nbgrader/__main__.py", line 2, in <module>
    main()
  File "/Users/jhamrick/project/tools/nbgrader/nbgrader/install.py", line 178, in main
    profile=args.profile)
  File "/Users/jhamrick/project/tools/nbgrader/nbgrader/install.py", line 57, in activate
    pdir = _get_profile_dir(profile, ipython_dir)
  File "/Users/jhamrick/project/tools/nbgrader/nbgrader/install.py", line 21, in _get_profile_dir
    pdir = ProfileDir.find_profile_dir_by_name(get_ipython_dir(), profile).location
  File "/Users/jhamrick/project/tools/ipython/IPython/core/profiledir.py", line 232, in find_profile_dir_by_name
    raise ProfileDirError('Profile directory not found in paths: %s' % dirname)
IPython.core.profiledir.ProfileDirError: Profile directory not found in paths: profile_foo
```

Something nicer would be to catch this error, and print out a helpful message, like this:

```
The 'foo' profile does not exist yet. To install nbgrader into this profile, you must create it first:

    ipython profile create foo
```

**Comment by jhamrick** [comment]
Closing as no longer an issue.
