### ISSUE TITLE
Import error for requests on user installation

### ISSUE THREAD

**Issue by willingc** [jupyter/nbgrader#388]
@jhamrick I was testing the user installation instructions (those in repo readme). When executing `nbgrader extension install`, I get an import error that there is no module for 'requests'. Missing dependency? Or my config error?

**Comment by Carreau** [comment]
FYI here is the traceback:

```
Traceback (most recent call last):
  File "/Users/bussonniermatthias/anaconda3/envs/3.4/bin/nbgrader", line 7, in <module>
    from nbgrader.apps.nbgraderapp import main
  File "/Users/bussonniermatthias/anaconda3/envs/3.4/lib/python3.4/site-packages/nbgrader/apps/__init__.py", line 6, in <module>
    from .formgradeapp import FormgradeApp
  File "/Users/bussonniermatthias/anaconda3/envs/3.4/lib/python3.4/site-packages/nbgrader/apps/formgradeapp.py", line 14, in <module>
    from nbgrader.auth import BaseAuth, NoAuth
  File "/Users/bussonniermatthias/anaconda3/envs/3.4/lib/python3.4/site-packages/nbgrader/auth/__init__.py", line 2, in <module>
    from .hubauth import HubAuth
  File "/Users/bussonniermatthias/anaconda3/envs/3.4/lib/python3.4/site-packages/nbgrader/auth/hubauth.py", line 2, in <module>
    import requests
ImportError: No module named 'requests'
```

I'll send a PR that add requests.

**Comment by willingc** [comment]
@Carreau Thanks :)

**Comment by willingc** [comment]
Closing this issue after merge of #389
