### ISSUE TITLE
`nbgrader extension activate assignment_list` failing

### ISSUE THREAD

**Issue by davis68** [jupyter/nbgrader#438]
We've had a weekold deployment of nbgrader working perfectly, but this afternoon it suddenly stopped.  The error that is arising is a ValueError from reading a JSON on the activate command:

<pre><code>
$ nbgrader extension activate assignment_list --ExtensionApp.log_level='DEBUG'
[ExtensionActivateApp | WARNING] Unrecognized JSON config file version, assuming version 1
[ExtensionActivateApp | WARNING] Unrecognized JSON config file version, assuming version 1
[ExtensionActivateApp | INFO] Activating assignment_list server extension
[ExtensionActivateApp | WARNING] Unrecognized JSON config file version, assuming version 1
[ExtensionActivateApp | INFO] Activating assignment_list nbextension
Traceback (most recent call last):
  File "/class/cs101/etc/venv/cs101-sp16/bin/nbgrader", line 11, in <module>
    sys.exit(main())
 File "/class/cs101/etc/venv/cs101-sp16/lib/python3.4/site-packages/nbgrader/apps/nbgraderapp.py", line 232, in main
    NbGraderApp.launch_instance()
  File "/class/cs101/etc/venv/cs101-sp16/lib/python3.4/site-packages/jupyter_core/application.py", line 267, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/class/cs101/etc/venv/cs101-sp16/lib/python3.4/site-packages/traitlets/config/application.py", line 589, in launch_instance
    app.start()
  File "/class/cs101/etc/venv/cs101-sp16/lib/python3.4/site-packages/nbgrader/apps/nbgraderapp.py", line 225, in start
    super(NbGraderApp, self).start()
  File "/class/cs101/etc/venv/cs101-sp16/lib/python3.4/site-packages/jupyter_core/application.py", line 256, in start
    self.subapp.start()
  File "/class/cs101/etc/venv/cs101-sp16/lib/python3.4/site-packages/nbgrader/apps/extensionapp.py", line 207, in start
    super(ExtensionApp, self).start()
  File "/class/cs101/etc/venv/cs101-sp16/lib/python3.4/site-packages/traitlets/config/application.py", line 276, in start
    return self.subapp.start()
  File "/class/cs101/etc/venv/cs101-sp16/lib/python3.4/site-packages/nbgrader/apps/extensionapp.py", line 107, in start
    self.enable_nbextension("assignment_list/main")
  File "/class/cs101/etc/venv/cs101-sp16/lib/python3.4/site-packages/notebook/nbextensions.py", line 347, in enable_nbextension
    cm.update(self.section, {"load_extensions": {name: True}})
  File "/class/cs101/etc/venv/cs101-sp16/lib/python3.4/site-packages/traitlets/config/manager.py", line 85, in update
    data = self.get(section_name)
  File "/class/cs101/etc/venv/cs101-sp16/lib/python3.4/site-packages/traitlets/config/manager.py", line 63, in get
    return json.load(f)
  File "/software/python3-3.4.1/lib/python3.4/json/__init__.py", line 268, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/software/python3-3.4.1/lib/python3.4/json/__init__.py", line 318, in loads
    return _default_decoder.decode(s)
  File "/software/python3-3.4.1/lib/python3.4/json/decoder.py", line 343, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/software/python3-3.4.1/lib/python3.4/json/decoder.py", line 361, in raw_decode
    raise ValueError(errmsg("Expecting value", s, err.value)) from None
ValueError: Expecting value: line 1 column 1 (char 0)
</code></pre>

We are using a Py3 venv, and the corresponding `jupyter_notebook_config.json` is:

<pre><code>
{
  "NotebookApp": {
    "server_extensions": [
      "nbgrader.nbextensions.assignment_list"
    ]
  }
}
</code></pre>

To my knowledge, nothing changed in our setup from one hour to the next.  I can still use the command line `nbgrader collect`, etc. without any problem.  Any idea what's breaking down now?

**Comment by davis68** [comment]
(The ExtensionActivateApp warnings have always been present for us.)

**Comment by davis68** [comment]
The `nbgrader_config.py` reads:

`
c = get_config()
c.NbGrader.course_id = "cs101-sp16"
c.TransferApp.exchange_directory = '/class/cs101/tmp/exchange'
`

**Comment by davis68** [comment]
`.../jupyter/nbconfig/notebook.json` reads:

<pre><code>
{
  "load_extensions": {
    "create_assignment/main": true
  }
}
</code></pre>

**Comment by jhamrick** [comment]
What is in `~/.jupyter/nbconfig/tree.json`?

**Comment by davis68** [comment]
<pre><code>
{
  "load_extensions": {
    "assignment_list/main": true
  }
}
</code></pre>

**Comment by davis68** [comment]
I've narrowed down whatever's happening to line 107 of extensionapp.py:

`self.enable_nbextension("assignment_list/main")`

is failing.

**Comment by davis68** [comment]
BUT:  `/class/cs101/etc/venv/cs101-sp16/etc/jupyter/nbconfig/tree.json` is EMPTY.  I just copied the same contents into it, and things are working.

**Comment by davis68** [comment]
So—no idea how things *broke* (i.e., how tree.json for the sitewide install got wiped over the lunch hour), but now I know *what* happened.

**Comment by davis68** [comment]
To recap:  somehow the tree.json file was wiped (644 perms), and this led to a JSON parsing error in `enable_nbextension`.

**Comment by jhamrick** [comment]
Yeah, that's weird -- not sure how that could have happened! Glad you were able to fix it, though!

**Comment by davis68** [comment]
Incidentally, I've a guess at what likely happened.  Since the JSON has to be writable (even though Jupyter doesn't change it almost ever), it got clobbered when two students hit at the same time.  The danger of sharing the config rather than farming it out to home directories—I may fix that in the future.
