### ISSUE TITLE
Latex to PDF output gives cryptic error

### ISSUE THREAD

**Issue by dsblank** [jupyter/nbgrader#440]
I'm trying to get PDF output from `feedback` option. I've changed the default type to `pdf` but am getting this LaTeX error. 

How can I get the notebook.log to see the actual error? Any clues? Regular PDF production (eg, Download as PDF works).

```shell
$ nbgrader feedback biocs115-assignment01 --force --debug
[FeedbackApp | DEBUG] Config changed:
[FeedbackApp | DEBUG] {'FeedbackApp': {'force': True}, 'HTMLExporter': {'template_path': ['.', '/opt/anaconda3/lib/python3.5/site-packages/nbgrader/html/templates'], 'template_file': 'feedback'}, 'Exporter': {'default_preprocessors': [<class 'nbgrader.preprocessors.getgrades.GetGrades'>, <class 'nbconvert.preprocessors.csshtmlheader.CSSHTMLHeaderPreprocessor'>]}, 'Application': {'log_level': 'DEBUG'}}
[FeedbackApp | DEBUG] Searching ['/home/dblank/nbgrader/biocs115', '/home/dblank/.jupyter', '/opt/anaconda3/etc/jupyter', '/usr/local/etc/jupyter', '/etc/jupyter'] for config files
[FeedbackApp | DEBUG] Looking for jupyter_config in /etc/jupyter
[FeedbackApp | DEBUG] Looking for jupyter_config in /usr/local/etc/jupyter
[FeedbackApp | DEBUG] Looking for jupyter_config in /opt/anaconda3/etc/jupyter
[FeedbackApp | DEBUG] Looking for jupyter_config in /home/dblank/.jupyter
[FeedbackApp | DEBUG] Looking for jupyter_config in /home/dblank/nbgrader/biocs115
[FeedbackApp | DEBUG] Looking for nbgrader_config in /etc/jupyter
[FeedbackApp | DEBUG] Looking for nbgrader_config in /usr/local/etc/jupyter
[FeedbackApp | DEBUG] Looking for nbgrader_config in /opt/anaconda3/etc/jupyter
[FeedbackApp | DEBUG] Loaded config file: /opt/anaconda3/etc/jupyter/nbgrader_config.py
[FeedbackApp | DEBUG] Config changed:
[FeedbackApp | DEBUG] {'NbGrader': {'course_id': 'biocs115'}, 'Exporter': {'default_preprocessors': [<class 'nbgrader.preprocessors.getgrades.GetGrades'>, <class 'nbconvert.preprocessors.csshtmlheader.CSSHTMLHeaderPreprocessor'>]}, 'Application': {'log_level': 'DEBUG'}, 'HTMLExporter': {'template_path': ['.', '/opt/anaconda3/lib/python3.5/site-packages/nbgrader/html/templates'], 'template_file': 'feedback'}, 'FormgradeApp': {'authenticator_class': 'nbgrader.auth.hubauth.HubAuth', 'port': 9000, 'ip': '127.0.0.1'}, 'FeedbackApp': {'force': True}, 'HubAuth': {'hub_db': '/root/jupyterhub.sqlite', 'notebook_url_prefix': '/jupyter/biocs115', 'generate_hubapi_token': True, 'hub_address': '127.0.0.1', 'graders': ['dblank', 'mmatlin', 'josh']}, 'TransferApp': {'exchange_directory': '/opt/nbgrader/exchange'}, 'ListApp': {'exchange_directory': '/opt/nbgrader/exchange'}}
[FeedbackApp | DEBUG] Config changed:
[FeedbackApp | DEBUG] {'NbGrader': {'course_id': 'biocs115'}, 'Exporter': {'default_preprocessors': [<class 'nbgrader.preprocessors.getgrades.GetGrades'>, <class 'nbconvert.preprocessors.csshtmlheader.CSSHTMLHeaderPreprocessor'>]}, 'Application': {'log_level': 'DEBUG'}, 'HTMLExporter': {'template_path': ['.', '/opt/anaconda3/lib/python3.5/site-packages/nbgrader/html/templates'], 'template_file': 'feedback'}, 'FormgradeApp': {'authenticator_class': 'nbgrader.auth.hubauth.HubAuth', 'port': 9000, 'ip': '127.0.0.1'}, 'FeedbackApp': {'force': True}, 'HubAuth': {'generate_hubapi_token': True, 'graders': ['dblank', 'mmatlin', 'josh'], 'hub_db': '/root/jupyterhub.sqlite', 'notebook_url_prefix': '/jupyter/biocs115', 'hub_address': '127.0.0.1'}, 'TransferApp': {'exchange_directory': '/opt/nbgrader/exchange'}, 'ListApp': {'exchange_directory': '/opt/nbgrader/exchange'}}
[FeedbackApp | DEBUG] Looking for nbgrader_config in /home/dblank/.jupyter
[FeedbackApp | DEBUG] Looking for nbgrader_config in /home/dblank/nbgrader/biocs115
[FeedbackApp | DEBUG] Loaded config file: /home/dblank/nbgrader/biocs115/nbgrader_config.py
[FeedbackApp | DEBUG] Config changed:
[FeedbackApp | DEBUG] {'NbGrader': {'course_id': 'biocs115'}, 'Exporter': {'default_preprocessors': [<class 'nbgrader.preprocessors.getgrades.GetGrades'>, <class 'nbconvert.preprocessors.csshtmlheader.CSSHTMLHeaderPreprocessor'>]}, 'Application': {'log_level': 'DEBUG'}, 'HTMLExporter': {'template_path': ['.', '/opt/anaconda3/lib/python3.5/site-packages/nbgrader/html/templates'], 'template_file': 'feedback'}, 'FormgradeApp': {'authenticator_class': 'nbgrader.auth.hubauth.HubAuth', 'port': 9000, 'ip': '127.0.0.1'}, 'FeedbackApp': {'force': True}, 'HubAuth': {'generate_hubapi_token': True, 'graders': ['dblank', 'mmatlin', 'josh'], 'hub_db': '/root/jupyterhub.sqlite', 'notebook_url_prefix': '/jupyter/biocs115', 'hub_address': '127.0.0.1'}, 'TransferApp': {'exchange_directory': '/opt/nbgrader/exchange/'}, 'ListApp': {'exchange_directory': '/opt/nbgrader/exchange'}}
[FeedbackApp | DEBUG] Config changed:
[FeedbackApp | DEBUG] {'NbGrader': {'course_id': 'biocs115'}, 'Exporter': {'default_preprocessors': [<class 'nbgrader.preprocessors.getgrades.GetGrades'>, <class 'nbconvert.preprocessors.csshtmlheader.CSSHTMLHeaderPreprocessor'>]}, 'Application': {'log_level': 'DEBUG'}, 'HTMLExporter': {'template_path': ['.', '/opt/anaconda3/lib/python3.5/site-packages/nbgrader/html/templates'], 'template_file': 'feedback'}, 'FormgradeApp': {'authenticator_class': 'nbgrader.auth.hubauth.HubAuth', 'port': 9000, 'ip': '127.0.0.1'}, 'FeedbackApp': {'force': True}, 'HubAuth': {'generate_hubapi_token': True, 'graders': ['dblank', 'mmatlin', 'josh'], 'hub_db': '/root/jupyterhub.sqlite', 'notebook_url_prefix': '/jupyter/biocs115', 'hub_address': '127.0.0.1'}, 'TransferApp': {'exchange_directory': '/opt/nbgrader/exchange/'}, 'ListApp': {'exchange_directory': '/opt/nbgrader/exchange'}}
[FeedbackApp | DEBUG] Config changed:
[FeedbackApp | DEBUG] {'NbGrader': {'course_id': 'biocs115'}, 'Exporter': {'default_preprocessors': [<class 'nbgrader.preprocessors.getgrades.GetGrades'>, <class 'nbconvert.preprocessors.csshtmlheader.CSSHTMLHeaderPreprocessor'>]}, 'Application': {'log_level': 'DEBUG'}, 'HTMLExporter': {'template_path': ['.', '/opt/anaconda3/lib/python3.5/site-packages/nbgrader/html/templates'], 'template_file': 'feedback'}, 'FormgradeApp': {'authenticator_class': 'nbgrader.auth.hubauth.HubAuth', 'port': 9000, 'ip': '127.0.0.1'}, 'FeedbackApp': {'force': True}, 'HubAuth': {'generate_hubapi_token': True, 'graders': ['dblank', 'mmatlin', 'josh'], 'hub_db': '/root/jupyterhub.sqlite', 'notebook_url_prefix': '/jupyter/biocs115', 'hub_address': '127.0.0.1'}, 'TransferApp': {'exchange_directory': '/opt/nbgrader/exchange/'}, 'ListApp': {'exchange_directory': '/opt/nbgrader/exchange'}}
[FeedbackApp | INFO] Copying autograded/aekerdt/biocs115-assignment01/timestamp.txt -> feedback/aekerdt/biocs115-assignment01/timestamp.txt
[FeedbackApp | INFO] Converting notebook autograded/aekerdt/biocs115-assignment01/Instructions.ipynb to pdf
[FeedbackApp | DEBUG] Student: aekerdt
[FeedbackApp | DEBUG] Assignment: biocs115-assignment01
[FeedbackApp | DEBUG] Notebook: Instructions
[FeedbackApp | DEBUG] Applying preprocessor: GetGrades
[FeedbackApp | DEBUG] Attempting to load template article.tplx
[FeedbackApp | DEBUG] Loaded template article.tplx
[FeedbackApp | DEBUG] Attempting to load template article.tplx
[FeedbackApp | DEBUG] Loaded template article.tplx
[FeedbackApp | INFO] Writing 14118 bytes to notebook.tex
[FeedbackApp | INFO] Building PDF
[FeedbackApp | INFO] Running pdflatex 3 times: ['pdflatex', 'notebook.tex']
[FeedbackApp | CRITICAL] pdflatex failed: ['pdflatex', 'notebook.tex']
    This is pdfTeXk, Version 3.141592-1.40.3 (Web2C 7.5.6)
     %&-line parsing enabled.
    entering extended mode
    (./notebook.tex
    LaTeX2e <2005/12/01>
    Babel <v3.8h> and hyphenation patterns for english, usenglishmax, dumylang, noh
    yphenation, arabic, basque, bulgarian, coptic, welsh, czech, slovak, german, ng
    erman, danish, esperanto, spanish, catalan, galician, estonian, farsi, finnish,
     french, greek, monogreek, ancientgreek, croatian, hungarian, interlingua, ibyc
    us, indonesian, icelandic, italian, latin, mongolian, dutch, norsk, polish, por
    tuguese, pinyin, romanian, russian, slovenian, uppersorbian, serbian, swedish, 
    turkish, ukenglish, ukrainian, loaded.
    (/var/lib/texmf/tex/latex/base/article.cls
    Document Class: article 2014/09/29 v1.4h Standard LaTeX document class
    (/var/lib/texmf/tex/latex/base/size10.clo))
    (/var/lib/texmf/tex/latex/graphics/graphicx.sty
    (/var/lib/texmf/tex/latex/graphics/keyval.sty)
    (/var/lib/texmf/tex/latex/graphics/graphics.sty
    (/var/lib/texmf/tex/latex/graphics/trig.sty)
    (/var/lib/texmf/tex/latex/latexconfig/graphics.cfg)
    (/var/lib/texmf/tex/latex/pdftex-def/pdftex.def
    (/var/lib/texmf/tex/generic/oberdiek/infwarerr.sty)
    (/var/lib/texmf/tex/generic/oberdiek/ltxcmds.sty))))
    (/var/lib/texmf/tex/latex/adjustbox/adjustbox.sty
    (/var/lib/texmf/tex/latex/xkeyval/xkeyval.sty
    (/usr/share/texmf/tex/latex/xkeyval/xkeyval.tex))
    (/var/lib/texmf/tex/latex/adjustbox/adjcalc.sty)
    (/var/lib/texmf/tex/latex/adjustbox/trimclip.sty
    (/var/lib/texmf/tex/latex/collectbox/collectbox.sty)
    (/var/lib/texmf/tex/latex/adjustbox/tc-pdftex.def))
    (/var/lib/texmf/tex/latex/ifoddpage/ifoddpage.sty)
    (/var/lib/texmf/tex/latex/varwidth/varwidth.sty))
    (/var/lib/texmf/tex/latex/graphics/color.sty
    (/var/lib/texmf/tex/latex/latexconfig/color.cfg))
    (/var/lib/texmf/tex/latex/tools/enumerate.sty)
    (/var/lib/texmf/tex/latex/geometry/geometry.sty
    (/var/lib/texmf/tex/generic/oberdiek/ifpdf.sty)
    (/var/lib/texmf/tex/generic/oberdiek/ifvtex.sty)
    (/var/lib/texmf/tex/generic/ifxetex/ifxetex.sty))
    (/var/lib/texmf/tex/latex/amsmath/amsmath.sty
    For additional information on amsmath, use the `?' option.
    (/var/lib/texmf/tex/latex/amsmath/amstext.sty
    (/var/lib/texmf/tex/latex/amsmath/amsgen.sty))
    (/var/lib/texmf/tex/latex/amsmath/amsbsy.sty)
    (/var/lib/texmf/tex/latex/amsmath/amsopn.sty))
    (/var/lib/texmf/tex/latex/amsfonts/amssymb.sty
    (/var/lib/texmf/tex/latex/amsfonts/amsfonts.sty))
    (/var/lib/texmf/tex/latex/eurosym/eurosym.sty)
    (/var/lib/texmf/tex/latex/ucs/ucs.sty
    (/var/lib/texmf/tex/latex/ucs/data/uni-global.def))
    (/var/lib/texmf/tex/latex/base/inputenc.sty
    (/var/lib/texmf/tex/latex/ucs/utf8x.def))
    (/var/lib/texmf/tex/latex/fancyvrb/fancyvrb.sty
    Style option: `fancyvrb' v2.7a, with DG/SPQR fixes, and firstline=lastline fix 
    <2008/02/07> (tvz)) (/var/lib/texmf/tex/latex/oberdiek/grffile.sty
    (/var/lib/texmf/tex/latex/oberdiek/kvoptions.sty
    (/var/lib/texmf/tex/generic/oberdiek/kvsetkeys.sty
    (/var/lib/texmf/tex/generic/oberdiek/etexcmds.sty
    (/var/lib/texmf/tex/generic/oberdiek/ifluatex.sty))))
    (/var/lib/texmf/tex/generic/oberdiek/pdftexcmds.sty))
    (/var/lib/texmf/tex/latex/hyperref/hyperref.sty
    (/var/lib/texmf/tex/generic/oberdiek/hobsub-hyperref.sty
    (/var/lib/texmf/tex/generic/oberdiek/hobsub-generic.sty))
    (/var/lib/texmf/tex/latex/oberdiek/auxhook.sty)
    (/var/lib/texmf/tex/latex/hyperref/pd1enc.def)
    (/var/lib/texmf/tex/latex/latexconfig/hyperref.cfg)
    (/var/lib/texmf/tex/latex/url/url.sty))
    
    Package hyperref Message: Driver (autodetected): hpdftex.
    
    (/var/lib/texmf/tex/latex/hyperref/hpdftex.def
    (/var/lib/texmf/tex/latex/oberdiek/rerunfilecheck.sty))
    (/var/lib/texmf/tex/latex/tools/longtable.sty)
    (/var/lib/texmf/tex/latex/booktabs/booktabs.sty)
    (/usr/share/texmf/tex/latex/ltxmisc/ulem.sty)
    No file notebook.aux.
    (/var/lib/texmf/tex/context/base/supp-pdf.mkii
    [Loading MPS to PDF converter (version 2006.09.02).]
    )
    *geometry* driver: auto-detecting
    *geometry* detected driver: pdftex
    
    Package geometry Warning: The marginal notes overrun the paper.
         Add 3.73001pt and more to the right margin.
    
    *geometry* verbose mode - [ preamble ] result:
    * driver: pdftex
    * paper: <default>
    * layout: <same size as paper>
    * layoutoffset:(h,v)=(0.0pt,0.0pt)
    * modes: 
    * h-part:(L,W,R)=(72.26999pt, 469.75502pt, 72.26999pt)
    * v-part:(T,H,B)=(72.26999pt, 650.43001pt, 72.26999pt)
    * \paperwidth=614.295pt
    * \paperheight=794.96999pt
    * \textwidth=469.75502pt
    * \textheight=650.43001pt
    * \oddsidemargin=0.0pt
    * \evensidemargin=0.0pt
    * \topmargin=-37.0pt
    * \headheight=12.0pt
    * \headsep=25.0pt
    * \topskip=10.0pt
    * \footskip=30.0pt
    * \marginparwidth=65.0pt
    * \marginparsep=11.0pt
    * \columnsep=10.0pt
    * \skip\footins=9.0pt plus 4.0pt minus 2.0pt
    * \hoffset=0.0pt
    * \voffset=0.0pt
    * \mag=1000
    * \@twocolumnfalse
    * \@twosidefalse
    * \@mparswitchfalse
    * \@reversemarginfalse
    * (1in=72.27pt=25.4mm, 1cm=28.453pt)
    
    (/var/lib/texmf/tex/latex/ucs/ucsencs.def)
    (/var/lib/texmf/tex/latex/hyperref/nameref.sty
    (/var/lib/texmf/tex/generic/oberdiek/gettitlestring.sty))
    (/var/lib/texmf/tex/latex/amsfonts/umsa.fd)
    (/var/lib/texmf/tex/latex/amsfonts/umsb.fd)
    
    LaTeX Warning: No \author given.
    
    (/var/lib/texmf/tex/latex/base/omscmr.fd) [1{/var/lib/texmf/fonts/map/pdftex/up
    dmap/pdftex.map}] [2]
    ! Undefined control sequence.
    <argument> ...olor}In [{\color {incolor}4}]:} \PY 
                                                      {o}{\PYZpc {}\PYZpc {}}\PY...
    l.434 ...PY{o}{\PYZpc{}\PYZpc{}}\PY{k}{simulation}
                                                      
    ? 
    ! Emergency stop.
    <argument> ...olor}In [{\color {incolor}4}]:} \PY 
                                                      {o}{\PYZpc {}\PYZpc {}}\PY...
    l.434 ...PY{o}{\PYZpc{}\PYZpc{}}\PY{k}{simulation}
                                                      
    !  ==> Fatal error occurred, no output PDF file produced!
    Transcript written on notebook.log.
    
[FeedbackApp | INFO] Running bibtex 1 time: ['bibtex', 'notebook']
[FeedbackApp | WARNING] bibtex had problems, most likely because there were no citations
[FeedbackApp | DEBUG] bibtex output: ['bibtex', 'notebook']
    This is BibTeX, Version 0.99c (Web2C 7.5.6)
    The top-level auxiliary file: notebook.aux
    I found no \citation commands---while reading file notebook.aux
    I found no \bibdata command---while reading file notebook.aux
    I found no \bibstyle command---while reading file notebook.aux
    (There were 3 error messages)
    
[FeedbackApp | INFO] Running pdflatex 3 times: ['pdflatex', 'notebook.tex']
[FeedbackApp | CRITICAL] pdflatex failed: ['pdflatex', 'notebook.tex']
    This is pdfTeXk, Version 3.141592-1.40.3 (Web2C 7.5.6)
     %&-line parsing enabled.
    entering extended mode
    (./notebook.tex
    LaTeX2e <2005/12/01>
    Babel <v3.8h> and hyphenation patterns for english, usenglishmax, dumylang, noh
    yphenation, arabic, basque, bulgarian, coptic, welsh, czech, slovak, german, ng
    erman, danish, esperanto, spanish, catalan, galician, estonian, farsi, finnish,
     french, greek, monogreek, ancientgreek, croatian, hungarian, interlingua, ibyc
    us, indonesian, icelandic, italian, latin, mongolian, dutch, norsk, polish, por
    tuguese, pinyin, romanian, russian, slovenian, uppersorbian, serbian, swedish, 
    turkish, ukenglish, ukrainian, loaded.
    (/var/lib/texmf/tex/latex/base/article.cls
    Document Class: article 2014/09/29 v1.4h Standard LaTeX document class
    (/var/lib/texmf/tex/latex/base/size10.clo))
    (/var/lib/texmf/tex/latex/graphics/graphicx.sty
    (/var/lib/texmf/tex/latex/graphics/keyval.sty)
    (/var/lib/texmf/tex/latex/graphics/graphics.sty
    (/var/lib/texmf/tex/latex/graphics/trig.sty)
    (/var/lib/texmf/tex/latex/latexconfig/graphics.cfg)
    (/var/lib/texmf/tex/latex/pdftex-def/pdftex.def
    (/var/lib/texmf/tex/generic/oberdiek/infwarerr.sty)
    (/var/lib/texmf/tex/generic/oberdiek/ltxcmds.sty))))
    (/var/lib/texmf/tex/latex/adjustbox/adjustbox.sty
    (/var/lib/texmf/tex/latex/xkeyval/xkeyval.sty
    (/usr/share/texmf/tex/latex/xkeyval/xkeyval.tex))
    (/var/lib/texmf/tex/latex/adjustbox/adjcalc.sty)
    (/var/lib/texmf/tex/latex/adjustbox/trimclip.sty
    (/var/lib/texmf/tex/latex/collectbox/collectbox.sty)
    (/var/lib/texmf/tex/latex/adjustbox/tc-pdftex.def))
    (/var/lib/texmf/tex/latex/ifoddpage/ifoddpage.sty)
    (/var/lib/texmf/tex/latex/varwidth/varwidth.sty))
    (/var/lib/texmf/tex/latex/graphics/color.sty
    (/var/lib/texmf/tex/latex/latexconfig/color.cfg))
    (/var/lib/texmf/tex/latex/tools/enumerate.sty)
    (/var/lib/texmf/tex/latex/geometry/geometry.sty
    (/var/lib/texmf/tex/generic/oberdiek/ifpdf.sty)
    (/var/lib/texmf/tex/generic/oberdiek/ifvtex.sty)
    (/var/lib/texmf/tex/generic/ifxetex/ifxetex.sty))
    (/var/lib/texmf/tex/latex/amsmath/amsmath.sty
    For additional information on amsmath, use the `?' option.
    (/var/lib/texmf/tex/latex/amsmath/amstext.sty
    (/var/lib/texmf/tex/latex/amsmath/amsgen.sty))
    (/var/lib/texmf/tex/latex/amsmath/amsbsy.sty)
    (/var/lib/texmf/tex/latex/amsmath/amsopn.sty))
    (/var/lib/texmf/tex/latex/amsfonts/amssymb.sty
    (/var/lib/texmf/tex/latex/amsfonts/amsfonts.sty))
    (/var/lib/texmf/tex/latex/eurosym/eurosym.sty)
    (/var/lib/texmf/tex/latex/ucs/ucs.sty
    (/var/lib/texmf/tex/latex/ucs/data/uni-global.def))
    (/var/lib/texmf/tex/latex/base/inputenc.sty
    (/var/lib/texmf/tex/latex/ucs/utf8x.def))
    (/var/lib/texmf/tex/latex/fancyvrb/fancyvrb.sty
    Style option: `fancyvrb' v2.7a, with DG/SPQR fixes, and firstline=lastline fix 
    <2008/02/07> (tvz)) (/var/lib/texmf/tex/latex/oberdiek/grffile.sty
    (/var/lib/texmf/tex/latex/oberdiek/kvoptions.sty
    (/var/lib/texmf/tex/generic/oberdiek/kvsetkeys.sty
    (/var/lib/texmf/tex/generic/oberdiek/etexcmds.sty
    (/var/lib/texmf/tex/generic/oberdiek/ifluatex.sty))))
    (/var/lib/texmf/tex/generic/oberdiek/pdftexcmds.sty))
    (/var/lib/texmf/tex/latex/hyperref/hyperref.sty
    (/var/lib/texmf/tex/generic/oberdiek/hobsub-hyperref.sty
    (/var/lib/texmf/tex/generic/oberdiek/hobsub-generic.sty))
    (/var/lib/texmf/tex/latex/oberdiek/auxhook.sty)
    (/var/lib/texmf/tex/latex/hyperref/pd1enc.def)
    (/var/lib/texmf/tex/latex/latexconfig/hyperref.cfg)
    (/var/lib/texmf/tex/latex/url/url.sty))
    
    Package hyperref Message: Driver (autodetected): hpdftex.
    
    (/var/lib/texmf/tex/latex/hyperref/hpdftex.def
    (/var/lib/texmf/tex/latex/oberdiek/rerunfilecheck.sty))
    (/var/lib/texmf/tex/latex/tools/longtable.sty)
    (/var/lib/texmf/tex/latex/booktabs/booktabs.sty)
    (/usr/share/texmf/tex/latex/ltxmisc/ulem.sty) (./notebook.aux)
    (/var/lib/texmf/tex/context/base/supp-pdf.mkii
    [Loading MPS to PDF converter (version 2006.09.02).]
    )
    *geometry* driver: auto-detecting
    *geometry* detected driver: pdftex
    
    Package geometry Warning: The marginal notes overrun the paper.
         Add 3.73001pt and more to the right margin.
    
    *geometry* verbose mode - [ preamble ] result:
    * driver: pdftex
    * paper: <default>
    * layout: <same size as paper>
    * layoutoffset:(h,v)=(0.0pt,0.0pt)
    * modes: 
    * h-part:(L,W,R)=(72.26999pt, 469.75502pt, 72.26999pt)
    * v-part:(T,H,B)=(72.26999pt, 650.43001pt, 72.26999pt)
    * \paperwidth=614.295pt
    * \paperheight=794.96999pt
    * \textwidth=469.75502pt
    * \textheight=650.43001pt
    * \oddsidemargin=0.0pt
    * \evensidemargin=0.0pt
    * \topmargin=-37.0pt
    * \headheight=12.0pt
    * \headsep=25.0pt
    * \topskip=10.0pt
    * \footskip=30.0pt
    * \marginparwidth=65.0pt
    * \marginparsep=11.0pt
    * \columnsep=10.0pt
    * \skip\footins=9.0pt plus 4.0pt minus 2.0pt
    * \hoffset=0.0pt
    * \voffset=0.0pt
    * \mag=1000
    * \@twocolumnfalse
    * \@twosidefalse
    * \@mparswitchfalse
    * \@reversemarginfalse
    * (1in=72.27pt=25.4mm, 1cm=28.453pt)
    
    (/var/lib/texmf/tex/latex/ucs/ucsencs.def)
    (/var/lib/texmf/tex/latex/hyperref/nameref.sty
    (/var/lib/texmf/tex/generic/oberdiek/gettitlestring.sty)) (./notebook.out)
    (./notebook.out) (/var/lib/texmf/tex/latex/amsfonts/umsa.fd)
    (/var/lib/texmf/tex/latex/amsfonts/umsb.fd)
    
    LaTeX Warning: No \author given.
    
    (/var/lib/texmf/tex/latex/base/omscmr.fd) [1{/var/lib/texmf/fonts/map/pdftex/up
    dmap/pdftex.map}] [2]
    ! Undefined control sequence.
    <argument> ...olor}In [{\color {incolor}4}]:} \PY 
                                                      {o}{\PYZpc {}\PYZpc {}}\PY...
    l.434 ...PY{o}{\PYZpc{}\PYZpc{}}\PY{k}{simulation}
                                                      
    ? 
    ! Emergency stop.
    <argument> ...olor}In [{\color {incolor}4}]:} \PY 
                                                      {o}{\PYZpc {}\PYZpc {}}\PY...
    l.434 ...PY{o}{\PYZpc{}\PYZpc{}}\PY{k}{simulation}
                                                      
    !  ==> Fatal error occurred, no output PDF file produced!
    Transcript written on notebook.log.
    
[FeedbackApp | ERROR] There was an error processing assignment: autograded/aekerdt/biocs115-assignment01
[FeedbackApp | WARNING] Removing failed assignment: feedback/aekerdt/biocs115-assignment01
Traceback (most recent call last):
  File "/opt/anaconda3/bin/nbgrader", line 11, in <module>
    sys.exit(main())
  File "/opt/anaconda3/lib/python3.5/site-packages/nbgrader/apps/nbgraderapp.py", line 232, in main
    NbGraderApp.launch_instance()
  File "/opt/anaconda3/lib/python3.5/site-packages/jupyter_core/application.py", line 267, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/opt/anaconda3/lib/python3.5/site-packages/traitlets/config/application.py", line 589, in launch_instance
    app.start()
  File "/opt/anaconda3/lib/python3.5/site-packages/nbgrader/apps/nbgraderapp.py", line 225, in start
    super(NbGraderApp, self).start()
  File "/opt/anaconda3/lib/python3.5/site-packages/jupyter_core/application.py", line 256, in start
    self.subapp.start()
  File "/opt/anaconda3/lib/python3.5/site-packages/nbconvert/nbconvertapp.py", line 289, in start
    self.convert_notebooks()
  File "/opt/anaconda3/lib/python3.5/site-packages/nbgrader/apps/baseapp.py", line 638, in convert_notebooks
    super(BaseNbConvertApp, self).convert_notebooks()
  File "/opt/anaconda3/lib/python3.5/site-packages/nbconvert/nbconvertapp.py", line 412, in convert_notebooks
    self.convert_single_notebook(notebook_filename)
  File "/opt/anaconda3/lib/python3.5/site-packages/nbconvert/nbconvertapp.py", line 383, in convert_single_notebook
    output, resources = self.export_single_notebook(notebook_filename, resources)
  File "/opt/anaconda3/lib/python3.5/site-packages/nbconvert/nbconvertapp.py", line 335, in export_single_notebook
    output, resources = self.exporter.from_filename(notebook_filename, resources=resources)
  File "/opt/anaconda3/lib/python3.5/site-packages/nbconvert/exporters/exporter.py", line 165, in from_filename
    return self.from_notebook_node(nbformat.read(f, as_version=4), resources=resources, **kw)
  File "/opt/anaconda3/lib/python3.5/site-packages/nbconvert/exporters/pdf.py", line 152, in from_notebook_node
    raise IOError("PDF creating failed")
```

**Comment by dsblank** [comment]
I've got two different installations (ubuntu 14.04 and old redhat) that give this same error.

**Comment by jhamrick** [comment]
I actually don't think that converting the feedback to pdf will work unless you are providing a custom template. The template that produces the html file is a custom one that is included with nbgrader, but I haven't written one for pdf. So what you'd get out otherwise is just a regular notebook converted to pdf -- it won't include any of the comments or grades.

I'm not sure why it would give you an error, though. One thing you could try would be to change the format to `.tex` and then compile the latex manually to see where the error is. It's possible that nbgrader is passing in some metadata that is getting included in the tex source that isn't valid.

**Comment by jhamrick** [comment]
Also, the way that I returned feedback to my students was to convert it to HTML and include a notebook (generated programmatically) with links to the HTML files. Then, I used the following script to copy the files to students home directories: https://gist.github.com/jhamrick/2ad63d7226b64c0a95fa

**Comment by dsblank** [comment]
Ah, a notebook with links... can you share that code?

**Comment by dsblank** [comment]
I'm just copying a notebook with some text, and the following code:

```python
from IPython.display import FileLinks
print("Contents of your Incoming folder:")
FileLinks(".")
```
That will work for now.

**Comment by jhamrick** [comment]
Huh, cool, I didn't actually know about FileLinks!

FYI, here's the code I used to build my notebooks: https://gist.github.com/jhamrick/506c0161af1393ae32cf It's a little specific to how we structured our class (e.g. including number of late days used -- which is the reason it's not in nbgrader proper) but that's the general idea.

**Comment by dsblank** [comment]
Thanks @jhamrick ! This was useful just to see what others are doing with the generated feedback.

I do think that a PDF output would simplify some of this for us, but I now see that it would take some work to make the templates.

**Comment by dsblank** [comment]
I'll close this, as it may never come up in real use.
