### ISSUE TITLE
AttributeError: 'ExtensionActivateApp' object has no attribute 'enable_nbextension'

### ISSUE THREAD

**Issue by magsol** [jupyter/nbgrader#497]
I'm attempting to perform a basic install of nbgrader (Python 3.5 via Anaconda, jupyter 4.1.0, nbgrader 0.2.2, Mac OS X 10.11.4), but it's failing on one of the first few steps.

```
$> pip install nbgrader
$> nbgrader extension install

Unrecognized JSON config file version, assuming version 1
Installing create_assignment extension
Up to date: /usr/local/share/jupyter/nbextensions/create_assignment/create_assignment.css
Up to date: /usr/local/share/jupyter/nbextensions/create_assignment/main.js

    To initialize this nbextension in the browser every time the notebook (or other app) loads:
    
          jupyter nbextension enable <the entry point>
    
Installing assignment_list extension
Up to date: /usr/local/share/jupyter/nbextensions/static/assignment_list.css
Up to date: /usr/local/share/jupyter/nbextensions/static/assignment_list.js
Up to date: /usr/local/share/jupyter/nbextensions/static/main.js

    To initialize this nbextension in the browser every time the notebook (or other app) loads:
    
          jupyter nbextension enable <the entry point>

$> nbgrader extension activate

Unrecognized JSON config file version, assuming version 1
Activating create_assignment nbextension
Traceback (most recent call last):
  File "/opt/python/bin/nbgrader", line 11, in <module>
    sys.exit(main())
  File "/opt/python/lib/python3.5/site-packages/nbgrader/apps/nbgraderapp.py", line 232, in main
    NbGraderApp.launch_instance()
  File "/opt/python/lib/python3.5/site-packages/jupyter_core/application.py", line 267, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/opt/python/lib/python3.5/site-packages/traitlets/config/application.py", line 596, in launch_instance
    app.start()
  File "/opt/python/lib/python3.5/site-packages/nbgrader/apps/nbgraderapp.py", line 225, in start
    super(NbGraderApp, self).start()
  File "/opt/python/lib/python3.5/site-packages/jupyter_core/application.py", line 256, in start
    self.subapp.start()
  File "/opt/python/lib/python3.5/site-packages/nbgrader/apps/extensionapp.py", line 207, in start
    super(ExtensionApp, self).start()
  File "/opt/python/lib/python3.5/site-packages/traitlets/config/application.py", line 279, in start
    return self.subapp.start()
  File "/opt/python/lib/python3.5/site-packages/nbgrader/apps/extensionapp.py", line 99, in start
    self.enable_nbextension("create_assignment/main")
AttributeError: 'ExtensionActivateApp' object has no attribute 'enable_nbextension'
```

Any pointers?

**Comment by jhamrick** [comment]
Yeah, this is due to the new version of the notebook that was just released. If you force it to be the notebook version 4.1 (rather than 4.2) then it should fix it, I believe. Note that the notebook version is separate from the jupyter version (so it's entirely possible to be on jupyter version 4.1 but notebook version 4.2!)

The next release of nbgrader (which should be coming out soon, just as soon as I fix the last few issues open) will support 4.2 so you won't need to worry about downgrading.

**Comment by magsol** [comment]
Super cool! Worked like a charm. Thank you very much!

Just FYI, I'm in the process of designing some courses around the [heavy!] use of `nbgrader`, so I may become a frequent visitor here over the next few months :) Please let me know if I should direct my general inquiries elsewhere besides polluting the issues tab with new tickets.

**Comment by jhamrick** [comment]
Fantastic, I'm really excited to hear that! And posting issues here is the perfect place for questions 👍
