### ISSUE TITLE
Installation issues

### ISSUE THREAD

**Issue by remram44** [jupyter/nbgrader#501]
```
(venv)vagrant@debian-83-amd64:~$ nbgrader extension install
Installing create_assignment extension
Traceback (most recent call last):
  ...
  File "/tmp/a/local/lib/python2.7/site-packages/ipython_genutils/path.py", line 167, in ensure_dir_exists
    os.makedirs(path, mode=mode)
  ...
OSError: [Errno 13] Permission denied: '/usr/local/share/jupyter'
```
Shouldn't this use the virtualenv (`/tmp/venv/share/jupyter`) instead of the global `/usr/local/share`? Is this a

```
(venv)vagrant@debian-83-amd64:~$ nbgrader extension install --user
Installing create_assignment extension
Making directory: /home/vagrant/.local/share/jupyter/nbextensions/create_assignment/
Copying: /tmp/a/local/lib/python2.7/site-packages/nbgrader/nbextensions/create_assignment/main.js -> /home/vagrant/.local/share/jupyter/nbextensions/create_assignment/main.js
Copying: /tmp/a/local/lib/python2.7/site-packages/nbgrader/nbextensions/create_assignment/create_assignment.css -> /home/vagrant/.local/share/jupyter/nbextensions/create_assignment/create_assignment.css

    To initialize this nbextension in the browser every time the notebook (or other app) loads:

          jupyter nbextension enable <the entry point> --user

Installing assignment_list extension
Making directory: /home/vagrant/.local/share/jupyter/nbextensions/static/
Copying: /tmp/a/local/lib/python2.7/site-packages/nbgrader/nbextensions/assignment_list/static/assignment_list.js -> /home/vagrant/.local/share/jupyter/nbextensions/static/assignment_list.js
Copying: /tmp/a/local/lib/python2.7/site-packages/nbgrader/nbextensions/assignment_list/static/main.js -> /home/vagrant/.local/share/jupyter/nbextensions/static/main.js
Copying: /tmp/a/local/lib/python2.7/site-packages/nbgrader/nbextensions/assignment_list/static/assignment_list.css -> /home/vagrant/.local/share/jupyter/nbextensions/static/assignment_list.css

    To initialize this nbextension in the browser every time the notebook (or other app) loads:

          jupyter nbextension enable <the entry point> --user
```
The `nbextensions/static/main.js` seems a good candidate for conflict between notebook extensions. It seems that you forgot to put assignment_list's files in a subdirectory? (or rather, you named that directory 'static') Remember that [Namespaces are one honking great idea](https://www.python.org/dev/peps/pep-0020/)

I'm also not sure what to do with that `jupyter nbextension` command. First, I don't know the entry point, second, isn't that what `nbgrader extension activate` is supposed to do?

```
(venv)vagrant@debian-83-amd64:~$ nbgrader extension activate
Activating create_assignment nbextension
Traceback (most recent call last):
  File "/tmp/a/bin/nbgrader", line 11, in <module>
    sys.exit(main())
  File "/tmp/a/local/lib/python2.7/site-packages/nbgrader/apps/nbgraderapp.py", line 232, in main
    NbGraderApp.launch_instance()
  File "/tmp/a/local/lib/python2.7/site-packages/jupyter_core/application.py", line 267, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/tmp/a/local/lib/python2.7/site-packages/traitlets/config/application.py", line 596, in launch_instance
    app.start()
  File "/tmp/a/local/lib/python2.7/site-packages/nbgrader/apps/nbgraderapp.py", line 225, in start
    super(NbGraderApp, self).start()
  File "/tmp/a/local/lib/python2.7/site-packages/jupyter_core/application.py", line 256, in start
    self.subapp.start()
  File "/tmp/a/local/lib/python2.7/site-packages/nbgrader/apps/extensionapp.py", line 207, in start
    super(ExtensionApp, self).start()
  File "/tmp/a/local/lib/python2.7/site-packages/traitlets/config/application.py", line 279, in start
    return self.subapp.start()
  File "/tmp/a/local/lib/python2.7/site-packages/nbgrader/apps/extensionapp.py", line 99, in start
    self.enable_nbextension("create_assignment/main")
AttributeError: 'ExtensionActivateApp' object has no attribute 'enable_nbextension'
```
Was `activate` broken by some Jupyter changes? It is plain broken right now.

```
(venv)vagrant@debian-83-amd64:~$ jupyter nbextension list
Known nbextensions:
  config dir: /home/vagrant/.jupyter/nbconfig
    notebook section
      nbgrader  enabled
      - Validating: problems found:
        - require?  X nbgrader
```
In the end I couldn't get this to run.

**Comment by jhamrick** [comment]
Yes, unfortunately this is an incompatibility problem with the notebook version 4.2, please see: https://github.com/jupyter/nbgrader/issues/497

If you downgrade to notebook 4.1 the issue should be fixed. I will be releasing the next version of nbgrader soon which will support notebook version 4.2

**Comment by jhamrick** [comment]
I am going to go ahead and close this, but feel free to reopen if you are still having issues!
