### ISSUE TITLE
sqlalchemy error when invoking autograder

### ISSUE THREAD

**Issue by ddbourgin** [jupyter/nbgrader#560]
When running the autograder over a large collection of student submissions, it errors out midway through with a message from sqlalchemy about having too many clients. A condensed traceback:

```
[AutogradeApp | ERROR] There was an error processing assignment: <assignment>                                                                                        
[AutogradeApp | ERROR] Traceback (most recent call last):                                                                           
      File "/opt/conda/lib/python3.5/site-packages/sqlalchemy/pool.py", line 1044, in _d                                            
o_get                                                                                                                               
        return self._pool.get(wait, self._timeout)                                                                                  
      File "/opt/conda/lib/python3.5/site-packages/sqlalchemy/util/queue.py", line 145,                                             
in get                                                                                                                              
        raise Empty                                                                                                                 
    sqlalchemy.util.queue.Empty                                                                                                     

    During handling of the above exception, another exception occurred:                                                             

    Traceback (most recent call last):                                                                                              
      File "/opt/conda/lib/python3.5/site-packages/sqlalchemy/engine/base.py", line 2074                                            
, in _wrap_pool_connect      

...                                                                                                               
      File "/opt/conda/lib/python3.5/site-packages/sqlalchemy/pool.py", line 607, in __c                                            
onnect                                                                                                                              
        connection = self.__pool._invoke_creator(self)                                                                              
      File "/opt/conda/lib/python3.5/site-packages/sqlalchemy/engine/strategies.py", lin                                            
e 97, in connect                                                                                                                    
        return dialect.connect(*cargs, **cparams)                                                                                   
      File "/opt/conda/lib/python3.5/site-packages/sqlalchemy/engine/default.py", line 3                                            
85, in connect                                                                                                                      
        return self.dbapi.connect(*cargs, **cparams)                                                                                
      File "/opt/conda/lib/python3.5/site-packages/psycopg2/__init__.py", line 164, in c                                            
onnect                                                                                                                              
        conn = _connect(dsn, connection_factory=connection_factory, async=async)                                                    
    sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) FATAL:  sorry, too many                                            
 clients already      
```

**Comment by jhamrick** [comment]
Ok, I've tracked down the issue, which is that the in `Gradebook.__init__` it creates the engine and session, and then the session is eventually closed but the engine is not. I will make a PR shortly to fix this.

**Comment by jhamrick** [comment]
It seems as though this error is still occurring for @ddbourgin :(

**Comment by lgpage** [comment]
I just finished grading 3353 submission files (1126 students) and this error did not occur. This was done using master at 1a44559

**Comment by jhamrick** [comment]
Where you using sqlite or postgres? This might be an issue only with postgres, but I'm not 100% sure.

**Comment by lgpage** [comment]
The default - sqlite

**Comment by lgpage** [comment]
I re-ran autograder using postgresql for the database and occasionally monitored the db connections with ``pg_top``. Same thing, no error and the db connections never exceeded 2.

**Comment by jhamrick** [comment]
Huh. I didn't know about `pg_top` -- that's definitely useful, thanks! I think maybe I will close this for now and reopen it if we (or anyone else) still has problems in the future.
