### ISSUE TITLE
Released assignment is not visible for student in assignments tab

### ISSUE THREAD

**Issue by inkrement** [jupyter/nbgrader#578]
System: Jupyterhub + nbgrade (newest version)

I released an new assignment (to `/srv/nbgrader/exchange`), but a test-student is not able to see it in the assignment tab. If I download it manually (`nbgrader fetch assignment_1 --course=SMA`) it works and I am also able to submit it... 

It's also there if I run `nbgrade list` in a students terminal. This behaviour is strange, isn't it?

![screen shot 2016-12-11 at 14 42 40](https://cloud.githubusercontent.com/assets/604528/21080464/2149b15e-bfb0-11e6-8f64-5f7a30578e42.png)

**Comment by jhamrick** [comment]
Just to clarify, the screenshot you're showing is after you have fetched it from the command line (i.e. it is showing nbgrader working correctly)?

**Comment by inkrement** [comment]
Yes, exactly. First I tried to fetch it with the UI (but all groups were empty) and then I fetched it manually (and now there are some entries).

**Comment by jhamrick** [comment]
Hmm. Are there any errors in the javascript console?

It looks like you're using JupyterHub from the screenshot -- can you try manually running the notebook from the command line and then seeing also if there are any errors in the log messages?

**Comment by inkrement** [comment]
Yes, I am using JupyterHub and I get no error in the jupyterhub output and also no error in my browsers JS console :/

**Comment by jhamrick** [comment]
Sorry, I meant the output from the notebook server itself, rather than JupyterHub -- I don't think there is an easy way to access this when running the notebook server through JupyterHub, which is why I suggested running it manually from the command line (i.e. with `jupyter notebook`).

**Comment by inkrement** [comment]
If I use the `jupyter notebook` command I also see the fetch-button! So just the jupyterhub and nbgrader combination does not work as expected, are they supposed to work together?

**Comment by jhamrick** [comment]
What is your JupyterHub config? It's possible that might be causing issues -- see https://groups.google.com/forum/#!topic/jupyter-education/VBd9nhq2crs for an example where someone else had a similar problem.

**Comment by inkrement** [comment]
ok thanks for the link. I have the same problem, but in my case `c.Spawner.disable_user_config = True` is not set (so the default is used). Now I updated jupyter, jupyterhub and nbgrader using pip and tried to install/enable the extension again, but I got following error:

```
chris@notebook:~$ jupyter nbextension install --sys-prefix --overwrite --py nbgrader
Traceback (most recent call last):
  File "/usr/local/bin/jupyter-nbextension", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.5/dist-packages/jupyter_core/application.py", line 267, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/home/chris/.local/lib/python3.5/site-packages/traitlets/config/application.py", line 658, in launch_instance
    app.start()
  File "/usr/local/lib/python3.5/dist-packages/notebook/nbextensions.py", line 969, in start
    super(NBExtensionApp, self).start()
  File "/usr/local/lib/python3.5/dist-packages/jupyter_core/application.py", line 256, in start
    self.subapp.start()
  File "/usr/local/lib/python3.5/dist-packages/notebook/nbextensions.py", line 745, in start
    self.install_extensions()
  File "/usr/local/lib/python3.5/dist-packages/notebook/nbextensions.py", line 724, in install_extensions
    **kwargs
  File "/usr/local/lib/python3.5/dist-packages/notebook/nbextensions.py", line 225, in install_nbextension_python
    m, nbexts = _get_nbextension_metadata(module)
  File "/usr/local/lib/python3.5/dist-packages/notebook/nbextensions.py", line 1143, in _get_nbextension_metadata
    'it is missing the `_jupyter_nbextension_paths()` method.'.format(module))
KeyError: 'The Python module nbgrader is not a valid nbextension, it is missing the `_jupyter_nbextension_paths()` method.'
```

**Comment by lgpage** [comment]
The current version of `nbgrader` (v0.3.1) on pip requires the extensions to be install and activated with `nbgrader extension install` and `nbgrader extension activate`. https://nbgrader.readthedocs.io/en/stable/user_guide/installation.html

**Comment by inkrement** [comment]
Oh thanks. Would you recommend to stick to the master version or wait for the latest to be released on pip? I have to set it up till march, so there would be enough time left. Maybe it works with the latest version... One big change of the new version is that it can be easily installed for all (Jupiterhub) users with a single command, right?

**Comment by jhamrick** [comment]
Yes, it is much easier to install for all users on JupyterHub using the master version.

I am working on getting a new release ready for 0.4.0 in the next few weeks, so I'd recommend using master for now (just so you can make sure everything in your deployment is working with the most recent stuff) and then by the time your class starts there will be a new release to use.

**Comment by jhamrick** [comment]
Also, after updating everything and installing the nbextensions again, are you still seeing the same issue (where no assignments are appearing)?

**Comment by inkrement** [comment]
I don't know. We have hardware problems with our server, so I am not able to use/try it yet :/

**Comment by jhamrick** [comment]
Ok, let me know when you get that sorted out if you are still having problems!

**Comment by inkrement** [comment]
I will close the issue now and reopen it, if this also happens with the new release.

**Comment by jhamrick** [comment]
Hmm. I am not sure why the issue would only affect 10% of students... it sounds like maybe there is a race condition somewhere. I am reopening this so we can track it.
