### ISSUE TITLE
The Python module nbgrader is not a valid nbextension....

### ISSUE THREAD

**Issue by dgrisham** [jupyter/nbgrader#663]
Hi --

I'm trying to install `nbgrader` for Python 3 on Arch Linux (which defaults to `python3`).

After successfully installing `jupyter` and `nbgrader` with

```
$ sudo pip install --upgrade pip
$ sudo pip install jupyter
$ sudo pip install nbgrader
```

Then, following the [rest of the instructions](https://nbgrader.readthedocs.io/en/latest/user_guide/installation.html), I received an error on the next command:

```
$ jupyter nbextension install --sys-prefix --py nbgrader
Traceback (most recent call last):
  File "/usr/bin/jupyter-nbextension", line 11, in <module>
    sys.exit(main())
  File "/usr/lib/python3.6/site-packages/jupyter_core/application.py", line 267, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/usr/lib/python3.6/site-packages/traitlets/config/application.py", line 658, in launch_instance
    app.start()
  File "/usr/lib/python3.6/site-packages/notebook/nbextensions.py", line 969, in start
    super(NBExtensionApp, self).start()
  File "/usr/lib/python3.6/site-packages/jupyter_core/application.py", line 256, in start
    self.subapp.start()
  File "/usr/lib/python3.6/site-packages/notebook/nbextensions.py", line 745, in start
    self.install_extensions()
  File "/usr/lib/python3.6/site-packages/notebook/nbextensions.py", line 724, in install_extensions
    **kwargs
  File "/usr/lib/python3.6/site-packages/notebook/nbextensions.py", line 225, in install_nbextension_python
    m, nbexts = _get_nbextension_metadata(module)
  File "/usr/lib/python3.6/site-packages/notebook/nbextensions.py", line 1143, in _get_nbextension_metadata
    'it is missing the `_jupyter_nbextension_paths()` method.'.format(module))
KeyError: 'The Python module nbgrader is not a valid nbextension, it is missing the `_jupyter_nbextension_paths()` method.'
```

I've done my best to ensure the error isn't something silly on my end (e.g. everything is updated, `jupyter` is only installed via `pip` and not conflicting with one from my distribution's repos, ...) but it's possible this is unique to me. If not, then hopefully this can help fix an issue :) Thanks in advance for your time!

David

**Comment by jhamrick** [comment]
The method you're using for installing nbextensions isn't compatible with nbgrader v0.3.x (which is what you get when you install from pip). There are two options:

* (The one I recommend) install the pre-release version of nbgrader 0.4.0, which is going to be officially released probably this weekend: `pip install nbgrader --pre`
* Or, follow the old installation instructions: http://nbgrader.readthedocs.io/en/stable/user_guide/installation.html

**Comment by jhamrick** [comment]
Also, you may need to pass the `-U` flag to force it to upgrade nbgrader. Let me know if you still have any trouble!

**Comment by dgrisham** [comment]
I went with your recommend option and installed with `pip install nbgrader --pre` and that seems to have resolved the issue, thank you Jessica! Glad it was a straightforward fix,
