### ISSUE TITLE
nbgrader and scala kernel problem

### ISSUE THREAD

**Issue by AnotherCodeArtist** [jupyter/nbgrader#719]
Hi!

I started off with the quickstart template and added a scala notebook with one autograded answer/test.

When I run the _nbgrader validate_ command I get the following error message:

```
Success! Your notebook passes all the tests.
Success! Your notebook passes all the tests.
Unrecognized argument: --HistoryManager.hist_file=:memory:
[ValidateApp | ERROR] Traceback (most recent call last):
      File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/nbgrader/preprocessors/execute.py", line 41, in preprocess
        output = super(Execute, self).preprocess(nb, resources)
      File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/nbconvert/preprocessors/execute.py", line 207, in preprocess
        cwd=path)
      File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/nbconvert/preprocessors/execute.py", line 192, in start_new_kernel
        kc.wait_for_ready(timeout=startup_timeout)
      File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/jupyter_client/blocking/client.py", line 59, in wait_for_ready
        raise RuntimeError('Kernel died before replying to kernel_info')
    RuntimeError: Kernel died before replying to kernel_info
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/nbgrader/apps/validateapp.py", line 81, in convert_single_notebook
        super(ValidateApp, self).convert_single_notebook(notebook_filename)
      File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/nbconvert/nbconvertapp.py", line 444, in convert_single_notebook
        output, resources = self.export_single_notebook(notebook_filename, resources, input_buffer=input_buffer)
      File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/nbconvert/nbconvertapp.py", line 373, in export_single_notebook
        output, resources = self.exporter.from_filename(notebook_filename, resources=resources)
      File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/nbconvert/exporters/exporter.py", line 171, in from_filename
        return self.from_file(f, resources=resources, **kw)
      File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/nbconvert/exporters/exporter.py", line 189, in from_file
        return self.from_notebook_node(nbformat.read(file_stream, as_version=4), resources=resources, **kw)
      File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/nbconvert/exporters/notebook.py", line 31, in from_notebook_node
        nb_copy, resources = super(NotebookExporter, self).from_notebook_node(nb, resources, **kw)
      File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/nbconvert/exporters/exporter.py", line 131, in from_notebook_node
        nb_copy, resources = self._preprocess(nb_copy, resources)
      File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/nbconvert/exporters/exporter.py", line 308, in _preprocess
        nbc, resc = preprocessor(nbc, resc)
      File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/nbconvert/preprocessors/base.py", line 47, in __call__
        return self.preprocess(nb,resources)
      File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/nbgrader/preprocessors/execute.py", line 44, in preprocess
        raise UnresponsiveKernelError()
    nbgrader.preprocessors.execute.UnresponsiveKernelError
```

So the two python notebooks created by quickstart are successfully validated, whereas the scala notebook fails.
Running `jupyter-console --kernel "scala211"`works, however, it takes some seconds to come up. So there might probably occur a timeout although `Kernel died before replying to kernel_info` indicates something different?

The same happens also with a haskell notebook.

**Comment by jhamrick** [comment]
Hmm, `Unrecognized argument: --HistoryManager.hist_file=:memory:` looks like #434 , but that was fixed a long time ago. What version of nbgrader are you running?

Can you also try executing the notebook with plain nbconvert, e.g. `jupyter nbconvert --execute notebook.ipynb`? Does that complete successfully?

**Comment by AnotherCodeArtist** [comment]
Hi!

I'm using jupyter version 4.3.0 and nbgrader version 0.4.0.

`jupyter nbconvert --execute source/ps1/scala.ipynb` produces a nice html. Here's the console output:
```
[NbConvertApp] Converting notebook source/ps1/scala.ipynb to html
[NbConvertApp] Executing notebook with kernel: scala211
[NbConvertApp] WARNING | Timeout waiting for IOPub output
[NbConvertApp] Writing 251079 bytes to source/ps1/scala.html
```

**Comment by jhamrick** [comment]
Ah, interesting. The IOPub timeout is still occurring, however:

```
[NbConvertApp] WARNING | Timeout waiting for IOPub output
```

which nbgrader is configured to raise an error on: https://github.com/jupyter/nbgrader/blob/master/nbgrader/preprocessors/execute.py#L15

I wonder if this is an issue with the particular notebook, or with the scala kernel? What's in the notebook? Do you have any long-running cells, or code that uses up a lot of memory? If not, this might be an issue with the interface between the scala kernel and nbconvert.

Additionally, if you have cells that are supposed to produce outputs, do the outputs get saved back out to the notebook after converting it with nbconvert (try adding `--to notebook` to the command)?

**Comment by AnotherCodeArtist** [comment]
WOW, that was quick!

There's just a simple add function and a test.
Here's the content of my notebook:
```scala
def add(a:Int,b:Int) = 
// BEGIN SOLUTION
a+b
// END SOLUTION

assert(add(5,2)==7)
assert(add(4,-3)==1)
```

It's only that the Scala environment takes significantly longer to come up than python.

Converting the notebook back to a notebook also works fine and the notebook is executed and the output update (changed the name of the function from `sum` to `add`without running it in the web interface and the output was updated in html as well as ipynb).


 
```
 jupyter nbconvert --to notebook --execute source/ps1/scala.ipynb
[NbConvertApp] Converting notebook source/ps1/scala.ipynb to notebook
[NbConvertApp] Executing notebook with kernel: scala211
[NbConvertApp] WARNING | Timeout waiting for IOPub output
[NbConvertApp] Writing 1733 bytes to source/ps1/scala.nbconvert.ipynb
```

Seems like the IOPub timeout has no apparent effect on the functionality. I get the same error (however without `Unrecognized argument: --HistoryManager.hist_file=:memory:`), when I try the same procedure with a haskell notebook. 
Is there a way to increase the timeout threshold?

**Comment by jhamrick** [comment]
You can set the `--ExecutePreprocessor.iopub_timeout` flag or config option:

https://github.com/jupyter/nbconvert/blob/master/nbconvert/preprocessors/execute.py#L129

It's already pretty high, though, (4s) which makes me suspect perhaps the scala and haskell kernels aren't properly sending an idle message after all the output has been sent. I can't look into this immediately, but I will try to do so this weekend.

**Comment by AnotherCodeArtist** [comment]
You might be right, cause increasing the `iopub_timeout` doesn't really help.
But I've made the following observation:
When I run the validate command with a wildcard pattern (eg. `nbgrader validate --ExecutePreprocessor.iopub_timeout=20 ./source/ps1/*.ipynb`) the error message comes _almost_ immediately. It really seems that the configuration option makes no difference here.
However, when I run the command and explicitly refer to the scala notebook (` nbgrader validate --ExecutePreprocessor.iopub_timeout=20 ./source/ps1/scala.ipynb `) it takes about the given timeout until the error occurs. The error message in this case is slightly different:

```
[ValidateApp | ERROR] Traceback (most recent call last):
      File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/nbconvert/preprocessors/execute.py", line 289, in run_cell
        msg = self.kc.iopub_channel.get_msg(timeout=self.iopub_timeout)
      File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/jupyter_client/blocking/channels.py", line 57, in get_msg
        raise Empty
    queue.Empty
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/nbgrader/preprocessors/execute.py", line 41, in preprocess
        output = super(Execute, self).preprocess(nb, resources)
      File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/nbconvert/preprocessors/execute.py", line 211, in preprocess
        nb, resources = super(ExecutePreprocessor, self).preprocess(nb, resources)
      File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/nbconvert/preprocessors/base.py", line 70, in preprocess
        nb.cells[index], resources = self.preprocess_cell(cell, resources, index)
      File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/nbconvert/preprocessors/execute.py", line 227, in preprocess_cell
        outputs = self.run_cell(cell)
      File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/nbconvert/preprocessors/execute.py", line 293, in run_cell
        raise RuntimeError("Timeout waiting for IOPub output")
    RuntimeError: Timeout waiting for IOPub output
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/nbgrader/apps/validateapp.py", line 81, in convert_single_notebook
        super(ValidateApp, self).convert_single_notebook(notebook_filename)
      File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/nbconvert/nbconvertapp.py", line 444, in convert_single_notebook
        output, resources = self.export_single_notebook(notebook_filename, resources, input_buffer=input_buffer)
      File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/nbconvert/nbconvertapp.py", line 373, in export_single_notebook
        output, resources = self.exporter.from_filename(notebook_filename, resources=resources)
      File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/nbconvert/exporters/exporter.py", line 171, in from_filename
        return self.from_file(f, resources=resources, **kw)
      File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/nbconvert/exporters/exporter.py", line 189, in from_file
        return self.from_notebook_node(nbformat.read(file_stream, as_version=4), resources=resources, **kw)
      File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/nbconvert/exporters/notebook.py", line 31, in from_notebook_node
        nb_copy, resources = super(NotebookExporter, self).from_notebook_node(nb, resources, **kw)
      File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/nbconvert/exporters/exporter.py", line 131, in from_notebook_node
        nb_copy, resources = self._preprocess(nb_copy, resources)
      File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/nbconvert/exporters/exporter.py", line 308, in _preprocess
        nbc, resc = preprocessor(nbc, resc)
      File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/nbconvert/preprocessors/base.py", line 47, in __call__
        return self.preprocess(nb,resources)
      File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/nbgrader/preprocessors/execute.py", line 44, in preprocess
        raise UnresponsiveKernelError()
    nbgrader.preprocessors.execute.UnresponsiveKernelError
```

**Comment by jhamrick** [comment]
I am fairly confident at this point that this is an issue either with nbconvert or with the kernels themselves (rather than nbgrader) but we can still try to debug here, and report the issue in the relevant place once we isolate it.

Can you try running `nbconvert` with log level set to debug, e.g.:

```
jupyter nbconvert --to notebook --execute --log-level=DEBUG source/ps1/scala.ipynb
```

and paste the output here?

**Comment by AnotherCodeArtist** [comment]
Sorry for the impressive latency, but there were so many things to do. Here's the request output:

```
jupyter nbconvert --to notebook --execute --log-level=DEBUG source/ps1/scala.ipynb
[NbConvertApp] Searching ['/Users/dummy/Documents/Projekte/Jupyter/nbgrader/info2', '/Users/dummy/.jupyter', '/Library/Frameworks/Python.framework/Versions/3.5/etc/jupyter', '/usr/local/etc/jupyter', '/etc/jupyter'] for config files
[NbConvertApp] Looking for jupyter_config in /etc/jupyter
[NbConvertApp] Looking for jupyter_config in /usr/local/etc/jupyter
[NbConvertApp] Looking for jupyter_config in /Library/Frameworks/Python.framework/Versions/3.5/etc/jupyter
[NbConvertApp] Looking for jupyter_config in /Users/dummy/.jupyter
[NbConvertApp] Looking for jupyter_config in /Users/dummy/Documents/Projekte/Jupyter/nbgrader/info2
[NbConvertApp] Looking for jupyter_nbconvert_config in /etc/jupyter
[NbConvertApp] Looking for jupyter_nbconvert_config in /usr/local/etc/jupyter
[NbConvertApp] Looking for jupyter_nbconvert_config in /Library/Frameworks/Python.framework/Versions/3.5/etc/jupyter
[NbConvertApp] Looking for jupyter_nbconvert_config in /Users/dummy/.jupyter
[NbConvertApp] Looking for jupyter_nbconvert_config in /Users/dummy/Documents/Projekte/Jupyter/nbgrader/info2
[NbConvertApp] Converting notebook source/ps1/scala.ipynb to notebook
[NbConvertApp] Notebook name is 'scala'
[NbConvertApp] Applying preprocessor: ExecutePreprocessor
[NbConvertApp] Executing notebook with kernel: scala211
[NbConvertApp] Found kernel scala211 in /Users/dummy/Library/Jupyter/kernels
[NbConvertApp] Found kernel ir in /Users/dummy/Library/Jupyter/kernels
[NbConvertApp] Native kernel (python3) available from /Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/ipykernel/resources
[NbConvertApp] Starting kernel: ['/Users/dummy/Documents/Projekte/Jupyter/kernels/jupyter-scala_2.11.6-0.2.0-SNAPSHOT/bin/jupyter-scala', '--quiet', '--connection-file', '/var/folders/rz/lqr8s5yx6vn6pp5d08sc8twh0000gn/T/tmpksl4zzbq.json']
[NbConvertApp] Connecting to: tcp://127.0.0.1:54482
[NbConvertApp] connecting shell channel to tcp://127.0.0.1:54479
[NbConvertApp] Connecting to: tcp://127.0.0.1:54479
[NbConvertApp] connecting iopub channel to tcp://127.0.0.1:54480
[NbConvertApp] Connecting to: tcp://127.0.0.1:54480
[NbConvertApp] connecting stdin channel to tcp://127.0.0.1:54481
[NbConvertApp] Connecting to: tcp://127.0.0.1:54481
[NbConvertApp] connecting heartbeat channel to tcp://127.0.0.1:54483
[NbConvertApp] Executing cell:
def add(a:Int,b:Int) = 
// BEGIN SOLUTION
a+b
// END SOLUTION
[NbConvertApp] output: execute_input
[NbConvertApp] output: status
[NbConvertApp] output: display_data
[NbConvertApp] output: status
[NbConvertApp] Executing cell:
assert(add(5,2)==7)
assert(add(4,-3)==1)
[NbConvertApp] output: execute_input
[NbConvertApp] output: status
[NbConvertApp] output: display_data
[NbConvertApp] output: status
[NbConvertApp] Executing cell:

[NbConvertApp] WARNING | Timeout waiting for IOPub output
[NbConvertApp] Applying preprocessor: coalesce_streams
[NbConvertApp] Writing 1733 bytes to source/ps1/scala.nbconvert.ipynb
```

Hope that is helpful.

**Comment by AnotherCodeArtist** [comment]
After carefully reading the log, I saw that the timeout is caused by an empty cell. I removed it an run the command again:

```
jupyter nbconvert --to notebook --execute --log-level=DEBUG source/ps1/scala.ipynb
[NbConvertApp] Searching ['/Users/dummy/Documents/Projekte/Jupyter/nbgrader/info2', '/Users/dummy/.jupyter', '/Library/Frameworks/Python.framework/Versions/3.5/etc/jupyter', '/usr/local/etc/jupyter', '/etc/jupyter'] for config files
[NbConvertApp] Looking for jupyter_config in /etc/jupyter
[NbConvertApp] Looking for jupyter_config in /usr/local/etc/jupyter
[NbConvertApp] Looking for jupyter_config in /Library/Frameworks/Python.framework/Versions/3.5/etc/jupyter
[NbConvertApp] Looking for jupyter_config in /Users/dummy/.jupyter
[NbConvertApp] Looking for jupyter_config in /Users/dummy/Documents/Projekte/Jupyter/nbgrader/info2
[NbConvertApp] Looking for jupyter_nbconvert_config in /etc/jupyter
[NbConvertApp] Looking for jupyter_nbconvert_config in /usr/local/etc/jupyter
[NbConvertApp] Looking for jupyter_nbconvert_config in /Library/Frameworks/Python.framework/Versions/3.5/etc/jupyter
[NbConvertApp] Looking for jupyter_nbconvert_config in /Users/dummy/.jupyter
[NbConvertApp] Looking for jupyter_nbconvert_config in /Users/dummy/Documents/Projekte/Jupyter/nbgrader/info2
[NbConvertApp] Converting notebook source/ps1/scala.ipynb to notebook
[NbConvertApp] Notebook name is 'scala'
[NbConvertApp] Applying preprocessor: ExecutePreprocessor
[NbConvertApp] Executing notebook with kernel: scala211
[NbConvertApp] Found kernel scala211 in /Users/dummy/Library/Jupyter/kernels
[NbConvertApp] Found kernel ir in /Users/dummy/Library/Jupyter/kernels
[NbConvertApp] Native kernel (python3) available from /Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/ipykernel/resources
[NbConvertApp] Starting kernel: ['/Users/dummy/Documents/Projekte/Jupyter/kernels/jupyter-scala_2.11.6-0.2.0-SNAPSHOT/bin/jupyter-scala', '--quiet', '--connection-file', '/var/folders/rz/lqr8s5yx6vn6pp5d08sc8twh0000gn/T/tmp8x7ybet9.json']
[NbConvertApp] Connecting to: tcp://127.0.0.1:60644
[NbConvertApp] connecting shell channel to tcp://127.0.0.1:60641
[NbConvertApp] Connecting to: tcp://127.0.0.1:60641
[NbConvertApp] connecting iopub channel to tcp://127.0.0.1:60642
[NbConvertApp] Connecting to: tcp://127.0.0.1:60642
[NbConvertApp] connecting stdin channel to tcp://127.0.0.1:60643
[NbConvertApp] Connecting to: tcp://127.0.0.1:60643
[NbConvertApp] connecting heartbeat channel to tcp://127.0.0.1:60645
[NbConvertApp] Executing cell:
def add(a:Int,b:Int) = 
// BEGIN SOLUTION
a+b
// END SOLUTION
[NbConvertApp] output: execute_input
[NbConvertApp] output: status
[NbConvertApp] output: display_data
[NbConvertApp] output: status
[NbConvertApp] Executing cell:
assert(add(5,2)==7)
assert(add(4,-3)==1)
[NbConvertApp] output: execute_input
[NbConvertApp] output: status
[NbConvertApp] output: display_data
[NbConvertApp] output: status
[NbConvertApp] Applying preprocessor: coalesce_streams
[NbConvertApp] Writing 1548 bytes to source/ps1/scala.nbconvert.ipynb
```

So the error is gone here but no change when I run the `validate` command!

**Comment by jhamrick** [comment]
Sorry this fell off my radar. Can you try running the validate command with `--log-level=DEBUG` and paste the full output here? I want to compare it to the `NbConvertApp` output you've pasted. This is really puzzling, since nbgrader runs nbconvert under the hood so there really shouldn't be a difference...

**Comment by jhamrick** [comment]
I am closing this issue because there hasn't been any activity on it in a while. However, if you (or others) continue to encounter problems, feel free to comment here or open a new issue!

**Comment by fishfree** [comment]
The problem still exists.
