### ISSUE TITLE
nbgrader collect does not work - permissions denied

### ISSUE THREAD

**Issue by ZelphirKaltstahl** [jupyter/nbgrader#728]
I followed the readme at: https://github.com/jhamrick/nbgrader-demo however, collecting solutions does not work:

    [CollectApp | INFO] Collecting submission: user ps1
    Traceback (most recent call last):
      File "/home/user/apps/anaconda3/envs/nbgrader/bin/nbgrader", line 11, in <module>
        load_entry_point('nbgrader==0.5.0.dev0', 'console_scripts', 'nbgrader')()
      File "/home/user/apps/anaconda3/envs/nbgrader/lib/python3.6/site-packages/nbgrader/apps/nbgraderapp.py", line 301, in main
        NbGraderApp.launch_instance()
      File "/home/user/apps/anaconda3/envs/nbgrader/lib/python3.6/site-packages/jupyter_core/application.py", line 267, in launch_instance
        return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
      File "/home/user/apps/anaconda3/envs/nbgrader/lib/python3.6/site-packages/traitlets/config/application.py", line 658, in launch_inst
    ance
        app.start()
      File "/home/user/apps/anaconda3/envs/nbgrader/lib/python3.6/site-packages/nbgrader/apps/nbgraderapp.py", line 294, in start
        super(NbGraderApp, self).start()
      File "/home/user/apps/anaconda3/envs/nbgrader/lib/python3.6/site-packages/jupyter_core/application.py", line 256, in start
        self.subapp.start()
      File "/home/user/apps/anaconda3/envs/nbgrader/lib/python3.6/site-packages/nbgrader/apps/collectapp.py", line 95, in start
        collect.start()
      File "/home/user/apps/anaconda3/envs/nbgrader/lib/python3.6/site-packages/nbgrader/exchange/exchange.py", line 131, in start
        self.copy_files()
      File "/home/user/apps/anaconda3/envs/nbgrader/lib/python3.6/site-packages/nbgrader/exchange/collect.py", line 83, in copy_files
        self.do_copy(src_path, dest_path)
      File "/home/user/apps/anaconda3/envs/nbgrader/lib/python3.6/site-packages/nbgrader/exchange/exchange.py", line 118, in do_copy
        shutil.copytree(src, dest, ignore=shutil.ignore_patterns(*self.coursedir.ignore))
      File "/home/user/apps/anaconda3/envs/nbgrader/lib/python3.6/shutil.py", line 359, in copytree
        raise Error(errors)
    shutil.Error: [('/home/user/development/nbgrader/exchange/demo/inbound/user+ps1+2017-03-23 12:06:35 UTC/images/numbered-list
    .png', '/home/user/development/nbgrader/nbgrader-demo-master/instructor/submitted/user/ps1/images/numbered-list.png', "[Errn
    o 13] Permission denied: '/home/user/development/nbgrader/exchange/demo/inbound/user+ps1+2017-03-23 12:06:35 UTC/images/numb
    ered-list.png'"), ..........................

My `nbgrader_config.py` is:

    from nbgrader.utils import get_username

    c = get_config()

    c.Exchange.course_id = "demo"
    c.Exchange.db_assignments = [dict(name="ps1")]
    c.Exchange.db_students = [dict(id=get_username())]
    c.Exchange.root = "/home/user/development/nbgrader/exchange/"

Also `nbgrader autograde ps1` does not work.

    [AutogradeApp | INFO] Copying /home/user/development/nbgrader/nbgrader-demo-master/instructor/submitted/user/ps1/timestamp.t
    xt -> /home/user/development/nbgrader/nbgrader-demo-master/instructor/autograded/user/ps1/timestamp.txt
    [AutogradeApp | INFO] Copying /home/user/development/nbgrader/nbgrader-demo-master/instructor/submitted/user/ps1/plotchecker
    .py -> /home/user/development/nbgrader/nbgrader-demo-master/instructor/autograded/user/ps1/plotchecker.py
    [AutogradeApp | INFO] Copying /home/user/development/nbgrader/nbgrader-demo-master/instructor/submitted/user/ps1/.nbgrader.l
    og -> /home/user/development/nbgrader/nbgrader-demo-master/instructor/autograded/user/ps1/.nbgrader.log
    [AutogradeApp | ERROR] No student with ID 'user' exists in the database

Seems like I was supposed to create a user in a database at some point, or the nbgrader should have done that but did not.

**Comment by jhamrick** [comment]
1. Are you doing this in the demo, or on your local computer?
2. Have you been running all the commands using the same user account (i.e. `nbgrader assign`, `nbgrader release`, `nbgrader fetch`, `nbgrader submit`) or different user accounts?
3. Can you say what the permissions are for the relevant file, e.g. run the command:

```
ls -l /home/user/development/nbgrader/exchange/demo/inbound/user+ps1+2017-03-23 12:06:35 UTC/images/numbered-list.png
```

> Seems like I was supposed to create a user in a database at some point, or the nbgrader should have done that but did not.

Yes, that is because your config file is incorrect, as in #727

**Comment by ZelphirKaltstahl** [comment]
@jhamrick This is on my local computer. The commands were run by the same user all the time. I did never enter any `sudo` or anything. The output of the command is:

    total 228
    -rw-r--r-- 1 user user 21262 Mär 23 12:36 1 - Introduction to the IPython notebook.ipynb
    -rw-r--r-- 1 user user 21994 Mär 23 12:37 2 - Markdown and LaTeX Cheatsheet.ipynb
    -rw-r--r-- 1 user user 49783 Mär 23 12:37 3 - Introduction to NumPy.ipynb
    -rw-r--r-- 1 user user 43634 Mär 23 12:37 4 - Manipulating and Plotting Data.ipynb
    -rw-r--r-- 1 user user 28155 Mär 23 12:37 5 - Advanced NumPy.ipynb
    -rw-r--r-- 1 user user 21450 Mär 23 12:53 6 - Truth Tables.ipynb
    -rw-r--r-- 1 user user 15067 Mär 23 12:37 7 - Debugging.ipynb
    drw-r--r-- 2 user user  4096 Mär 23 12:36 data
    drw-r--r-- 2 user user  4096 Mär 23 12:36 images
    -rw-r--r-- 1 user user  1907 Mär 23 12:36 plotchecker.py
    -rw-r--r-- 1 user user    23 Mär 23 13:06 timestamp.txt

**Comment by jhamrick** [comment]
Hmm, strange. If you're using this with the same user account in all cases, then there definitely shouldn't be any permissions errors... so I'm not really sure what could be going wrong, but let's try a few things and see if we can track down the issue.

First, perhaps it's possible that there are permissions issues with other directories in your exchange path? Can you look to see what the permissions are for each of the containing directories, i.e.

```
ls -l /home/user/development/nbgrader/exchange
ls -l /home/user/development/nbgrader
ls -l /home/user/development
ls -l /home/user
ls -l /home
```

Then, can you try using a different exchange directory altogether, e.g. `/tmp/exchange`:

```
mkdir /tmp/exchange
chmod +rw /tmp/exchange
```

and then update your config and try re-running all the nbgrader commands again?

**Comment by Zsailer** [comment]
I get a similar issue when an assignment contains a directory. The permissions of the directory are "read-only", so errors are raised when `nbgrader collect` tries to move the inbound assignment to the instructor's submitted folder. 

As a quick fix, I adjust the permissions of the inbound assignments in the exchange directory to allow execution by the instructor.

**Comment by jhamrick** [comment]
Ah, ok, yes, I can reproduce this now. Steps to reproduce:

```
$ nbgrader quickstart course101
$ cd course101/
$ nbgrader assign ps1
$ nbgrader release ps1
$ nbgrader fetch ps1
$ mkdir ps1/foo
$ touch ps1/foo/temp.txt
$ nbgrader submit ps1
$ nbgrader collect ps1
[CollectApp | INFO] Collecting submission: jhamrick ps1
Traceback (most recent call last):
  File "/Users/jhamrick/miniconda3/envs/nbgrader/bin/nbgrader", line 11, in <module>
    load_entry_point('nbgrader', 'console_scripts', 'nbgrader')()
  File "/Users/jhamrick/project/tools/nbgrader/nbgrader/apps/nbgraderapp.py", line 301, in main
    NbGraderApp.launch_instance()
  File "/Users/jhamrick/miniconda3/envs/nbgrader/lib/python3.5/site-packages/jupyter_core/application.py", line 267, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/Users/jhamrick/miniconda3/envs/nbgrader/lib/python3.5/site-packages/traitlets/config/application.py", line 658, in launch_instance
    app.start()
  File "/Users/jhamrick/project/tools/nbgrader/nbgrader/apps/nbgraderapp.py", line 294, in start
    super(NbGraderApp, self).start()
  File "/Users/jhamrick/miniconda3/envs/nbgrader/lib/python3.5/site-packages/jupyter_core/application.py", line 256, in start
    self.subapp.start()
  File "/Users/jhamrick/project/tools/nbgrader/nbgrader/apps/collectapp.py", line 95, in start
    collect.start()
  File "/Users/jhamrick/project/tools/nbgrader/nbgrader/exchange/exchange.py", line 131, in start
    self.copy_files()
  File "/Users/jhamrick/project/tools/nbgrader/nbgrader/exchange/collect.py", line 83, in copy_files
    self.do_copy(src_path, dest_path)
  File "/Users/jhamrick/project/tools/nbgrader/nbgrader/exchange/exchange.py", line 118, in do_copy
    shutil.copytree(src, dest, ignore=shutil.ignore_patterns(*self.coursedir.ignore))
  File "/Users/jhamrick/miniconda3/envs/nbgrader/lib/python3.5/shutil.py", line 353, in copytree
    raise Error(errors)
shutil.Error: [('/srv/nbgrader/exchange/course101/inbound/jhamrick+ps1+2017-05-03 21:59:06 UTC/foo/temp.txt', '/private/tmp/course101/submitted/jhamrick/ps1/foo/temp.txt', "[Errno 13] Permission denied: '/srv/nbgrader/exchange/course101/inbound/jhamrick+ps1+2017-05-03 21:59:06 UTC/foo/temp.txt'")]
```
