### ISSUE TITLE
Feedback error on Windows

### ISSUE THREAD

**Issue by lgpage** [jupyter/nbgrader#806]
I am getting the following error on Windows but not on Linux:

```bash
[FeedbackApp | INFO] Copying C:\Users\logan\Desktop\Notebooks\assignments\demo\autograded\u00000001\ps1\timestamp.txt -> C:\Users\logan\Desktop\Notebooks\assignments\demo\feedback\u00000001\ps1\timestamp.txt
[FeedbackApp | INFO] Converting notebook C:\Users\logan\Desktop\Notebooks\assignments\demo\autograded\u00000001\ps1\problem1.ipynb
[FeedbackApp | ERROR] There was an error processing assignment: C:\Users\logan\Desktop\Notebooks\assignments\demo\autograded\u00000001\ps1
[FeedbackApp | ERROR] Traceback (most recent call last):
      File "C:\ProgramData\Anaconda3\lib\site-packages\nbgrader\converters\base.py", line 288, in convert_notebooks
        self.convert_single_notebook(notebook_filename)
      File "C:\ProgramData\Anaconda3\lib\site-packages\nbgrader\converters\base.py", line 244, in convert_single_notebook
        output, resources = self.exporter.from_filename(notebook_filename, resources=resources)
      File "C:\ProgramData\Anaconda3\lib\site-packages\nbconvert\exporters\exporter.py", line 171, in from_filename
        return self.from_file(f, resources=resources, **kw)
      File "C:\ProgramData\Anaconda3\lib\site-packages\nbconvert\exporters\exporter.py", line 189, in from_file
        return self.from_notebook_node(nbformat.read(file_stream, as_version=4), resources=resources, **kw)
      File "C:\ProgramData\Anaconda3\lib\site-packages\nbconvert\exporters\html.py", line 69, in from_notebook_node
        return super(HTMLExporter, self).from_notebook_node(nb, resources, **kw)
      File "C:\ProgramData\Anaconda3\lib\site-packages\nbconvert\exporters\templateexporter.py", line 239, in from_notebook_node
        output = self.template.render(nb=nb_copy, resources=resources)
      File "C:\ProgramData\Anaconda3\lib\site-packages\nbconvert\exporters\templateexporter.py", line 111, in template
        self._template_cached = self._load_template()
      File "C:\ProgramData\Anaconda3\lib\site-packages\nbconvert\exporters\templateexporter.py", line 222, in _load_template
        return self.environment.get_template(template_file)
      File "C:\ProgramData\Anaconda3\lib\site-packages\jinja2\environment.py", line 830, in get_template
        return self._load_template(name, self.make_globals(globals))
      File "C:\ProgramData\Anaconda3\lib\site-packages\jinja2\environment.py", line 804, in _load_template
        template = self.loader.load(self, name, globals)
      File "C:\ProgramData\Anaconda3\lib\site-packages\jinja2\loaders.py", line 405, in load
        return loader.load(environment, name, globals)
      File "C:\ProgramData\Anaconda3\lib\site-packages\jinja2\loaders.py", line 113, in load
        source, filename, uptodate = self.get_source(environment, name)
      File "C:\ProgramData\Anaconda3\lib\site-packages\nbconvert\exporters\templateexporter.py", line 75, in get_source
        return self.loader.get_source(environment, template)
      File "C:\ProgramData\Anaconda3\lib\site-packages\jinja2\loaders.py", line 171, in get_source
        f = open_if_exists(filename)
      File "C:\ProgramData\Anaconda3\lib\site-packages\jinja2\utils.py", line 154, in open_if_exists
        return open(filename, mode)
    PermissionError: [Errno 13] Permission denied: '.\\feedback'
```

This was on a fresh install of Anaconda and nbgrader 0.5.1

**Comment by jhamrick** [comment]
Hmm, I wonder how that error crept in there.

Unfortunately I'm traveling until August and won't be able to debug this on my windows machine until then... but maybe someone at SciPy sprints will have windows and I could get them to look at it :-)

**Comment by jhamrick** [comment]
Just to confirm, does this happen with the notebooks created by nbgrader quickstart? e.g. does it happen if you do:

```
nbgrader quickstart course101
cd course101
nbgrader assign ps1 --create
mkdir -p submitted/test_student
cp -r release/ps1 submitted/test_student/ps1
nbgrader autograde ps1 --create
nbgrader feedback ps1
```

**Comment by lgpage** [comment]
I will double check this on Monday and get back to you.
The demo I set up was created from the quickstart files.

**Comment by jhamrick** [comment]
I wasn't able to get someone to work on this during sprints, unfortunately. Did you have a chance to look more at it?

**Comment by lgpage** [comment]
This should maybe be reported as a `nbconvert` issue.
The default template name (`feedback`) was getting matched to the default folder name (`feedback`) and `jinja2` was thus trying to load the folder as a template file.

**Comment by jhamrick** [comment]
Ah, curious. I'm a bit confused why the windows tests would all pass if this was an issue, but if #850 seems to fix the problem for you then I'll go ahead and merge that now and maybe investigate further when I'm back home.

**Comment by lgpage** [comment]
I am also at a bit of a loss as to why the CI tests pass, but this gives an issue on my machine :(
#850 did the trick in sorting it out. Also if I only had one path (not `'.'`) in the `template_path` list (https://github.com/jupyter/nbgrader/blob/master/nbgrader/converters/feedback.py#L49) then it also worked.
