### ISSUE TITLE
`jupyter notebook` fails to create the exchange directory

### ISSUE THREAD

**Issue by ixjlyons** [jupyter/nbgrader#820]
Just running `jupyter notebook` after quickstart attempts to create the exchange directory. In my case, this fails because I do not have permissions in the `/srv` directory.

```
[C 09:01:08.652 NotebookApp] Unwritable directory, please contact your instructor: /srv/nbgrader/exchange
[E 09:01:08.654 NotebookApp] Traceback (most recent call last):
      File "/home/kenny/miniconda3/envs/nbgrader/lib/python3.6/site-packages/nbgrader/server_extensions/assignment_list/handlers.py", line 63, in list_released_assignments
        assignments = lister.start()
      File "/home/kenny/miniconda3/envs/nbgrader/lib/python3.6/site-packages/nbgrader/exchange/list.py", line 129, in start
        super(ExchangeList, self).start()
      File "/home/kenny/miniconda3/envs/nbgrader/lib/python3.6/site-packages/nbgrader/exchange/exchange.py", line 122, in start
        self.ensure_root()
      File "/home/kenny/miniconda3/envs/nbgrader/lib/python3.6/site-packages/nbgrader/exchange/exchange.py", line 100, in ensure_root
        self.fail("Unwritable directory, please contact your instructor: {}".format(self.root))
      File "/home/kenny/miniconda3/envs/nbgrader/lib/python3.6/site-packages/nbgrader/exchange/exchange.py", line 78, in fail
        raise ExchangeError(msg)
    nbgrader.exchange.exchange.ExchangeError: Unwritable directory, please contact your instructor: /srv/nbgrader/exchange
```

**Comment by jhamrick** [comment]
I think the best solution is to not attempt to create the exchange directory until the formgrader (or the assignment list extension) is actually accessed.

**Comment by Yenthe666** [comment]
@jhamrick didn't this just move up the problem one level though? Okay now it won't go wrong if you have no formgraders but as soon as you make one you will/can still get it:
```
Traceback (most recent call last): File "/usr/local/lib/python3.6/dist-packages/nbgrader/server_extensions/assignment_list/handlers.py", line 65, in list_released_assignments assignments = lister.start() File "/usr/local/lib/python3.6/dist-packages/nbgrader/exchange/list.py", line 129, in start super(ExchangeList, self).start() File "/usr/local/lib/python3.6/dist-packages/nbgrader/exchange/exchange.py", line 122, in start self.ensure_root() File "/usr/local/lib/python3.6/dist-packages/nbgrader/exchange/exchange.py", line 100, in ensure_root self.fail("Unwritable directory, please contact your instructor: {}".format(self.root)) File "/usr/local/lib/python3.6/dist-packages/nbgrader/exchange/exchange.py", line 78, in fail raise ExchangeError(msg) nbgrader.exchange.exchange.ExchangeError: Unwritable directory, please contact your instructor: /srv/nbgrader/exchange 
```

**Comment by jhamrick** [comment]
Generally, the exchange directory is in a location that is only writeable
by root, so nbgrader wouldn't have permissions to create it automatically
(it shouldn't be run as root). Thus the exchange is unfortunately something
that has to be created manually by the instructor, rather than something
nbgrader can itself create.

**Comment by Yenthe666** [comment]
Hmm I see. Could you perhaps slightly expand the documentation though? I think an example in the docs where you say where Jupyter is installed (for example /home/administrator/Jupyter) along with in which directory the extra directories should be created would be a neat clarification. To me it's unclear in which path nbgrader actually expects the new folder to be created.

**Comment by jhamrick** [comment]
There is documentation for setting up the exchange here:
https://nbgrader.readthedocs.io/en/stable/user_guide/managing_assignment_files.html#setting-up-the-exchange

> I think an example in the docs where you say where Jupyter is installed
(for example /home/administrator/Jupyter)

I'm a bit hesitant to list specific directories like that just because it
will be different on every system, and in my experience having specifics
like that in the documentation can actually create more confusion :-/
However, I think it wouldn't hurt to include a link on the installation
page pointing to the documentation on setting up the exchange, so that it's
clearer that is a required step in the setup process.
