### ISSUE TITLE
conda install throws warnings and doesn't install extensions

### ISSUE THREAD

**Issue by ncclementi** [jupyter/nbgrader#854]
I'm using the latest anaconda, when installing `nbgrader` using `conda` I followed the next steps: 
```
conda install jupyter
conda install -c conda-forge nbgrader
```
I did the quick start using `nbgrader quickstart` and when launching the notebooks I got the following (and the extensions don't appear). I got this same warning with `pip`, however, the extensions display well. 

```
[W 16:22:07.244 NotebookApp] server_extensions is deprecated, use nbserver_extensions
[W 16:22:08.086 NotebookApp] Error loading server extension jupyter_nbextensions_configurator
    Traceback (most recent call last):
      File "/home/ncclementi/anaconda3/lib/python3.5/site-packages/notebook/notebookapp.py", line 1271, in init_server_extensions
        mod = importlib.import_module(modulename)
      File "/home/ncclementi/anaconda3/lib/python3.5/importlib/__init__.py", line 126, in import_module
        return _bootstrap._gcd_import(name[level:], package, level)
      File "<frozen importlib._bootstrap>", line 986, in _gcd_import
      File "<frozen importlib._bootstrap>", line 969, in _find_and_load
      File "<frozen importlib._bootstrap>", line 956, in _find_and_load_unlocked
    ImportError: No module named 'jupyter_nbextensions_configurator'
[I 16:22:08.092 NotebookApp] Serving notebooks from local directory: /home/ncclementi/Documents/course_test
[I 16:22:08.092 NotebookApp] 0 active kernels 
[I 16:22:08.092 NotebookApp] The Jupyter Notebook is running at: http://localhost:8888/?token=f9ff6478a7df2efb78e2db6314ea3791f0dde4761267661b
[I 16:22:08.092 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 16:22:08.093 NotebookApp] 
    
    Copy/paste this URL into your browser when you connect for the first time,
    to login with a token:
        http://localhost:8888/?token=f9ff6478a7df2efb78e2db6314ea3791f0dde4761267661b
[I 16:22:08.395 NotebookApp] Accepting one-time-token-authenticated connection from 127.0.0.1
[W 16:22:10.032 NotebookApp] 404 GET /nbextensions/nbextensions_configurator/tree_tab/main.js?v=20170720162207 (127.0.0.1) 9.55ms referer=http://localhost:8888/tree
[W 16:22:21.878 NotebookApp] 404 GET /nbextensions/nbextensions_configurator/tree_tab/main.js?v=20170720162207 (127.0.0.1) 2.89ms referer=http://localhost:8888/tree/source
[W 16:22:29.992 NotebookApp] 404 GET /nbextensions/nbextensions_configurator/tree_tab/main.js?v=20170720162207 (127.0.0.1) 6.38ms referer=http://localhost:8888/tree/source/ps1
```

If I run `jupyter notebook --debug` I got:

```
[D 16:28:25.045 NotebookApp] Searching ['/home/ncclementi/Documents/course_test', '/home/ncclementi/.jupyter', '/home/ncclementi/anaconda3/etc/jupyter', '/usr/local/etc/jupyter', '/etc/jupyter'] for config files
[D 16:28:25.046 NotebookApp] Looking for jupyter_config in /etc/jupyter
[D 16:28:25.046 NotebookApp] Looking for jupyter_config in /usr/local/etc/jupyter
[D 16:28:25.046 NotebookApp] Looking for jupyter_config in /home/ncclementi/anaconda3/etc/jupyter
[D 16:28:25.046 NotebookApp] Looking for jupyter_config in /home/ncclementi/.jupyter
[D 16:28:25.047 NotebookApp] Looking for jupyter_config in /home/ncclementi/Documents/course_test
[D 16:28:25.047 NotebookApp] Looking for jupyter_notebook_config in /etc/jupyter
[D 16:28:25.047 NotebookApp] Looking for jupyter_notebook_config in /usr/local/etc/jupyter
[D 16:28:25.048 NotebookApp] Looking for jupyter_notebook_config in /home/ncclementi/anaconda3/etc/jupyter
[D 16:28:25.048 NotebookApp] Looking for jupyter_notebook_config in /home/ncclementi/.jupyter
[D 16:28:25.048 NotebookApp] Loaded config file: /home/ncclementi/.jupyter/jupyter_notebook_config.json
[D 16:28:25.048 NotebookApp] Looking for jupyter_notebook_config in /home/ncclementi/Documents/course_test
[W 16:28:25.049 NotebookApp] server_extensions is deprecated, use nbserver_extensions
[W 16:28:25.806 NotebookApp] Error loading server extension jupyter_nbextensions_configurator
    Traceback (most recent call last):
      File "/home/ncclementi/anaconda3/lib/python3.5/site-packages/notebook/notebookapp.py", line 1271, in init_server_extensions
        mod = importlib.import_module(modulename)
      File "/home/ncclementi/anaconda3/lib/python3.5/importlib/__init__.py", line 126, in import_module
        return _bootstrap._gcd_import(name[level:], package, level)
      File "<frozen importlib._bootstrap>", line 986, in _gcd_import
      File "<frozen importlib._bootstrap>", line 969, in _find_and_load
      File "<frozen importlib._bootstrap>", line 956, in _find_and_load_unlocked
    ImportError: No module named 'jupyter_nbextensions_configurator'
[I 16:28:25.810 NotebookApp] Serving notebooks from local directory: /home/ncclementi/Documents/course_test
[I 16:28:25.810 NotebookApp] 0 active kernels 
[I 16:28:25.810 NotebookApp] The Jupyter Notebook is running at: http://localhost:8888/?token=b460d7b4016d0fed9cb973ee0b2696e2576f227c9beac516
[I 16:28:25.810 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 16:28:25.811 NotebookApp] 
    
    Copy/paste this URL into your browser when you connect for the first time,
    to login with a token:
        http://localhost:8888/?token=b460d7b4016d0fed9cb973ee0b2696e2576f227c9beac516
[I 16:28:26.078 NotebookApp] Accepting one-time-token-authenticated connection from 127.0.0.1
[D 16:28:26.080 NotebookApp] Using contents: services/contents
[D 16:28:26.138 NotebookApp] Path base/images/favicon.ico served from /home/ncclementi/anaconda3/lib/python3.5/site-packages/notebook/static/base/images/favicon.ico
[D 16:28:26.139 NotebookApp] Path components/jquery-ui/themes/smoothness/jquery-ui.min.css served from /home/ncclementi/anaconda3/lib/python3.5/site-packages/notebook/static/components/jquery-ui/themes/smoothness/jquery-ui.min.css
[D 16:28:26.139 NotebookApp] Path components/jquery-typeahead/dist/jquery.typeahead.min.css served from /home/ncclementi/anaconda3/lib/python3.5/site-packages/notebook/static/components/jquery-typeahead/dist/jquery.typeahead.min.css
[D 16:28:26.140 NotebookApp] Path style/style.min.css served from /home/ncclementi/anaconda3/lib/python3.5/site-packages/notebook/static/style/style.min.css
[D 16:28:26.141 NotebookApp] Path components/es6-promise/promise.min.js served from /home/ncclementi/anaconda3/lib/python3.5/site-packages/notebook/static/components/es6-promise/promise.min.js
[D 16:28:26.142 NotebookApp] Path components/preact/index.js served from /home/ncclementi/anaconda3/lib/python3.5/site-packages/notebook/static/components/preact/index.js
[D 16:28:26.142 NotebookApp] Path components/proptypes/index.js served from /home/ncclementi/anaconda3/lib/python3.5/site-packages/notebook/static/components/proptypes/index.js
[D 16:28:26.142 NotebookApp] Path components/preact-compat/index.js served from /home/ncclementi/anaconda3/lib/python3.5/site-packages/notebook/static/components/preact-compat/index.js
[D 16:28:26.143 NotebookApp] Path components/requirejs/require.js served from /home/ncclementi/anaconda3/lib/python3.5/site-packages/notebook/static/components/requirejs/require.js
[D 16:28:26.144 NotebookApp] Path base/images/logo.png served from /home/ncclementi/anaconda3/lib/python3.5/site-packages/notebook/static/base/images/logo.png
[D 16:28:26.144 NotebookApp] Path tree/js/main.min.js served from /home/ncclementi/anaconda3/lib/python3.5/site-packages/notebook/static/tree/js/main.min.js
[D 16:28:26.148 NotebookApp] 200 GET /tree?token=57b3f955e387938f49b2705a0c46e1eab1757d37eb306f10 (127.0.0.1) 72.00ms
[D 16:28:26.617 NotebookApp] Path custom.css served from /home/ncclementi/anaconda3/lib/python3.5/site-packages/notebook/static/custom/custom.css
[D 16:28:26.618 NotebookApp] 304 GET /custom/custom.css (127.0.0.1) 2.85ms
[D 16:28:27.129 NotebookApp] Path services/contents.js served from /home/ncclementi/anaconda3/lib/python3.5/site-packages/notebook/static/services/contents.js
[D 16:28:27.131 NotebookApp] 200 GET /static/services/contents.js?v=20170720162825 (127.0.0.1) 2.06ms
[D 16:28:27.324 NotebookApp] 200 GET /api/config/tree?_=1500582507031 (127.0.0.1) 7.31ms
[D 16:28:27.333 NotebookApp] 200 GET /api/config/common?_=1500582507032 (127.0.0.1) 7.01ms
[D 16:28:27.409 NotebookApp] 200 GET /api/terminals?_=1500582507033 (127.0.0.1) 1.98ms
[D 16:28:27.414 NotebookApp] 200 GET /api/terminals?_=1500582507035 (127.0.0.1) 1.66ms
[D 16:28:27.418 NotebookApp] 200 GET /api/sessions?_=1500582507034 (127.0.0.1) 3.04ms
[D 16:28:27.628 NotebookApp] Found kernel python3 in /home/ncclementi/anaconda3/share/jupyter/kernels
[D 16:28:27.629 NotebookApp] Found kernel python3 in /home/ncclementi/anaconda3/share/jupyter/kernels
[D 16:28:27.634 NotebookApp] 200 GET /api/kernelspecs (127.0.0.1) 7.59ms
[D 16:28:27.636 NotebookApp] Using contents: services/contents
[W 16:28:27.663 NotebookApp] 404 GET /nbextensions/nbextensions_configurator/tree_tab/main.js?v=20170720162825 (127.0.0.1) 28.00ms referer=http://localhost:8888/tree
[D 16:28:27.664 NotebookApp] Path custom.js served from /home/ncclementi/anaconda3/lib/python3.5/site-packages/notebook/static/custom/custom.js
[D 16:28:27.666 NotebookApp] 200 GET /custom/custom.js?v=20170720162825 (127.0.0.1) 2.39ms
[D 16:28:28.282 NotebookApp] 200 GET /api/contents?type=directory&_=1500582507036 (127.0.0.1) 7.79ms
[D 16:29:16.782 NotebookApp] 200 GET /api/sessions?_=1500582507037 (127.0.0.1) 1.96ms
[D 16:29:16.869 NotebookApp] 200 GET /api/terminals?_=1500582507038 (127.0.0.1) 2.21ms
[D 16:29:17.049 NotebookApp] 200 GET /api/contents?type=directory&_=1500582507039 (127.0.0.1) 4.10ms
```

**Comment by jhamrick** [comment]
I think the errors pertaining to `jupyter_nbextensions_configurator` are unrelated -- it likely means you installed the jupyter nbextensions configurator plugin at some point (https://github.com/Jupyter-contrib/jupyter_nbextensions_configurator) and the notebook is trying to load the extension but can't import it.

I can confirm that the nbgrader nbextensions don't show up, however. I will investigate.

**Comment by jhamrick** [comment]
This should be fixed by https://github.com/conda-forge/nbgrader-feedstock/pull/16 once it is merged and the new conda package rebuilt.

**Comment by ncclementi** [comment]
Thanks @jhamrick . 
I'll try when the release is out. Meantime I'll use pip!

**Comment by jhamrick** [comment]
Ok, this should be fixed now, I just tested this and it should be working again. Let me know if you still have any issues!

**Comment by jhamrick** [comment]
Closed by https://github.com/conda-forge/nbgrader-feedstock/pull/16
