### ISSUE TITLE
JSON ValidationError on old notebooks, even after update

### ISSUE THREAD

**Issue by ddbourgin** [jupyter/nbgrader#916]
When attempting to `assign` notebooks created using an earlier version of nbgrader, I receive a JSON ValidationError, even after updating the cell metadata using `nbgrader update`, as in https://github.com/jupyter/nbgrader/issues/883. Full traceback:

```
> nbgrader update source/ps1/
[UpdateApp | WARNING] Outdated config: use CourseDirectory.directory_structure rather than NbGrader.directory_structure
[UpdateApp | WARNING] Outdated config: use CourseDirectory.db_url rather than NbGrader.db_url
[UpdateApp | WARNING] Outdated config: use CourseDirectory.db_assignments rather than NbGrader.db_assignments
[UpdateApp | WARNING] Outdated config: use CourseDirectory.db_students rather than NbGrader.db_students
[UpdateApp | WARNING] Outdated config: use Exchange.course_id rather than NbGrader.course_id
[UpdateApp | WARNING] Outdated config: use CourseDirectory.directory_structure rather than NbGrader.directory_structure
[UpdateApp | WARNING] Outdated config: use CourseDirectory.db_url rather than NbGrader.db_url
[UpdateApp | WARNING] Outdated config: use CourseDirectory.db_assignments rather than NbGrader.db_assignments
[UpdateApp | WARNING] Outdated config: use CourseDirectory.db_students rather than NbGrader.db_students
[UpdateApp | WARNING] Outdated config: use Exchange.course_id rather than NbGrader.course_id
[NbGraderApp | WARNING] Outdated config: use CourseDirectory.directory_structure rather than NbGrader.directory_structure
[NbGraderApp | WARNING] Outdated config: use CourseDirectory.db_url rather than NbGrader.db_url
[NbGraderApp | WARNING] Outdated config: use CourseDirectory.db_assignments rather than NbGrader.db_assignments
[NbGraderApp | WARNING] Outdated config: use CourseDirectory.db_students rather than NbGrader.db_students
[NbGraderApp | WARNING] Outdated config: use Exchange.course_id rather than NbGrader.course_id
[UpdateApp | INFO] Updating metadata for notebook: source/ps1/1 - Levels of Analysis.ipynb
[UpdateApp | INFO] Updating metadata for notebook: source/ps1/2 - Production Systems.ipynb
[UpdateApp | INFO] Updating metadata for notebook: source/ps1/3 - Formal Languages.ipynb
[UpdateApp | INFO] Updating metadata for notebook: source/ps1/4 - Turing Machines.ipynb
[UpdateApp | INFO] Updating metadata for notebook: source/ps1/Autograder Tests.ipynb

> nbgrader assign ps0
[AssignApp | WARNING] Outdated config: use CourseDirectory.directory_structure rather than NbGrader.directory_structure
[AssignApp | WARNING] Outdated config: use CourseDirectory.db_url rather than NbGrader.db_url
[AssignApp | WARNING] Outdated config: use CourseDirectory.db_assignments rather than NbGrader.db_assignments
[AssignApp | WARNING] Outdated config: use CourseDirectory.db_students rather than NbGrader.db_students
[AssignApp | WARNING] Outdated config: use Exchange.course_id rather than NbGrader.course_id
[AssignApp | WARNING] Outdated config: use CourseDirectory.directory_structure rather than NbGrader.directory_structure
[AssignApp | WARNING] Outdated config: use CourseDirectory.db_url rather than NbGrader.db_url
[AssignApp | WARNING] Outdated config: use CourseDirectory.db_assignments rather than NbGrader.db_assignments
[AssignApp | WARNING] Outdated config: use CourseDirectory.db_students rather than NbGrader.db_students
[AssignApp | WARNING] Outdated config: use Exchange.course_id rather than NbGrader.course_id
[NbGraderApp | WARNING] Outdated config: use CourseDirectory.directory_structure rather than NbGrader.directory_structure
[NbGraderApp | WARNING] Outdated config: use CourseDirectory.db_url rather than NbGrader.db_url
[NbGraderApp | WARNING] Outdated config: use CourseDirectory.db_assignments rather than NbGrader.db_assignments
[NbGraderApp | WARNING] Outdated config: use CourseDirectory.db_students rather than NbGrader.db_students
[NbGraderApp | WARNING] Outdated config: use Exchange.course_id rather than NbGrader.course_id
[AssignApp | INFO] Copying /home/ddbourgin/compmodels/assignments/source/ps1/./turing_machine_helper.py -> /home/ddbourgin/compmodels/assignments/release/ps1/./turing_machine_helper.py
[AssignApp | INFO] Updating/creating assignment 'ps1': {'duedate': '2016-09-25 01:00:00.000000'}
[AssignApp | INFO] Converting notebook /home/ddbourgin/compmodels/assignments/source/ps1/./1 - Levels of Analysis.ipynb
[AssignApp | ERROR] There was an error processing assignment: /home/ddbourgin/compmodels/assignments/source/ps1/.
[AssignApp | ERROR] Traceback (most recent call last):
      File "/usr/local/lib/python3.4/dist-packages/nbgrader/converters/base.py", line 293, in convert_notebooks
        self.convert_single_notebook(notebook_filename)
      File "/usr/local/lib/python3.4/dist-packages/nbgrader/converters/base.py", line 249, in convert_single_notebook
        output, resources = self.exporter.from_filename(notebook_filename, resources=resources)
      File "/usr/local/lib/python3.4/dist-packages/nbconvert/exporters/exporter.py", line 174, in from_filename
        return self.from_file(f, resources=resources, **kw)
      File "/usr/local/lib/python3.4/dist-packages/nbconvert/exporters/exporter.py", line 192, in from_file
        return self.from_notebook_node(nbformat.read(file_stream, as_version=4), resources=resources, **kw)
      File "/usr/local/lib/python3.4/dist-packages/nbconvert/exporters/notebook.py", line 31, in from_notebook_node
        nb_copy, resources = super(NotebookExporter, self).from_notebook_node(nb, resources, **kw)
      File "/usr/local/lib/python3.4/dist-packages/nbconvert/exporters/exporter.py", line 134, in from_notebook_node
        nb_copy, resources = self._preprocess(nb_copy, resources)
      File "/usr/local/lib/python3.4/dist-packages/nbconvert/exporters/exporter.py", line 311, in _preprocess
        nbc, resc = preprocessor(nbc, resc)
      File "/usr/local/lib/python3.4/dist-packages/nbconvert/preprocessors/base.py", line 47, in __call__
        return self.preprocess(nb, resources)
      File "/usr/local/lib/python3.4/dist-packages/nbgrader/preprocessors/headerfooter.py", line 24, in preprocess
        header_nb = read_nb(fh, as_version=current_nbformat)
      File "/usr/local/lib/python3.4/dist-packages/nbgrader/nbgraderformat/v1.py", line 125, in read_v1
        ValidatorV1().validate_nb(nb)
      File "/usr/local/lib/python3.4/dist-packages/nbgrader/nbgraderformat/v1.py", line 102, in validate_nb
        super(ValidatorV1, self).validate_nb(nb)
      File "/usr/local/lib/python3.4/dist-packages/nbgrader/nbgraderformat/common.py", line 35, in validate_nb
        self.validate_cell(cell)
      File "/usr/local/lib/python3.4/dist-packages/nbgrader/nbgraderformat/v1.py", line 69, in validate_cell
        super(ValidatorV1, self).validate_cell(cell)
      File "/usr/local/lib/python3.4/dist-packages/nbgrader/nbgraderformat/common.py", line 31, in validate_cell
        jsonschema.validate(cell.metadata['nbgrader'], self.schema)
      File "/usr/local/lib/python3.4/dist-packages/jsonschema/validators.py", line 541, in validate
        cls(schema, *args, **kwargs).validate(instance)
      File "/usr/local/lib/python3.4/dist-packages/jsonschema/validators.py", line 130, in validate
        raise error
    jsonschema.exceptions.ValidationError: Additional properties are not allowed ('cell_type' was unexpected)

    Failed validating 'additionalProperties' in schema:
        {'$schema': 'http://json-schema.org/draft-04/schema#',
         'additionalProperties': False,
         'properties': {'checksum': {'description': 'a checksum of the '
                                                    'cell contents; '
                                                    'generally only '
                                                    'present in the '
                                                    'student version of an '
                                                    'assignment',
                                     'maxLength': 32,
                                     'minLength': 32,
                                     'type': 'string'},
                        'grade': {'default': False,
                                  'description': 'whether this cell should '
                                                 'be graded',
                                  'type': 'boolean'},
                        'grade_id': {'description': 'the nbgrader id of '
                                                    'the cell, only '
                                                    'present if one or '
                                                    'more of '
                                                    'grade/locked/solution '
                                                    'is true',
                                     'pattern': '^[a-zA-Z0-9_\\-]*$',
                                     'type': 'string'},
                        'locked': {'default': False,
                                   'description': 'whether the cell should '
                                                  'be editable',
                                   'type': 'boolean'},
                        'points': {'description': 'the number of points '
                                                  'this cell is worth; '
                                                  'only present if grade '
                                                  'is true',
                                   'minimum': 0,
                                   'type': 'number'},
                        'schema_version': {'description': 'the version of '
                                                          'the cell '
                                                          'metadata schema',
                                           'maximum': 1,
                                           'minimum': 1,
                                           'type': 'integer'},
                        'solution': {'default': False,
                                     'description': 'whether this cell '
                                                    'contains a solution',
                                     'type': 'boolean'}},
         'required': ['schema_version', 'grade', 'locked', 'solution'],
         'title': 'nbgrader cell metadata schema',
         'type': 'object'}

    On instance:
        {'cell_type': 'release'}
```

### System Info
```
> lsb_release -a
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.5 LTS
Release:	14.04
Codename:	trusty
```

```
> nbgrader --version
nbgrader version 0.5.4
```
```
> jupyterhub --version
0.8.0
```

```
> jupyter notebook --version
5.2.2
```

**Comment by jhamrick** [comment]
From talking to @ddbourgin over email, it seems that the assignments he was using have some old metadata in them from a very old version of nbgrader. I think it is worthwhile to have `nbgrader update` remove extraneous properties from the nbgrader metadata to catch cases like this.

**Comment by ttimbers** [comment]
How is this going? I repeatedly run into this issue across machines (that are not too different in versions, but are different enough I guess...)

**Comment by jhamrick** [comment]
Hmm, can you provide an example notebook that causes this issue, and paste the exact error output? This probably shouldn't be an issue unless you're using nbgrader notebooks that are several years old (e.g. from 2015 or so), which is possible though not too many people were using nbgrader then 😄so I think it's also possible it could be something else that gives a similar error.

**Comment by psychemedia** [comment]
Can I just check the sense in which this is fixed? I'm encountering this error using both the `nbgrader` package pulled from PyPi and when pulled from repo master when I upload a notebook and try to generate an assignment from it?

```
[INFO] Updating/creating assignment 'test': {}
[INFO] Converting notebook /home/jovyan/source/./test/2019J_TMA01_q1_NBGRADER.ipynb
[ERROR] There was an error processing assignment: /home/jovyan/source/./test
[ERROR] Traceback (most recent call last):
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbgrader/converters/base.py", line 308, in convert_notebooks
        self.convert_single_notebook(notebook_filename)
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbgrader/converters/base.py", line 264, in convert_single_notebook
        output, resources = self.exporter.from_filename(notebook_filename, resources=resources)
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbconvert/exporters/exporter.py", line 178, in from_filename
        return self.from_file(f, resources=resources, **kw)
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbconvert/exporters/exporter.py", line 196, in from_file
        return self.from_notebook_node(nbformat.read(file_stream, as_version=4), resources=resources, **kw)
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbconvert/exporters/notebook.py", line 32, in from_notebook_node
        nb_copy, resources = super(NotebookExporter, self).from_notebook_node(nb, resources, **kw)
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbconvert/exporters/exporter.py", line 138, in from_notebook_node
        nb_copy, resources = self._preprocess(nb_copy, resources)
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbconvert/exporters/exporter.py", line 315, in _preprocess
        nbc, resc = preprocessor(nbc, resc)
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbconvert/preprocessors/base.py", line 47, in __call__
        return self.preprocess(nb, resources)
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbgrader/preprocessors/clearmarkingscheme.py", line 82, in preprocess
        nb, resources = super(ClearMarkScheme, self).preprocess(nb, resources)
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbconvert/preprocessors/base.py", line 69, in preprocess
        nb.cells[index], resources = self.preprocess_cell(cell, resources, index)
      File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbgrader/preprocessors/clearmarkingscheme.py", line 100, in preprocess_cell
        "Mark scheme region detected in a non-grade cell; "
    RuntimeError: Mark scheme region detected in a non-grade cell; please make sure all mark scheme regions are within 'Manually graded task' cells.
    
[ERROR] There was an error processing assignment 'test' for student '.'
[ERROR] Please see the the above traceback for details on the specific errors on the above failures.
```

(I can't share the actual notebook atm - it's for a live assignment!)
