### ISSUE TITLE
Hidden tests are revealed in feedback

### ISSUE THREAD

**Issue by aytekinar** [jupyter/nbgrader#917]
### Expected behavior

I would expect that the system to keep hiding the hidden tests in the feedback students receive.

### Actual behavior

The system reveals the hidden tests in the generated HTML file. Is this a bug, or is this actually on purpose?

### Steps to reproduce the behavior

Feedback on a student's assignment wich has hidden tests.

**Comment by lgpage** [comment]
@aytekinar this is by design. For what use case would you want to keep the tests hidden in the feedback?

**Comment by jhamrick** [comment]
Yeah, like @lgpage said that's intentional---the reasoning is that if you are grading students against hidden tests, it's still useful for the students to be able to see what they got wrong and understand why they got it wrong.

**Comment by aytekinar** [comment]
Thank you, both @lgpage and @jhamrick, for your responses. At least an option would have been great in that regard. When we allow for resubmissions, it might be better to hide the tests. Then, once the final grade is given, then the student can see what went wrong in the whole process. That would help when studying for the exams while keeping the hidden tests hidden in the intermediate submissions. I don't know, maybe our use case is not the best one :)

**Comment by jhamrick** [comment]
Ah I see, allowing for resubmissions is not something I'd considered.

I think it's probably reasonable to add an option to suppress hidden tests in the feedback, but have it be off by default, and with a warning that if the hidden tests change the state of the notebook it might be very difficult to understand the behavior of visible parts of the notebook.

**Comment by aytekinar** [comment]
Thank you for taking it as a feature/enhancement request. I cannot say anything regarding how you would implement and which default behaviour you would opt-in. But provided that there is a feature and that it is documented, I would (personally) be glad to read through and modify the settings accordingly.

Cheers :)

**Comment by bbhopesh** [comment]
HI @jhamrick. I need this feature too. Has anyone started working on this? I can if no one is.

I also wanted to hear your thoughts on how to approach this technically. Cell metadata doesn't contain any information indicating if test case is hidden or not, so we probably can't do it in the feedback template. We can either add metadata and then take care of it in the template or do some preprocessing to create a copy of notebook with hidden cases removed. Which of the two would be better? or if you better ways in mind? If it is latter, what would be best place to do that preprocessing? feedback app or converter?

**Comment by jhamrick** [comment]
Off the top of my head, I think the way to do this would be to run the `ClearHiddenTests` preprocessor during the feedback step.

**Comment by jhamrick** [comment]
#1156 brought up the of whether to keep the cell output or not. I think it might be hard to determine which output is a result of a hidden test and which is not, so I think maybe the easiest way to implement this anyways is to strip out the hidden tests from the code cell but retain all cell output.

**Comment by debbieyuster** [comment]
Another important use case for this feature: Instructor may want to reuse some exercises in a future semester, so may not want to hand out printed solution keys that can easily be passed down.

**Comment by debbieyuster** [comment]
@ykazakov Thanks for this helpful workaround. I tried putting your most recent code into a `nbgrader_config.py` file but got the following error:

>  [GenerateFeedbackApp | WARNING] Config option `preprocessors` not recognized by `GenerateFeedback`.

My entire `nbgrader_config.py` is as follows:
```
c = get_config()

c.GenerateFeedback.preprocessors = [
    'nbgrader.preprocessors.GetGrades',
    'nbconvert.preprocessors.CSSHTMLHeaderPreprocessor',
    'nbgrader.preprocessors.ClearHiddenTests',
    'nbgrader.preprocessors.Execute',
] 
```

I do have another nbgrader_config.py file in another directory, but I don't think it's being accessed.
Any chance you could quickly diagnose the problem? Presumably something important missing from my file?

**Comment by ykazakov** [comment]
@debbieyuster Oh, you are right, looks like the commit #1376 was not (yet) backported to branch 0.6.x.
I am using nbgrader from the master branch, which seems rather stable.

**Comment by debbieyuster** [comment]
@ykazakov Thanks, I really appreciate your help! I tried installing from GH but there was an error during the build and my system seems to still be using the 0.6.x installation. I'm afraid to mess with things, especially mid-semester, so at this point I am going to give up on the post-processing...hopefully a new version of nbgrader will be released soon that includes the commit you referenced.

**Comment by ykazakov** [comment]
@debbieyuster Well, there are not many changes in the commit #1376. You can do them yourself:
- locate the file `generate_feedback.py` in your python installation. For example, I have it under `/opt/conda/lib/python3.9/site-packages/nbgrader/converters/generate_feedback.py`
- append `.tag(config=True)` at the end of line 25 so that it looks like that:
```
    preprocessors = List([
        GetGrades,
        CSSHTMLHeaderPreprocessor
    ]).tag(config=True)
```

**Comment by debbieyuster** [comment]
@ykazakov Thanks, this is a great idea! It worked perfectly for the first student's notebook. This student's code had passed all my autograder tests. The subsequent notebooks all generated errors/infinite loops. I see that  commit #1376 contains changes to multiple files so perhaps I'd need to make all (or more of) those changes, and/or perhaps the new and improved `generate_feedback` will only work on new assignments, not those I created and graded before making the changes.

If anyone else is trying this on Windows 10 and using Anaconda, my `generate_feedback.py` file was located here:
`C:\ProgramData\Anaconda3\pkgs\nbgrader-0.6.1-py38haa244fe_1\Lib\site-packages\nbgrader\converters\generate_feedback.py`

Here are some of the errors I got when generating feedback through the Formgrader:
```
[WARNING] Config option `display_data_priority` not recognized by `ClearHiddenTests`.
[WARNING] Config option `display_data_priority` not recognized by `Execute`.
[...]
[ERROR] While processing assignment C:\Users\dyuster\autograded\1278\hw5, the kernel became unresponsive and we could not interrupt it. This probably means that the students' code has an infinite loop that consumes a lot of memory or something similar. nbgrader doesn't know how to deal with this problem, so you will have to manually edit the students' code (for example, to just throw an error rather than enter an infinite loop). 
```

And tracebacks:
```
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\nbgrader\utils.py", line 514, in capture_log
    app.start()
  File "C:\ProgramData\Anaconda3\lib\site-packages\nbgrader\converters\base.py", line 74, in start
    self.convert_notebooks()
  File "C:\ProgramData\Anaconda3\lib\site-packages\nbgrader\converters\base.py", line 413, in convert_notebooks
    raise NbGraderException(msg)
nbgrader.converters.base.NbGraderException: Please see the the above traceback for details on the specific errors on the above failures.
```

I'm not expecting anyone to fix this for me! Just sharing in case anyone is interested or in case it helps someone else.

For now I'll revert my code back.

**Comment by debbieyuster** [comment]
Wanted to revisit this - keeping hidden test contents out of student feedback should be doable now (see #1376 and #1519). What is the simplest way to configure this? Is it @ykazakov 's code above from 2021/10/27 or does #1519 lead to a different recommended way? Thanks in advance.

**Comment by jhamrick** [comment]
Just from a quick look I think it would still be the same as @ykazakov
described.

**Comment by debbieyuster** [comment]
It worked! Thanks to both of you!

**Comment by AIRCAP** [comment]
I used a slightly different config. As mentioned, the output of grading cells often leaks information about the code inside, especially when errors are thrown, which is the case if assertions fail.
Re-executing the notebook alone didn't fix this for me, as this somehow did not change this. I had to add an additional line to first clear all outputs, and then re-execute the whole notebook. The code working for me was

```
c.GenerateFeedback.preprocessors = [
     'nbgrader.preprocessors.GetGrades',
     'nbconvert.preprocessors.CSSHTMLHeaderPreprocessor',
     'nbgrader.preprocessors.ClearOutput',
     'nbgrader.preprocessors.ClearHiddenTests',
     'nbgrader.preprocessors.Execute',
]
```
