### ISSUE TITLE
Validate and Autograde notebook with OCaml kernel

### ISSUE THREAD

**Issue by kf71** [jupyter/nbgrader#920]
### Operating system
Ubuntu 16.04.3 LTS
### `nbgrader --version`
0.5.1
### `jupyterhub --version` (if used with JupyterHub)
0.8.1
### `jupyter notebook --version` 
5.2.2

With jupyterhub as a service.
When attempting to validate or autograde a notebook with OCaml kernel, I get the following error:

(Note1: everything is OK when I validate or autograde a notebook with a Python kernel.
Note2: everything is OK when I execute the cells of the OCaml notebook)

====================================
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/nbgrader/utils.py", line 371, in capture_log
    app.start()
  File "/usr/local/lib/python3.5/dist-packages/nbgrader/converters/base.py", line 72, in start
    self.convert_notebooks()
  File "/usr/local/lib/python3.5/dist-packages/nbgrader/converters/base.py", line 350, in convert_notebooks
    raise NbGraderException(msg)
nbgrader.converters.base.NbGraderException: Please see the the above traceback for details on the specific errors on the above failures.

=====================================================

[ERROR] There was an error processing assignment: /home/xxxx/submitted/xxxx/test_OCaml
[ERROR] Traceback (most recent call last):
      File "/usr/local/lib/python3.5/dist-packages/nbgrader/converters/base.py", line 293, in convert_notebooks
        self.convert_single_notebook(notebook_filename)
      File "/usr/local/lib/python3.5/dist-packages/nbgrader/converters/autograde.py", line 181, in convert_single_notebook
        super(Autograde, self).convert_single_notebook(notebook_filename)
      File "/usr/local/lib/python3.5/dist-packages/nbgrader/converters/base.py", line 249, in convert_single_notebook
        output, resources = self.exporter.from_filename(notebook_filename, resources=resources)
      File "/usr/local/lib/python3.5/dist-packages/nbconvert/exporters/exporter.py", line 174, in from_filename
        return self.from_file(f, resources=resources, **kw)
      File "/usr/local/lib/python3.5/dist-packages/nbconvert/exporters/exporter.py", line 192, in from_file
        return self.from_notebook_node(nbformat.read(file_stream, as_version=4), resources=resources, **kw)
      File "/usr/local/lib/python3.5/dist-packages/nbconvert/exporters/notebook.py", line 31, in from_notebook_node
        nb_copy, resources = super(NotebookExporter, self).from_notebook_node(nb, resources, **kw)
      File "/usr/local/lib/python3.5/dist-packages/nbconvert/exporters/exporter.py", line 134, in from_notebook_node
        nb_copy, resources = self._preprocess(nb_copy, resources)
      File "/usr/local/lib/python3.5/dist-packages/nbconvert/exporters/exporter.py", line 311, in _preprocess
        nbc, resc = preprocessor(nbc, resc)
      File "/usr/local/lib/python3.5/dist-packages/nbconvert/preprocessors/base.py", line 47, in __call__
        return self.preprocess(nb, resources)
      File "/usr/local/lib/python3.5/dist-packages/nbgrader/preprocessors/execute.py", line 41, in preprocess
        output = super(Execute, self).preprocess(nb, resources)
      File "/usr/local/lib/python3.5/dist-packages/nbconvert/preprocessors/execute.py", line 257, in preprocess
        cwd=path)
      File "/usr/local/lib/python3.5/dist-packages/nbconvert/preprocessors/execute.py", line 241, in start_new_kernel
        kc.wait_for_ready(timeout=startup_timeout)
      File "/usr/local/lib/python3.5/dist-packages/jupyter_client/blocking/client.py", line 111, in wait_for_ready
        msg = self.shell_channel.get_msg(block=True, timeout=1)
      File "/usr/local/lib/python3.5/dist-packages/jupyter_client/blocking/channels.py", line 55, in get_msg
        return self._recv()
      File "/usr/local/lib/python3.5/dist-packages/jupyter_client/blocking/channels.py", line 43, in _recv
        return self.session.deserialize(smsg)
      File "/usr/local/lib/python3.5/dist-packages/jupyter_client/session.py", line 923, in deserialize
        raise ValueError("Invalid Signature: %r" % signature)
    ValueError: Invalid Signature: b'37d8b02f04080d601d2dab8b71f30d33d8d4fe6256061668fd0a1d944daa2b0a'
    
[WARNING] Removing failed assignment: /home/xxxx/autograded/xxxx/test_OCaml
[ERROR] There was an error processing assignment 'test_OCaml' for student 'xxxx'
[ERROR] Please see the the above traceback for details on the specific errors on the above

================================================

Here is a minimal working example of an OCaml notebook:

<pre>
let rec factoriel n =
    (* BEGIN SOLUTION *)
    if n=1 then 1 else n*(factoriel (n-1))
    (* END SOLUTION *)
</pre>

<pre>
(* BEGIN HIDDEN TESTS *)
let () = assert (factoriel 1 = 1)
let () = assert (factoriel 4 = 24)
(* END HIDDEN TESTS *)
</pre>

=============================

The config has been modified in: usr/etc/jupyter/nbgrader_config.py
<pre>
c = get_config()
c.Exchange.course_id = "devoir"
c.Exchange.root = "/home/common/exchange"
c.ClearSolutions.code_stub={’python’:’# ENTRER VOTRE CODE ICI’,
’ocaml’: ’(* ENTRER VOTRE CODE ICI *)’}
</pre>

**Comment by kf71** [comment]
Changing OCaml kernel from IOCaml to OCaml-jupyter
https://github.com/akabe/ocaml-jupyter
solves my problem.
Sorry for disturbing

**Comment by jhamrick** [comment]
Glad you were able to get it to work---sounds like IOCaml might not be quite up-to-date with the current requirements for jupyter kernels.

I'm glad it seems to be working with the OCaml-jupyter kernel; it's good to know nbgrader is being tested with other kernels besides python!
