### ISSUE TITLE
Autograder with Java kernel: How to implement assertions?

### ISSUE THREAD

**Issue by adibaba** [jupyter/nbgrader#986]
### Operating system

cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04 LTS"

### `nbgrader --version`

Python version 3.6.5 | packaged by conda-forge | (default, Apr  6 2018, 13:39:56) 
[GCC 4.8.2 20140120 (Red Hat 4.8.2-15)]
nbgrader version 0.5.4

### `jupyterhub --version` (if used with JupyterHub)

0.9.0rc1

### `jupyter notebook --version` 

5.5.0

### Issue

I am using nbgrader on Jupyterhub with the scijava kernel. Code execution and importing packages works fine. The implementation of autograder tests with assert statements fail. A statement `assert (1==1)` is evaluated and nothing happens, which is fine. But a statement `assert (1==2)` produces an error inside the kernel, which is not recognized by nbgrader. Additionally, the autograder assigns full credit.

**Is there a way to evaluate Java assertions?**
**If not: How can errors be identified to not assign credits?**

### Expected behavior

- Assertion is evaluated as false.
- Autograder does not assign credits

### Actual behavior

- Assertion produces error (see below)
- Autograder assigns full credit

```
[ERROR] null
Assertion failed: 

assert (1==2)
         |
         false

	at org.codehaus.groovy.runtime.InvokerHelper.assertFailed(InvokerHelper.java:404)
	at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.assertFailed(ScriptBytecodeAdapter.java:650)
	at Script5.run(Script5.groovy:1)
	at org.scijava.plugins.scripting.groovy.GroovyScriptEngine.eval(GroovyScriptEngine.java:303)
	at org.scijava.plugins.scripting.groovy.GroovyScriptEngine.eval(GroovyScriptEngine.java:122)
	at javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:264)
	at org.scijava.script.ScriptModule.run(ScriptModule.java:160)
	at org.scijava.module.ModuleRunner.run(ModuleRunner.java:168)
	at org.scijava.jupyter.kernel.evaluator.Worker.run(Worker.java:108)
	at org.scijava.thread.DefaultThreadService$2.run(DefaultThreadService.java:221)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

### Steps to reproduce the behavior

- Install Jupyterhub docker version (https://hub.docker.com/r/jupyterhub/jupyterhub/)
- Install nbgrader (http://nbgrader.readthedocs.io/en/stable/user_guide/installation.html)
- Install scijava-jupyter-kernel (https://github.com/scijava/scijava-jupyter-kernel)
- If the kernel does not appear in the frontend, take a look at these solutions: https://github.com/scijava/scijava-jupyter-kernel/issues/79
- Create a notebook with the assertion above

**Comment by jhamrick** [comment]
This sounds like a bug with the java kernel, would you mind filing an issue there instead? Specifically, the thing that needs to happen is for the java kernel to send an error message kernel reply, which will cause the notebook to create an "error" output: https://github.com/jupyter/nbformat/blob/master/nbformat/v4/nbbase.py#L55

nbgrader then looks for this error output. If it's assigning full credit, that means that there is no error output on the cell which makes me think it's a problem with the java kernel not sending the right type of response.

**Comment by hkarl** [comment]
Hello, 

I was wondering if any progress has happened here? Will have the same issue as the OP soon... 

thanks, 

HK

**Comment by adibaba** [comment]
No updates from the project.
Our workflow includes to use relational operators instead of assertions an to throw Exceptions for negative results. Have also a look at the [kernel](https://github.com/jupyter/jupyter/wiki/Jupyter-kernels) named [IJava](https://github.com/SpencerPark/IJava).

**Comment by adibaba** [comment]
Using the IJava kernel, there are two solutions:

1. Use kernel.json to set the ea flag
2. Use JUnit Assertions

The kernel developer provided a comprehensive answer:
https://github.com/SpencerPark/IJava/issues/30#issuecomment-420713306

**Comment by hkarl** [comment]
Even with JUnit assertions, this does not really work. I tried a notebook as follows:  

![image](https://user-images.githubusercontent.com/1374616/45843301-82bf2180-bd1f-11e8-9681-829248641a0d.png)


It correctly throws an error and shows this when I run the cell. With my limited knowledge of how kernel and browser interact, I would think that means error messages are correctly transported?
 
But when I validate such a notebook, it shows "Success": 
 
![image](https://user-images.githubusercontent.com/1374616/45843216-4a1f4800-bd1f-11e8-8433-a0c94949f2d6.png)

Any ideas where a good place to start debugging this would be? Any help much appreciated.

**Comment by hkarl** [comment]
Digging around some more:  When putting  `print (msg)` in nbbase.py:output_from_msg(msg), an incorrect answer in a Python autograder-test gives: 

```python 
{'buffers': [],
 'content': {'ename': 'AssertionError',
             'evalue': '',
             'traceback': ['\x1b[0;31m---------------------------------------------------------------------------\x1b[0m',
                           '\x1b[0;31mAssertionError\x1b[0m                            '
                           'Traceback (most recent call last)',
                           '\x1b[0;32m<ipython-input-3-501f9a3de02f>\x1b[0m in '
                           '\x1b[0;36m<module>\x1b[0;34m()\x1b[0m\n'
                           '\x1b[1;32m      1\x1b[0m \x1b[0;31m### BEGIN '
                           'HIDDEN '
                           'TESTS\x1b[0m\x1b[0;34m\x1b[0m\x1b[0;34m\x1b[0m\x1b[0m\n'
                           '\x1b[1;32m      2\x1b[0m \x1b[0;31m# almost right '
                           ':-P\x1b[0m\x1b[0;34m\x1b[0m\x1b[0;34m\x1b[0m\x1b[0m\n'
                           '\x1b[0;32m----> 3\x1b[0;31m '
                           '\x1b[0;32massert\x1b[0m\x1b[0;34m(\x1b[0m\x1b[0mi\x1b[0m '
                           '\x1b[0;34m==\x1b[0m \x1b[0;36m4\x1b[0m '
                           '\x1b[0;32mor\x1b[0m \x1b[0mi\x1b[0m '
                           '\x1b[0;34m==\x1b[0m '
                           '\x1b[0;36m6\x1b[0m\x1b[0;34m)\x1b[0m\x1b[0;34m\x1b[0m\x1b[0m\n'
                           '\x1b[0m\x1b[1;32m      4\x1b[0m \x1b[0;31m### END '
                           'HIDDEN '
                           'TESTS\x1b[0m\x1b[0;34m\x1b[0m\x1b[0;34m\x1b[0m\x1b[0m\n',
                           '\x1b[0;31mAssertionError\x1b[0m: ']},
 'header': {'date': datetime.datetime(2018, 9, 21, 6, 46, 40, 247841, tzinfo=tzutc()),
            'msg_id': '28aa6133-9c66a4b64b9de70ee8d5bfbd',
            'msg_type': 'error',
            'session': '392ae242-27d6c058229b046fd804ec85',
            'username': 'jhubrunner',
            'version': '5.3'},
 'metadata': {},
 'msg_id': '28aa6133-9c66a4b64b9de70ee8d5bfbd',
 'msg_type': 'error',
 'parent_header': {'date': datetime.datetime(2018, 9, 21, 6, 46, 40, 168502, tzinfo=tzutc()),
                   'msg_id': '1ba495fe-fc4526323258f1db8b6a64fd',
                   'msg_type': 'execute_request',
                   'session': '097d5882-726067bce374bd5386bb365d',
                   'username': 'jhubrunner',
                   'version': '5.3'}}
```

but the corresponding output from a failed Assertion in a Java notebook gives: 

```python 
{'buffers': [],
 'content': {'ename': 'EvalException',
             'evalue': 'null',
             'traceback': ['\x1b[1m\x1b[31m---------------------------------------------------------------------------\x1b[0m',
                           '\x1b[1m\x1b[31mjava.lang.AssertionError: '
                           'null\x1b[0m',
                           '\x1b[1m\x1b[31m\tat '
                           'org.junit.Assert.fail(Assert.java:86)\x1b[0m',
                           '\x1b[1m\x1b[31m\tat '
                           'org.junit.Assert.assertTrue(Assert.java:41)\x1b[0m',
                           '\x1b[1m\x1b[31m\tat '
                           'org.junit.Assert.assertTrue(Assert.java:52)\x1b[0m',
                           '\x1b[1m\x1b[31m\tat .(#21:1)\x1b[0m']},
 'header': {'date': '2018-09-21T06:47+0000',
            'msg_id': 'f431e6ba-7137-40bc-b002-1c1733bd60d5',
            'msg_type': 'error',
            'session': '99b97474-8731cdc1500729364da4d93c',
            'username': 'jhubrunner',
            'version': '5.0'},
 'metadata': {},
 'msg_id': 'f431e6ba-7137-40bc-b002-1c1733bd60d5',
 'msg_type': 'error',
 'parent_header': {'date': datetime.datetime(2018, 9, 21, 6, 47, 16, 958255, tzinfo=tzutc()),
                   'msg_id': 'd36da9cd-923abac3ed4f2cad1ba90324',
                   'msg_type': 'execute_request',
                   'session': '99b97474-8731cdc1500729364da4d93c',
                   'username': 'jhubrunner',
                   'version': '5.3'}}
```

Is it possible that the different ename values ( `AssertionError` vs. `EvalException`) lead to different treatment later on? (Trying to trace this down currently, but a bit lost :-} )
